window.LYL_MAY = [
  // BARRO — BLUM
  { articulo: "FRUTILLERA 60", medidas: "", material: "Barro", pintada: false, precio: 119260 },
  { articulo: "MAC. COMUN Nº 16 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 5050 },
  { articulo: "MAC. COMUN Nº 18 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 6910 },
  { articulo: "PORTEÑA Nº20", medidas: "", material: "Barro", pintada: false, precio: 3240 },
  { articulo: "PORTEÑA Nº45", medidas: "", material: "Barro", pintada: false, precio: 33760 },
  { articulo: "CILINDRO N26 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 15020 },
  { articulo: "CILINDRO N22 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 10240 },
  { articulo: "CILINDRO N18 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 6620 },
  { articulo: "CILINDRO N14 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 3660 },
  { articulo: "CILINDRO N12 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 1550 },
  { articulo: "BOMBA N23 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 11360 },
  { articulo: "MAC PREMIUM N22 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 5450 },
  { articulo: "CILINDRO N18 ESMALTADO", medidas: "", material: "Barro", pintada: true, precio: 10250 },
  { articulo: "MAC. COMUN N14 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 4260 },
  { articulo: "CILINDRO ESMALTADO N12", medidas: "", material: "Barro", pintada: true, precio: 3580 },
  { articulo: "CILINDRO ESMALTADO N14", medidas: "", material: "Barro", pintada: true, precio: 6930 },
  { articulo: "MAC PREMIUM ESMALTADA N22", medidas: "", material: "Barro", pintada: true, precio: 10990 },
  { articulo: "ICONO N12", medidas: "", material: "Barro", pintada: false, precio: 1210 },
  { articulo: "ICONO N14", medidas: "", material: "Barro", pintada: false, precio: 1260 },
  { articulo: "ICONO N16", medidas: "", material: "Barro", pintada: false, precio: 1900 },
  { articulo: "ICONO N18", medidas: "", material: "Barro", pintada: false, precio: 2300 },
  { articulo: "ICONO N20", medidas: "", material: "Barro", pintada: false, precio: 2820 },
  { articulo: "CILINDRO ESMALTADO N22", medidas: "", material: "Barro", pintada: true, precio: 20410 },
  { articulo: "AMERICANA Nº23", medidas: "", material: "Barro", pintada: false, precio: 5710 },
  { articulo: "AMERICANA Nº29", medidas: "", material: "Barro", pintada: false, precio: 10600 },
  { articulo: "AMERICANA Nº36", medidas: "", material: "Barro", pintada: false, precio: 17140 },
  { articulo: "BALCONERA Nº45", medidas: "", material: "Barro", pintada: false, precio: 11590 },
  { articulo: "BOLS COLGANTE N24", medidas: "", material: "Barro", pintada: false, precio: 4780 },
  { articulo: "BOLS Nº13", medidas: "", material: "Barro", pintada: false, precio: 2000 },
  { articulo: "BOLS Nº17", medidas: "", material: "Barro", pintada: false, precio: 3110 },
  { articulo: "BOLS Nº21", medidas: "", material: "Barro", pintada: false, precio: 4920 },
  { articulo: "BOLS Nº25", medidas: "", material: "Barro", pintada: false, precio: 6710 },
  { articulo: "BOMBA Nº08", medidas: "", material: "Barro", pintada: false, precio: 2330 },
  { articulo: "BOMBA Nº14", medidas: "", material: "Barro", pintada: false, precio: 4630 },
  { articulo: "BOMBA Nº16", medidas: "", material: "Barro", pintada: false, precio: 5760 },
  { articulo: "BOMBA Nº19", medidas: "", material: "Barro", pintada: false, precio: 7360 },
  { articulo: "BOMBA Nº23", medidas: "", material: "Barro", pintada: false, precio: 11330 },
  { articulo: "BOMBA Nº35", medidas: "", material: "Barro", pintada: false, precio: 27670 },
  { articulo: "BOMBA Nº40", medidas: "", material: "Barro", pintada: false, precio: 41080 },
  { articulo: "BOMBA Nº50", medidas: "", material: "Barro", pintada: false, precio: 62250 },
  { articulo: "CILINDRO C/BORDE Nº15", medidas: "", material: "Barro", pintada: false, precio: 2630 },
  { articulo: "CILINDRO C/BORDE Nº19", medidas: "", material: "Barro", pintada: false, precio: 3910 },
  { articulo: "CILINDRO C/BORDE Nº24", medidas: "", material: "Barro", pintada: false, precio: 6300 },
  { articulo: "CILINDRO C/BORDE Nº30", medidas: "", material: "Barro", pintada: false, precio: 13290 },
  { articulo: "CILINDRO C/BORDE Nº38", medidas: "", material: "Barro", pintada: false, precio: 23740 },
  { articulo: "CILINDRO C/BORDE Nº48", medidas: "", material: "Barro", pintada: false, precio: 54040 },
  { articulo: "CILINDRO Nº12", medidas: "", material: "Barro", pintada: false, precio: 1540 },
  { articulo: "CILINDRO Nº14", medidas: "", material: "Barro", pintada: false, precio: 3650 },
  { articulo: "CILINDRO Nº18", medidas: "", material: "Barro", pintada: false, precio: 6600 },
  { articulo: "CILINDRO Nº22", medidas: "", material: "Barro", pintada: false, precio: 10210 },
  { articulo: "CILINDRO Nº26", medidas: "", material: "Barro", pintada: false, precio: 14980 },
  { articulo: "CILINDRO Nº30", medidas: "", material: "Barro", pintada: false, precio: 22040 },
  { articulo: "COLGADERA Nº25", medidas: "", material: "Barro", pintada: false, precio: 7080 },
  { articulo: "COLGADERA Nº30", medidas: "", material: "Barro", pintada: false, precio: 12350 },
  { articulo: "CONO 31", medidas: "", material: "Barro", pintada: false, precio: 7010 },
  { articulo: "CONO 40", medidas: "", material: "Barro", pintada: false, precio: 13900 },
  { articulo: "CONO 48", medidas: "", material: "Barro", pintada: false, precio: 21280 },
  { articulo: "CONO 55 CM", medidas: "", material: "Barro", pintada: false, precio: 35950 },
  { articulo: "FESTONEADA Nº08", medidas: "", material: "Barro", pintada: false, precio: 2290 },
  { articulo: "FESTONEADA Nº10", medidas: "", material: "Barro", pintada: false, precio: 3010 },
  { articulo: "FESTONEADA Nº16", medidas: "", material: "Barro", pintada: false, precio: 5600 },
  { articulo: "FESTONEADA Nº19", medidas: "", material: "Barro", pintada: false, precio: 7720 },
  { articulo: "FESTONEADA Nº24", medidas: "", material: "Barro", pintada: false, precio: 8870 },
  { articulo: "FESTONEADA Nº30", medidas: "", material: "Barro", pintada: false, precio: 21430 },
  { articulo: "FESTONEADA Nº45", medidas: "", material: "Barro", pintada: false, precio: 62880 },
  { articulo: "FESTONEADA Nº58", medidas: "", material: "Barro", pintada: false, precio: 94340 },
  { articulo: "FRUTILLERA 40", medidas: "", material: "Barro", pintada: false, precio: 59630 },
  { articulo: "ITALIANA Nº14", medidas: "", material: "Barro", pintada: false, precio: 1790 },
  { articulo: "ITALIANA Nº16", medidas: "", material: "Barro", pintada: false, precio: 2120 },
  { articulo: "ITALIANA Nº18", medidas: "", material: "Barro", pintada: false, precio: 2890 },
  { articulo: "ITALIANA Nº20", medidas: "", material: "Barro", pintada: false, precio: 3820 },
  { articulo: "ITALIANA Nº22", medidas: "", material: "Barro", pintada: false, precio: 5370 },
  { articulo: "ITALIANA Nº24", medidas: "", material: "Barro", pintada: false, precio: 6960 },
  { articulo: "ITALIANA Nº26", medidas: "", material: "Barro", pintada: false, precio: 9210 },
  { articulo: "ITALIANA Nº30", medidas: "", material: "Barro", pintada: false, precio: 11610 },
  { articulo: "ITALIANA Nº35", medidas: "", material: "Barro", pintada: false, precio: 16880 },
  { articulo: "ITALIANA Nº40", medidas: "", material: "Barro", pintada: false, precio: 21920 },
  { articulo: "ITALIANA Nº48", medidas: "", material: "Barro", pintada: false, precio: 36500 },
  { articulo: "ITALIANA Nº52", medidas: "", material: "Barro", pintada: false, precio: 53030 },
  { articulo: "JARD. C.ROMA Nº31", medidas: "", material: "Barro", pintada: false, precio: 9970 },
  { articulo: "JARD. C.ROMA Nº52", medidas: "", material: "Barro", pintada: false, precio: 25690 },
  { articulo: "JARDINERA Nº30", medidas: "", material: "Barro", pintada: false, precio: 9090 },
  { articulo: "JARDINERA Nº40", medidas: "", material: "Barro", pintada: false, precio: 16620 },
  { articulo: "JARDINERA Nº50", medidas: "", material: "Barro", pintada: false, precio: 23980 },
  { articulo: "LEBRILLO Nº22", medidas: "", material: "Barro", pintada: false, precio: 4720 },
  { articulo: "LEBRILLO Nº26", medidas: "", material: "Barro", pintada: false, precio: 6640 },
  { articulo: "LEBRILLO Nº30", medidas: "", material: "Barro", pintada: false, precio: 9120 },
  { articulo: "LEBRILLO Nº34", medidas: "", material: "Barro", pintada: false, precio: 11390 },
  { articulo: "LEBRILLO Nº38", medidas: "", material: "Barro", pintada: false, precio: 14010 },
  { articulo: "LEBRILLO Nº45", medidas: "", material: "Barro", pintada: false, precio: 22860 },
  { articulo: "LEBRILLO Nº52", medidas: "", material: "Barro", pintada: false, precio: 34030 },
  { articulo: "MAC. COMUN Nº 04", medidas: "", material: "Barro", pintada: false, precio: 740 },
  { articulo: "MAC. COMUN Nº 05", medidas: "", material: "Barro", pintada: false, precio: 750 },
  { articulo: "MAC. COMUN Nº 07", medidas: "", material: "Barro", pintada: false, precio: 950 },
  { articulo: "MAC. COMUN Nº 08", medidas: "", material: "Barro", pintada: false, precio: 1090 },
  { articulo: "MAC. COMUN Nº 10", medidas: "", material: "Barro", pintada: false, precio: 1120 },
  { articulo: "MAC. COMUN Nº 12", medidas: "", material: "Barro", pintada: false, precio: 1260 },
  { articulo: "MAC. COMUN Nº 14", medidas: "", material: "Barro", pintada: false, precio: 1500 },
  { articulo: "MAC. COMUN Nº 16", medidas: "", material: "Barro", pintada: false, precio: 1970 },
  { articulo: "MAC. COMUN Nº 18", medidas: "", material: "Barro", pintada: false, precio: 2740 },
  { articulo: "MAC. COMUN Nº 20", medidas: "", material: "Barro", pintada: false, precio: 3380 },
  { articulo: "MAC. COMUN Nº 22", medidas: "", material: "Barro", pintada: false, precio: 5430 },
  { articulo: "MAC. COMUN Nº 24", medidas: "", material: "Barro", pintada: false, precio: 6310 },
  { articulo: "MAC. COMUN Nº 26", medidas: "", material: "Barro", pintada: false, precio: 7820 },
  { articulo: "MAC. COMUN Nº 28", medidas: "", material: "Barro", pintada: false, precio: 8950 },
  { articulo: "MAC. COMUN Nº 30", medidas: "", material: "Barro", pintada: false, precio: 10590 },
  { articulo: "MAC. COMUN Nº 35", medidas: "", material: "Barro", pintada: false, precio: 13900 },
  { articulo: "MAC. COMUN Nº 40", medidas: "", material: "Barro", pintada: false, precio: 21830 },
  { articulo: "MAC. COMUN Nº 48", medidas: "", material: "Barro", pintada: false, precio: 33310 },
  { articulo: "MAC. COMUN Nº 52", medidas: "", material: "Barro", pintada: false, precio: 52050 },
  { articulo: "AGUSTINIANA Nº20", medidas: "", material: "Barro", pintada: false, precio: 6990 },
  { articulo: "AGUSTINIANA Nº27", medidas: "", material: "Barro", pintada: false, precio: 15720 },
  { articulo: "AGUSTINIANA Nº34", medidas: "", material: "Barro", pintada: false, precio: 30590 },
  { articulo: "AGUSTINIANA Nº40", medidas: "", material: "Barro", pintada: false, precio: 48650 },
  { articulo: "AGUSTINIANA Nº60", medidas: "", material: "Barro", pintada: false, precio: 93190 },
  { articulo: "NIDO DE PALOMA Nº24", medidas: "", material: "Barro", pintada: false, precio: 6240 },
  { articulo: "PAILA Nº35", medidas: "", material: "Barro", pintada: false, precio: 10680 },
  { articulo: "PAILA Nº48", medidas: "", material: "Barro", pintada: false, precio: 22960 },
  { articulo: "PAILA Nº62", medidas: "", material: "Barro", pintada: false, precio: 41000 },
  { articulo: "PIE DE MACETA Nº45", medidas: "", material: "Barro", pintada: false, precio: 1220 },
  { articulo: "PIE DE MACETA Nº90", medidas: "", material: "Barro", pintada: false, precio: 1600 },
  { articulo: "PLATO Nº 08", medidas: "", material: "Barro", pintada: false, precio: 1010 },
  { articulo: "PLATO Nº 10", medidas: "", material: "Barro", pintada: false, precio: 1090 },
  { articulo: "PLATO Nº 12", medidas: "", material: "Barro", pintada: false, precio: 1150 },
  { articulo: "PLATO Nº 14", medidas: "", material: "Barro", pintada: false, precio: 1410 },
  { articulo: "PLATO Nº 16", medidas: "", material: "Barro", pintada: false, precio: 1830 },
  { articulo: "PLATO Nº 18", medidas: "", material: "Barro", pintada: false, precio: 2250 },
  { articulo: "PLATO Nº 20", medidas: "", material: "Barro", pintada: false, precio: 2770 },
  { articulo: "PLATO Nº 22", medidas: "", material: "Barro", pintada: false, precio: 4290 },
  { articulo: "PLATO Nº 24", medidas: "", material: "Barro", pintada: false, precio: 5650 },
  { articulo: "PLATO Nº 26", medidas: "", material: "Barro", pintada: false, precio: 7000 },
  { articulo: "PLATO Nº 28", medidas: "", material: "Barro", pintada: false, precio: 8460 },
  { articulo: "PLATO Nº 30", medidas: "", material: "Barro", pintada: false, precio: 10230 },
  { articulo: "PLATO Nº 35", medidas: "", material: "Barro", pintada: false, precio: 11980 },
  { articulo: "PLATO Nº 40", medidas: "", material: "Barro", pintada: false, precio: 14500 },
  { articulo: "PLATO Nº 45", medidas: "", material: "Barro", pintada: false, precio: 20210 },
  { articulo: "PLATO Nº 52", medidas: "", material: "Barro", pintada: false, precio: 25060 },
  { articulo: "TERRINA Nº10", medidas: "", material: "Barro", pintada: false, precio: 1740 },
  { articulo: "TERRINA Nº12", medidas: "", material: "Barro", pintada: false, precio: 1950 },
  { articulo: "TERRINA Nº14", medidas: "", material: "Barro", pintada: false, precio: 2110 },
  { articulo: "TERRINA Nº22", medidas: "", material: "Barro", pintada: false, precio: 5210 },
  { articulo: "TERRINA Nº24", medidas: "", material: "Barro", pintada: false, precio: 6850 },
  { articulo: "TERRINA Nº27", medidas: "", material: "Barro", pintada: false, precio: 10090 },
  { articulo: "MAC. COMUN N*6", medidas: "", material: "Barro", pintada: false, precio: 850 },
  { articulo: "MAC. PREMIUM N22", medidas: "", material: "Barro", pintada: false, precio: 5430 },
  { articulo: "BOMBA Nº30", medidas: "", material: "Barro", pintada: false, precio: 20450 },
  { articulo: "MAC. COMUN Nº 10 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 2810 },
  { articulo: "MAC. COMUN Nº 12 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 3270 },
  { articulo: "MAC. COMUN Nº 22 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 11090 },
  { articulo: "MAC. COMUN Nº 08 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 2360 },
  { articulo: "ICONO Nº 8", medidas: "", material: "Barro", pintada: false, precio: 1090 },
  { articulo: "ICONO Nº 10", medidas: "", material: "Barro", pintada: false, precio: 1120 },
  { articulo: "ICONO Nº 8  PINTADA", medidas: "", material: "Barro", pintada: true, precio: 2250 },
  { articulo: "ICONO Nº 10  PINTADA", medidas: "", material: "Barro", pintada: true, precio: 2680 },
  // BARRO ARTESANAL — CACHARROS
  { articulo: "Nº3 (*) 20CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9750 },
  { articulo: "MATERON GIGANTE 10CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 2850 },
  { articulo: "Nº1  (*) 16CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 4720 },
  { articulo: "PREMIUM N22", medidas: "", material: "Barro Artesanal", pintada: false, precio: 7950 },
  { articulo: "PREMIUM N18", medidas: "", material: "Barro Artesanal", pintada: false, precio: 5930 },
  { articulo: "BANDEJA OVAL GRANDE 30CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 14820 },
  { articulo: "OLLA CHICA CUADRADA Y REDONDA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 14820 },
  { articulo: "OLLA MEDIANA REDONDA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 19760 },
  { articulo: "OLLA EXTRA GRANDE OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 27000 },
  { articulo: "VOLCADO GIGANTE SUPER 40CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 49500 },
  { articulo: "CHANCHITOS CH.", medidas: "", material: "Barro Artesanal", pintada: false, precio: 6590 },
  { articulo: "CHANCHITOS GRANDE", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9220 },
  { articulo: "N4 30CM BOCA C/MANIJA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 24300 },
  { articulo: "JARRAS GRANDE 24CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 7250 },
  { articulo: "JARRA CHICA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 4940 },
  { articulo: "GIGANTE SUPER", medidas: "", material: "Barro Artesanal", pintada: false, precio: 19120 },
  { articulo: "VOLCADO 1 30CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 19120 },
  // FIBROCEMENTO PINTADO
  // FIBROCEMENTO SIN PINTAR
  // ROTOMOLDEADO
  { articulo: "Misionera", medidas: "20cm c/plato", material: "Rotomoldeado", pintada: false, precio: 6300 },
  { articulo: "Misionera", medidas: "30cm c/plato", material: "Rotomoldeado", pintada: false, precio: 15200 },
  { articulo: "Misionera", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 39300 },
  { articulo: "Misionera", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 65900 },
  { articulo: "Misionera", medidas: "60cm", material: "Rotomoldeado", pintada: false, precio: 98000 },
  { articulo: "Misionera Texturada", medidas: "20h x 15Ø x 18b", material: "Rotomoldeado", pintada: false, precio: 6630 },
  { articulo: "Misionera Texturada", medidas: "30h x 22Ø x 18b", material: "Rotomoldeado", pintada: false, precio: 20550 },
  { articulo: "Cuenco", medidas: "32cm c/plato", material: "Rotomoldeado", pintada: false, precio: 43000 },
  { articulo: "Cuenco", medidas: "48cm c/plato", material: "Rotomoldeado", pintada: false, precio: 101200 },
  { articulo: "Gota", medidas: "40cm c/plato", material: "Rotomoldeado", pintada: false, precio: 40600 },
  { articulo: "Gota", medidas: "55cm c/plato", material: "Rotomoldeado", pintada: false, precio: 57000 },
  { articulo: "Gota", medidas: "70cm c/plato", material: "Rotomoldeado", pintada: false, precio: 68500 },
  { articulo: "Copa", medidas: "40cm c/plato", material: "Rotomoldeado", pintada: false, precio: 31100 },
  { articulo: "Copa", medidas: "55cm c/plato", material: "Rotomoldeado", pintada: false, precio: 60600 },
  { articulo: "Copa", medidas: "70cm c/plato", material: "Rotomoldeado", pintada: false, precio: 100400 },
  { articulo: "Cubo", medidas: "20x20x20", material: "Rotomoldeado", pintada: false, precio: 11100 },
  { articulo: "Cubo", medidas: "30x30x30", material: "Rotomoldeado", pintada: false, precio: 19700 },
  { articulo: "Cubo", medidas: "40x40x40", material: "Rotomoldeado", pintada: false, precio: 42700 },
  { articulo: "Cubo", medidas: "50x50x50", material: "Rotomoldeado", pintada: false, precio: 73300 },
  { articulo: "Piramidal", medidas: "40h x 25bo x 22b", material: "Rotomoldeado", pintada: false, precio: 19100 },
  { articulo: "Piramidal", medidas: "60h x 30bo x 25b", material: "Rotomoldeado", pintada: false, precio: 33800 },
  { articulo: "Piramidal", medidas: "70h x 35bo x 30b", material: "Rotomoldeado", pintada: false, precio: 44900 },
  { articulo: "Cilindro", medidas: "30x30", material: "Rotomoldeado", pintada: false, precio: 40800 },
  { articulo: "Cilindro", medidas: "50x50", material: "Rotomoldeado", pintada: false, precio: 60750 },
  { articulo: "Jardinera", medidas: "60x20x20", material: "Rotomoldeado", pintada: false, precio: 25600 },
  { articulo: "Jardinera", medidas: "80x27x30", material: "Rotomoldeado", pintada: false, precio: 53600 },
  { articulo: "Jardinera", medidas: "100x27x30", material: "Rotomoldeado", pintada: false, precio: 66700 },
  { articulo: "Paris", medidas: "30cm", material: "Rotomoldeado", pintada: false, precio: 34800 },
  { articulo: "Paris", medidas: "44cm", material: "Rotomoldeado", pintada: false, precio: 40600 },
  { articulo: "Misionera Texturada", medidas: "30cm", material: "Rotomoldeado", pintada: false, precio: 18200 },
  { articulo: "Misionera Texturada", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 35500 },
  { articulo: "Plato Misionera", medidas: "Chico", material: "Rotomoldeado", pintada: false, precio: 5600 },
  { articulo: "Plato Misionera", medidas: "Mediano", material: "Rotomoldeado", pintada: false, precio: 9600 },
  { articulo: "Plato Misionera", medidas: "Grande", material: "Rotomoldeado", pintada: false, precio: 13500 },
  // CERÁMICA
  { articulo: "Coco Nº1", medidas: "10h x 11d x 8b", material: "Cerámica", pintada: false, precio: 23210 },
  { articulo: "Coco Nº2", medidas: "14h x 14d x 11b", material: "Cerámica", pintada: false, precio: 35640 },
  { articulo: "Coco Nº3", medidas: "18h x 17d x 14b", material: "Cerámica", pintada: false, precio: 63690 },
  { articulo: "Coco Nº4", medidas: "24h x 22d x 18b", material: "Cerámica", pintada: false, precio: 117650 },
  { articulo: "Maceta Nº1", medidas: "9h x 11d x 6b", material: "Cerámica", pintada: false, precio: 13140 },
  { articulo: "Maceta Nº2", medidas: "14h x 16d x 10b", material: "Cerámica", pintada: false, precio: 23180 },
  { articulo: "Maceta Nº3", medidas: "18h x 20d x 12b", material: "Cerámica", pintada: false, precio: 33090 },
  { articulo: "Maceta Nº4", medidas: "31h x 29d x 18b", material: "Cerámica", pintada: false, precio: 74710 },
  // PLÁSTICO (muestra)
  { articulo: "Plato Nº12", medidas: "Nº12", material: "Plástico", pintada: false, precio: 750 },
  { articulo: "Plato Nº16", medidas: "Nº16", material: "Plástico", pintada: false, precio: 810 },
  { articulo: "Plato Nº20", medidas: "Nº20", material: "Plástico", pintada: false, precio: 1050 },
  { articulo: "Plato Nº24", medidas: "Nº24", material: "Plástico", pintada: false, precio: 1380 },
  { articulo: "Plato Nº36", medidas: "Nº36", material: "Plástico", pintada: false, precio: 2410 },
  { articulo: "Plato Nº40", medidas: "Nº40", material: "Plástico", pintada: false, precio: 3180 },
  { articulo: "Regadera", medidas: "2 lts", material: "Plástico", pintada: false, precio: 5870 },
  { articulo: "Regadera", medidas: "5 lts", material: "Plástico", pintada: false, precio: 10300 },
  { articulo: "Regadera", medidas: "10 lts", material: "Plástico", pintada: false, precio: 18580 },
  { articulo: "MAC JARDINERA", medidas: "35 CM", material: "Plástico", pintada: false, precio: 2650 },
  { articulo: "MAC JARDINERA", medidas: "45 CM", material: "Plástico", pintada: false, precio: 3920 },
  { articulo: "MAC JARDINERA", medidas: "60 CM", material: "Plástico", pintada: false, precio: 7950 },
  { articulo: "MAC JARDINERA IMPERIO", medidas: "50 CM", material: "Plástico", pintada: false, precio: 11910 },
  { articulo: "MAC JARDINERA IMPERIO", medidas: "80 CM", material: "Plástico", pintada: false, precio: 26640 },

  // ROTOMOLDEADO — nuevos modelos
  { articulo: "Cubo", medidas: "25x25x25", material: "Rotomoldeado", pintada: false, precio: 15300 },
  { articulo: "Cubo", medidas: "35x35x35", material: "Rotomoldeado", pintada: false, precio: 29000 },
  { articulo: "Piramidal", medidas: "50h x 25bo x 22b", material: "Rotomoldeado", pintada: false, precio: 23400 },
  { articulo: "Jardinera", medidas: "80x20x20", material: "Rotomoldeado", pintada: false, precio: 33700 },
  { articulo: "Jardinera", medidas: "100x20x20", material: "Rotomoldeado", pintada: false, precio: 40600 },
  { articulo: "Jardinera", medidas: "60x27x30", material: "Rotomoldeado", pintada: false, precio: 40600 },
  { articulo: "Cilindro", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 39400 },
  { articulo: "Cilindro", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 58700 },
  { articulo: "Misionera Texturada", medidas: "20cm", material: "Rotomoldeado", pintada: false, precio: 5800 },
  { articulo: "Misionera Texturada", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 69600 },

  // ROTOMOLDEADO — RAYUM Andina (actualizado)
  { articulo: "JARDINERA 40x20x30", medidas: "40x20x30", material: "Rotomoldeado", pintada: false, precio: 35800 },
  { articulo: "JARDINERA 60x20x30", medidas: "60x20x30", material: "Rotomoldeado", pintada: false, precio: 67100 },
  { articulo: "JARDINERA 80x20x30", medidas: "80x20x30", material: "Rotomoldeado", pintada: false, precio: 93400 },

  // ROTOMOLDEADO — RAYUM Andina (actualizado)
  { articulo: "ANDINA N27 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 20100 },
  { articulo: "ANDINA N40 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 43800 },
  { articulo: "ANDINA N50 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 74800 },
  { articulo: "ANDINA N65 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 148300 },
  { articulo: "ANDINA N80 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 236600 },
  { articulo: "ANDINA N40 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 38100 },
  { articulo: "ANDINA N50 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 65000 },
  { articulo: "ANDINA N65 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 128900 },
  { articulo: "ANDINA N80 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 205700 },
  { articulo: "JARDINERA RAYUM", medidas: "40x20x30", material: "Rotomoldeado", pintada: false, precio: 35800 },
  { articulo: "JARDINERA RAYUM", medidas: "60x20x30", material: "Rotomoldeado", pintada: false, precio: 67100 },
  { articulo: "JARDINERA RAYUM", medidas: "80x20x30", material: "Rotomoldeado", pintada: false, precio: 93400 },

  { articulo: "Van Gogh", medidas: "", material: "Rotomoldeado", pintada: false, precio: 19900 },

  // ── FIBROCEMENTO ──
  { articulo: "Misionera · Natural / Cruda", medidas: "20altx18bocx16bas", material: "Fibrocemento", pintada: false, precio: 4900 },
  { articulo: "Misionera · Impermeabilizada", medidas: "20altx18bocx16bas", material: "Fibrocemento", pintada: false, precio: 8200 },
  { articulo: "Misionera · Pintada", medidas: "20altx18bocx16bas", material: "Fibrocemento", pintada: true, precio: 9100 },
  { articulo: "Misionera · Natural / Cruda", medidas: "28altx18bocx15bas", material: "Fibrocemento", pintada: false, precio: 10900 },
  { articulo: "Misionera · Impermeabilizada", medidas: "28altx18bocx15bas", material: "Fibrocemento", pintada: false, precio: 18100 },
  { articulo: "Misionera · Pintada", medidas: "28altx18bocx15bas", material: "Fibrocemento", pintada: true, precio: 19900 },
  { articulo: "Misionera · Natural / Cruda", medidas: "38altx28bocx20bas", material: "Fibrocemento", pintada: false, precio: 17300 },
  { articulo: "Misionera · Impermeabilizada", medidas: "38altx28bocx20bas", material: "Fibrocemento", pintada: false, precio: 28800 },
  { articulo: "Misionera · Pintada", medidas: "38altx28bocx20bas", material: "Fibrocemento", pintada: true, precio: 31700 },
  { articulo: "Misionera · Natural / Cruda", medidas: "50altx37bocx32bas", material: "Fibrocemento", pintada: false, precio: 21200 },
  { articulo: "Misionera · Impermeabilizada", medidas: "50altx37bocx32bas", material: "Fibrocemento", pintada: false, precio: 35400 },
  { articulo: "Misionera · Pintada", medidas: "50altx37bocx32bas", material: "Fibrocemento", pintada: true, precio: 38900 },
  { articulo: "Misionera · Natural / Cruda", medidas: "63altx40bocx32bas", material: "Fibrocemento", pintada: false, precio: 32100 },
  { articulo: "Misionera · Impermeabilizada", medidas: "63altx40bocx32bas", material: "Fibrocemento", pintada: false, precio: 53500 },
  { articulo: "Misionera · Pintada", medidas: "63altx40bocx32bas", material: "Fibrocemento", pintada: true, precio: 58900 },
  { articulo: "Misionera · Natural / Cruda", medidas: "67altx37bocx32bas", material: "Fibrocemento", pintada: false, precio: 31100 },
  { articulo: "Misionera · Impermeabilizada", medidas: "67altx37bocx32bas", material: "Fibrocemento", pintada: false, precio: 51800 },
  { articulo: "Misionera · Pintada", medidas: "67altx37bocx32bas", material: "Fibrocemento", pintada: true, precio: 57000 },
  { articulo: "Misionera · Natural / Cruda", medidas: "90altx40bocx35bas", material: "Fibrocemento", pintada: false, precio: 52500 },
  { articulo: "Misionera · Impermeabilizada", medidas: "90altx40bocx35bas", material: "Fibrocemento", pintada: false, precio: 87500 },
  { articulo: "Misionera · Pintada", medidas: "90altx40bocx35bas", material: "Fibrocemento", pintada: true, precio: 96200 },
  { articulo: "Misionera · Natural / Cruda", medidas: "80altx50bocx40bas", material: "Fibrocemento", pintada: false, precio: 55600 },
  { articulo: "Misionera · Impermeabilizada", medidas: "80altx50bocx40bas", material: "Fibrocemento", pintada: false, precio: 92600 },
  { articulo: "Misionera · Pintada", medidas: "80altx50bocx40bas", material: "Fibrocemento", pintada: true, precio: 101900 },
  { articulo: "Misionera con Borde · Natural / Cruda", medidas: "35altx32bocx30bas", material: "Fibrocemento", pintada: false, precio: 17400 },
  { articulo: "Misionera con Borde · Impermeabilizada", medidas: "35altx32bocx30bas", material: "Fibrocemento", pintada: false, precio: 29000 },
  { articulo: "Misionera con Borde · Pintada", medidas: "35altx32bocx30bas", material: "Fibrocemento", pintada: true, precio: 31900 },
  { articulo: "Misionera con Borde · Natural / Cruda", medidas: "45altx45bocx42bas", material: "Fibrocemento", pintada: false, precio: 22800 },
  { articulo: "Misionera con Borde · Impermeabilizada", medidas: "45altx45bocx42bas", material: "Fibrocemento", pintada: false, precio: 38000 },
  { articulo: "Misionera con Borde · Pintada", medidas: "45altx45bocx42bas", material: "Fibrocemento", pintada: true, precio: 41800 },
  { articulo: "Misionera con Borde · Natural / Cruda", medidas: "55altx50bocx45bas", material: "Fibrocemento", pintada: false, precio: 41400 },
  { articulo: "Misionera con Borde · Impermeabilizada", medidas: "55altx50bocx45bas", material: "Fibrocemento", pintada: false, precio: 69000 },
  { articulo: "Misionera con Borde · Pintada", medidas: "55altx50bocx45bas", material: "Fibrocemento", pintada: true, precio: 75900 },
  { articulo: "Misionera Recta · Natural / Cruda", medidas: "40hx35Øx40bas", material: "Fibrocemento", pintada: false, precio: 22000 },
  { articulo: "Misionera Recta · Impermeabilizada", medidas: "40hx35Øx40bas", material: "Fibrocemento", pintada: false, precio: 36700 },
  { articulo: "Misionera Recta · Pintada", medidas: "40hx35Øx40bas", material: "Fibrocemento", pintada: true, precio: 40400 },
  { articulo: "Misionera Recta · Natural / Cruda", medidas: "55hx35Øx40bas", material: "Fibrocemento", pintada: false, precio: 24800 },
  { articulo: "Misionera Recta · Impermeabilizada", medidas: "55hx35Øx40bas", material: "Fibrocemento", pintada: false, precio: 41400 },
  { articulo: "Misionera Recta · Pintada", medidas: "55hx35Øx40bas", material: "Fibrocemento", pintada: true, precio: 45500 },
  { articulo: "Misionera Recta · Natural / Cruda", medidas: "70hx35Øx40bas", material: "Fibrocemento", pintada: false, precio: 31400 },
  { articulo: "Misionera Recta · Impermeabilizada", medidas: "70hx35Øx40bas", material: "Fibrocemento", pintada: false, precio: 52400 },
  { articulo: "Misionera Recta · Pintada", medidas: "70hx35Øx40bas", material: "Fibrocemento", pintada: true, precio: 57600 },
  { articulo: "Salteña · Natural / Cruda", medidas: "27altx24bocx20bas", material: "Fibrocemento", pintada: false, precio: 8900 },
  { articulo: "Salteña · Impermeabilizada", medidas: "27altx24bocx20bas", material: "Fibrocemento", pintada: false, precio: 14900 },
  { articulo: "Salteña · Pintada", medidas: "27altx24bocx20bas", material: "Fibrocemento", pintada: true, precio: 16400 },
  { articulo: "Salteña · Natural / Cruda", medidas: "45altx35bocx20bas", material: "Fibrocemento", pintada: false, precio: 16100 },
  { articulo: "Salteña · Impermeabilizada", medidas: "45altx35bocx20bas", material: "Fibrocemento", pintada: false, precio: 26800 },
  { articulo: "Salteña · Pintada", medidas: "45altx35bocx20bas", material: "Fibrocemento", pintada: true, precio: 29400 },
  { articulo: "Salteña · Natural / Cruda", medidas: "45altx40bocx20bas", material: "Fibrocemento", pintada: false, precio: 17000 },
  { articulo: "Salteña · Impermeabilizada", medidas: "45altx40bocx20bas", material: "Fibrocemento", pintada: false, precio: 28300 },
  { articulo: "Salteña · Pintada", medidas: "45altx40bocx20bas", material: "Fibrocemento", pintada: true, precio: 31100 },
  { articulo: "Salteña · Natural / Cruda", medidas: "41altx50bocx35bas", material: "Fibrocemento", pintada: false, precio: 21600 },
  { articulo: "Salteña · Impermeabilizada", medidas: "41altx50bocx35bas", material: "Fibrocemento", pintada: false, precio: 36000 },
  { articulo: "Salteña · Pintada", medidas: "41altx50bocx35bas", material: "Fibrocemento", pintada: true, precio: 39600 },
  { articulo: "Salteña · Natural / Cruda", medidas: "65altx50bocx25bas", material: "Fibrocemento", pintada: false, precio: 34700 },
  { articulo: "Salteña · Impermeabilizada", medidas: "65altx50bocx25bas", material: "Fibrocemento", pintada: false, precio: 57800 },
  { articulo: "Salteña · Pintada", medidas: "65altx50bocx25bas", material: "Fibrocemento", pintada: true, precio: 63500 },
  { articulo: "Salteña · Natural / Cruda", medidas: "50altx65bocx32bas", material: "Fibrocemento", pintada: false, precio: 53100 },
  { articulo: "Salteña · Impermeabilizada", medidas: "50altx65bocx32bas", material: "Fibrocemento", pintada: false, precio: 88400 },
  { articulo: "Salteña · Pintada", medidas: "50altx65bocx32bas", material: "Fibrocemento", pintada: true, precio: 97300 },
  { articulo: "Salteña · Natural / Cruda", medidas: "77altx65bocx32bas", material: "Fibrocemento", pintada: false, precio: 63600 },
  { articulo: "Salteña · Impermeabilizada", medidas: "77altx65bocx32bas", material: "Fibrocemento", pintada: false, precio: 106000 },
  { articulo: "Salteña · Pintada", medidas: "77altx65bocx32bas", material: "Fibrocemento", pintada: true, precio: 116600 },
  { articulo: "Copa · Natural / Cruda", medidas: "40altx33bocx16bas", material: "Fibrocemento", pintada: false, precio: 12400 },
  { articulo: "Copa · Impermeabilizada", medidas: "40altx33bocx16bas", material: "Fibrocemento", pintada: false, precio: 20600 },
  { articulo: "Copa · Pintada", medidas: "40altx33bocx16bas", material: "Fibrocemento", pintada: true, precio: 22600 },
  { articulo: "Copa · Natural / Cruda", medidas: "55altx45bocx28bas", material: "Fibrocemento", pintada: false, precio: 24700 },
  { articulo: "Copa · Impermeabilizada", medidas: "55altx45bocx28bas", material: "Fibrocemento", pintada: false, precio: 41200 },
  { articulo: "Copa · Pintada", medidas: "55altx45bocx28bas", material: "Fibrocemento", pintada: true, precio: 45300 },
  { articulo: "Copa · Natural / Cruda", medidas: "70altx50bocx28bas", material: "Fibrocemento", pintada: false, precio: 53700 },
  { articulo: "Copa · Impermeabilizada", medidas: "70altx50bocx28bas", material: "Fibrocemento", pintada: false, precio: 89500 },
  { articulo: "Copa · Pintada", medidas: "70altx50bocx28bas", material: "Fibrocemento", pintada: true, precio: 98500 },
  { articulo: "Bols · Natural / Cruda", medidas: "28altx55bocx27bas", material: "Fibrocemento", pintada: false, precio: 15800 },
  { articulo: "Bols · Impermeabilizada", medidas: "28altx55bocx27bas", material: "Fibrocemento", pintada: false, precio: 26300 },
  { articulo: "Bols · Pintada", medidas: "28altx55bocx27bas", material: "Fibrocemento", pintada: true, precio: 29000 },
  { articulo: "Bols · Natural / Cruda", medidas: "30altx80bocx33bas", material: "Fibrocemento", pintada: false, precio: 25300 },
  { articulo: "Bols · Impermeabilizada", medidas: "30altx80bocx33bas", material: "Fibrocemento", pintada: false, precio: 42200 },
  { articulo: "Bols · Pintada", medidas: "30altx80bocx33bas", material: "Fibrocemento", pintada: true, precio: 46400 },
  { articulo: "Cónica / Tradicional · Natural / Cruda", medidas: "30altx30bocx18bas", material: "Fibrocemento", pintada: false, precio: 9300 },
  { articulo: "Cónica / Tradicional · Impermeabilizada", medidas: "30altx30bocx18bas", material: "Fibrocemento", pintada: false, precio: 15400 },
  { articulo: "Cónica / Tradicional · Pintada", medidas: "30altx30bocx18bas", material: "Fibrocemento", pintada: true, precio: 17000 },
  { articulo: "Cónica / Tradicional · Natural / Cruda", medidas: "40altx40bocx25bas", material: "Fibrocemento", pintada: false, precio: 18400 },
  { articulo: "Cónica / Tradicional · Impermeabilizada", medidas: "40altx40bocx25bas", material: "Fibrocemento", pintada: false, precio: 30600 },
  { articulo: "Cónica / Tradicional · Pintada", medidas: "40altx40bocx25bas", material: "Fibrocemento", pintada: true, precio: 33700 },
  { articulo: "Cónica / Tradicional · Natural / Cruda", medidas: "50altx50bocx29bas", material: "Fibrocemento", pintada: false, precio: 20100 },
  { articulo: "Cónica / Tradicional · Impermeabilizada", medidas: "50altx50bocx29bas", material: "Fibrocemento", pintada: false, precio: 33500 },
  { articulo: "Cónica / Tradicional · Pintada", medidas: "50altx50bocx29bas", material: "Fibrocemento", pintada: true, precio: 36800 },
  { articulo: "Cónica / Tradicional · Natural / Cruda", medidas: "60altx60bocx36bas", material: "Fibrocemento", pintada: false, precio: 27800 },
  { articulo: "Cónica / Tradicional · Impermeabilizada", medidas: "60altx60bocx36bas", material: "Fibrocemento", pintada: false, precio: 46300 },
  { articulo: "Cónica / Tradicional · Pintada", medidas: "60altx60bocx36bas", material: "Fibrocemento", pintada: true, precio: 51000 },
  { articulo: "Cónica / Tradicional · Natural / Cruda", medidas: "70altx70bocx44bas", material: "Fibrocemento", pintada: false, precio: 49900 },
  { articulo: "Cónica / Tradicional · Impermeabilizada", medidas: "70altx70bocx44bas", material: "Fibrocemento", pintada: false, precio: 83100 },
  { articulo: "Cónica / Tradicional · Pintada", medidas: "70altx70bocx44bas", material: "Fibrocemento", pintada: true, precio: 91500 },
  { articulo: "Andina · Natural / Cruda", medidas: "35altx40bocx26bas", material: "Fibrocemento", pintada: false, precio: 16900 },
  { articulo: "Andina · Impermeabilizada", medidas: "35altx40bocx26bas", material: "Fibrocemento", pintada: false, precio: 28100 },
  { articulo: "Andina · Pintada", medidas: "35altx40bocx26bas", material: "Fibrocemento", pintada: true, precio: 30900 },
  { articulo: "Andina · Natural / Cruda", medidas: "43altx50bocx33bas", material: "Fibrocemento", pintada: false, precio: 23700 },
  { articulo: "Andina · Impermeabilizada", medidas: "43altx50bocx33bas", material: "Fibrocemento", pintada: false, precio: 39400 },
  { articulo: "Andina · Pintada", medidas: "43altx50bocx33bas", material: "Fibrocemento", pintada: true, precio: 43400 },
  { articulo: "Andina · Natural / Cruda", medidas: "55altx65bocx43bas", material: "Fibrocemento", pintada: false, precio: 42300 },
  { articulo: "Andina · Impermeabilizada", medidas: "55altx65bocx43bas", material: "Fibrocemento", pintada: false, precio: 70400 },
  { articulo: "Andina · Pintada", medidas: "55altx65bocx43bas", material: "Fibrocemento", pintada: true, precio: 77500 },
  { articulo: "Andina · Natural / Cruda", medidas: "69altx80bocx53bas", material: "Fibrocemento", pintada: false, precio: 112900 },
  { articulo: "Andina · Impermeabilizada", medidas: "69altx80bocx53bas", material: "Fibrocemento", pintada: false, precio: 188200 },
  { articulo: "Andina · Pintada", medidas: "69altx80bocx53bas", material: "Fibrocemento", pintada: true, precio: 207000 },
  { articulo: "Cono · Natural / Cruda", medidas: "60altx38bocx30bas", material: "Fibrocemento", pintada: false, precio: 17300 },
  { articulo: "Cono · Impermeabilizada", medidas: "60altx38bocx30bas", material: "Fibrocemento", pintada: false, precio: 28800 },
  { articulo: "Cono · Pintada", medidas: "60altx38bocx30bas", material: "Fibrocemento", pintada: true, precio: 31700 },
  { articulo: "Cono · Natural / Cruda", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: false, precio: 22200 },
  { articulo: "Cono · Impermeabilizada", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: false, precio: 37100 },
  { articulo: "Cono · Pintada", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: true, precio: 40800 },
  { articulo: "Cono · Natural / Cruda", medidas: "100altx45bocx30bas", material: "Fibrocemento", pintada: false, precio: 34600 },
  { articulo: "Cono · Impermeabilizada", medidas: "100altx45bocx30bas", material: "Fibrocemento", pintada: false, precio: 57700 },
  { articulo: "Cono · Pintada", medidas: "100altx45bocx30bas", material: "Fibrocemento", pintada: true, precio: 63400 },
  { articulo: "Cono Moderno · Natural / Cruda", medidas: "40altx31bocx22bas", material: "Fibrocemento", pintada: false, precio: 12400 },
  { articulo: "Cono Moderno · Impermeabilizada", medidas: "40altx31bocx22bas", material: "Fibrocemento", pintada: false, precio: 20700 },
  { articulo: "Cono Moderno · Pintada", medidas: "40altx31bocx22bas", material: "Fibrocemento", pintada: true, precio: 22800 },
  { articulo: "Cono Moderno · Natural / Cruda", medidas: "55altx36bocx24bas", material: "Fibrocemento", pintada: false, precio: 16100 },
  { articulo: "Cono Moderno · Impermeabilizada", medidas: "55altx36bocx24bas", material: "Fibrocemento", pintada: false, precio: 26800 },
  { articulo: "Cono Moderno · Pintada", medidas: "55altx36bocx24bas", material: "Fibrocemento", pintada: true, precio: 29500 },
  { articulo: "Cono Moderno · Natural / Cruda", medidas: "70altx46bocx24bas", material: "Fibrocemento", pintada: false, precio: 21600 },
  { articulo: "Cono Moderno · Impermeabilizada", medidas: "70altx46bocx24bas", material: "Fibrocemento", pintada: false, precio: 36000 },
  { articulo: "Cono Moderno · Pintada", medidas: "70altx46bocx24bas", material: "Fibrocemento", pintada: true, precio: 39600 },
  { articulo: "Cono Moderno · Natural / Cruda", medidas: "80altx46bocx28bas", material: "Fibrocemento", pintada: false, precio: 28400 },
  { articulo: "Cono Moderno · Impermeabilizada", medidas: "80altx46bocx28bas", material: "Fibrocemento", pintada: false, precio: 47300 },
  { articulo: "Cono Moderno · Pintada", medidas: "80altx46bocx28bas", material: "Fibrocemento", pintada: true, precio: 52000 },
  { articulo: "Esfera · Natural / Cruda", medidas: "20cm", material: "Fibrocemento", pintada: false, precio: 6900 },
  { articulo: "Esfera · Impermeabilizada", medidas: "20cm", material: "Fibrocemento", pintada: false, precio: 11500 },
  { articulo: "Esfera · Pintada", medidas: "20cm", material: "Fibrocemento", pintada: true, precio: 12700 },
  { articulo: "Esfera · Natural / Cruda", medidas: "28cm", material: "Fibrocemento", pintada: false, precio: 9700 },
  { articulo: "Esfera · Impermeabilizada", medidas: "28cm", material: "Fibrocemento", pintada: false, precio: 16200 },
  { articulo: "Esfera · Pintada", medidas: "28cm", material: "Fibrocemento", pintada: true, precio: 17800 },
  { articulo: "Esfera · Natural / Cruda", medidas: "40cm", material: "Fibrocemento", pintada: false, precio: 13800 },
  { articulo: "Esfera · Impermeabilizada", medidas: "40cm", material: "Fibrocemento", pintada: false, precio: 23100 },
  { articulo: "Esfera · Pintada", medidas: "40cm", material: "Fibrocemento", pintada: true, precio: 25400 },
  { articulo: "Esfera · Natural / Cruda", medidas: "50cm", material: "Fibrocemento", pintada: false, precio: 27700 },
  { articulo: "Esfera · Impermeabilizada", medidas: "50cm", material: "Fibrocemento", pintada: false, precio: 46200 },
  { articulo: "Esfera · Pintada", medidas: "50cm", material: "Fibrocemento", pintada: true, precio: 50800 },
  { articulo: "Maceta Esférica · Natural / Cruda", medidas: "20Ø", material: "Fibrocemento", pintada: false, precio: 6200 },
  { articulo: "Maceta Esférica · Impermeabilizada", medidas: "20Ø", material: "Fibrocemento", pintada: false, precio: 10300 },
  { articulo: "Maceta Esférica · Pintada", medidas: "20Ø", material: "Fibrocemento", pintada: true, precio: 11300 },
  { articulo: "Maceta Esférica · Natural / Cruda", medidas: "30Ø", material: "Fibrocemento", pintada: false, precio: 8700 },
  { articulo: "Maceta Esférica · Impermeabilizada", medidas: "30Ø", material: "Fibrocemento", pintada: false, precio: 14400 },
  { articulo: "Maceta Esférica · Pintada", medidas: "30Ø", material: "Fibrocemento", pintada: true, precio: 15900 },
  { articulo: "Maceta Esférica · Natural / Cruda", medidas: "40Ø", material: "Fibrocemento", pintada: false, precio: 12400 },
  { articulo: "Maceta Esférica · Impermeabilizada", medidas: "40Ø", material: "Fibrocemento", pintada: false, precio: 20600 },
  { articulo: "Maceta Esférica · Pintada", medidas: "40Ø", material: "Fibrocemento", pintada: true, precio: 22600 },
  { articulo: "Maceta Esférica · Natural / Cruda", medidas: "50Ø", material: "Fibrocemento", pintada: false, precio: 24700 },
  { articulo: "Maceta Esférica · Impermeabilizada", medidas: "50Ø", material: "Fibrocemento", pintada: false, precio: 41200 },
  { articulo: "Maceta Esférica · Pintada", medidas: "50Ø", material: "Fibrocemento", pintada: true, precio: 45300 },
  { articulo: "Paila · Natural / Cruda", medidas: "33cm", material: "Fibrocemento", pintada: false, precio: 5900 },
  { articulo: "Paila · Impermeabilizada", medidas: "33cm", material: "Fibrocemento", pintada: false, precio: 9900 },
  { articulo: "Paila · Pintada", medidas: "33cm", material: "Fibrocemento", pintada: true, precio: 10900 },
  { articulo: "Paila · Natural / Cruda", medidas: "48cm", material: "Fibrocemento", pintada: false, precio: 8900 },
  { articulo: "Paila · Impermeabilizada", medidas: "48cm", material: "Fibrocemento", pintada: false, precio: 14900 },
  { articulo: "Paila · Pintada", medidas: "48cm", material: "Fibrocemento", pintada: true, precio: 16400 },
  { articulo: "Paila · Natural / Cruda", medidas: "60cm", material: "Fibrocemento", pintada: false, precio: 11400 },
  { articulo: "Paila · Impermeabilizada", medidas: "60cm", material: "Fibrocemento", pintada: false, precio: 19000 },
  { articulo: "Paila · Pintada", medidas: "60cm", material: "Fibrocemento", pintada: true, precio: 20900 },
  { articulo: "Premium · Natural / Cruda", medidas: "20cmx22", material: "Fibrocemento", pintada: false, precio: 4800 },
  { articulo: "Premium · Impermeabilizada", medidas: "20cmx22", material: "Fibrocemento", pintada: false, precio: 7900 },
  { articulo: "Premium · Pintada", medidas: "20cmx22", material: "Fibrocemento", pintada: true, precio: 8700 },
  { articulo: "Premium · Natural / Cruda", medidas: "24cmx27", material: "Fibrocemento", pintada: false, precio: 7100 },
  { articulo: "Premium · Impermeabilizada", medidas: "24cmx27", material: "Fibrocemento", pintada: false, precio: 11900 },
  { articulo: "Premium · Pintada", medidas: "24cmx27", material: "Fibrocemento", pintada: true, precio: 13100 },
  { articulo: "Premium · Natural / Cruda", medidas: "30cmx35", material: "Fibrocemento", pintada: false, precio: 10900 },
  { articulo: "Premium · Impermeabilizada", medidas: "30cmx35", material: "Fibrocemento", pintada: false, precio: 18200 },
  { articulo: "Premium · Pintada", medidas: "30cmx35", material: "Fibrocemento", pintada: true, precio: 20000 },
  { articulo: "Sanjuanina · Natural / Cruda", medidas: "53altx36bocx30bas", material: "Fibrocemento", pintada: false, precio: 24700 },
  { articulo: "Sanjuanina · Impermeabilizada", medidas: "53altx36bocx30bas", material: "Fibrocemento", pintada: false, precio: 41200 },
  { articulo: "Sanjuanina · Pintada", medidas: "53altx36bocx30bas", material: "Fibrocemento", pintada: true, precio: 45300 },
  { articulo: "Sanjuanina · Natural / Cruda", medidas: "63altx39bocx33bas", material: "Fibrocemento", pintada: false, precio: 29600 },
  { articulo: "Sanjuanina · Impermeabilizada", medidas: "63altx39bocx33bas", material: "Fibrocemento", pintada: false, precio: 49400 },
  { articulo: "Sanjuanina · Pintada", medidas: "63altx39bocx33bas", material: "Fibrocemento", pintada: true, precio: 54400 },
  { articulo: "Tinaja · Natural / Cruda", medidas: "50cm", material: "Fibrocemento", pintada: false, precio: 22400 },
  { articulo: "Tinaja · Impermeabilizada", medidas: "50cm", material: "Fibrocemento", pintada: false, precio: 37300 },
  { articulo: "Tinaja · Pintada", medidas: "50cm", material: "Fibrocemento", pintada: true, precio: 41000 },
  { articulo: "Tinaja · Natural / Cruda", medidas: "60cm", material: "Fibrocemento", pintada: false, precio: 25200 },
  { articulo: "Tinaja · Impermeabilizada", medidas: "60cm", material: "Fibrocemento", pintada: false, precio: 41900 },
  { articulo: "Tinaja · Pintada", medidas: "60cm", material: "Fibrocemento", pintada: true, precio: 46100 },
  { articulo: "Tinaja · Natural / Cruda", medidas: "80cm", material: "Fibrocemento", pintada: false, precio: 76800 },
  { articulo: "Tinaja · Impermeabilizada", medidas: "80cm", material: "Fibrocemento", pintada: false, precio: 128100 },
  { articulo: "Tinaja · Pintada", medidas: "80cm", material: "Fibrocemento", pintada: true, precio: 140900 },
  { articulo: "Ánfora · Natural / Cruda", medidas: "75cm de alto", material: "Fibrocemento", pintada: false, precio: 41900 },
  { articulo: "Ánfora · Impermeabilizada", medidas: "75cm de alto", material: "Fibrocemento", pintada: false, precio: 69900 },
  { articulo: "Ánfora · Pintada", medidas: "75cm de alto", material: "Fibrocemento", pintada: true, precio: 76800 },
  { articulo: "Ánfora · Natural / Cruda", medidas: "90cm de alto", material: "Fibrocemento", pintada: false, precio: 60100 },
  { articulo: "Ánfora · Impermeabilizada", medidas: "90cm de alto", material: "Fibrocemento", pintada: false, precio: 100100 },
  { articulo: "Ánfora · Pintada", medidas: "90cm de alto", material: "Fibrocemento", pintada: true, precio: 110100 },
  { articulo: "Grecia · Natural / Cruda", medidas: "24hx32Øx15bas", material: "Fibrocemento", pintada: false, precio: 17700 },
  { articulo: "Grecia · Impermeabilizada", medidas: "24hx32Øx15bas", material: "Fibrocemento", pintada: false, precio: 29600 },
  { articulo: "Grecia · Pintada", medidas: "24hx32Øx15bas", material: "Fibrocemento", pintada: true, precio: 32500 },
  { articulo: "Grecia · Natural / Cruda", medidas: "36hx44Øx20bas", material: "Fibrocemento", pintada: false, precio: 19000 },
  { articulo: "Grecia · Impermeabilizada", medidas: "36hx44Øx20bas", material: "Fibrocemento", pintada: false, precio: 31700 },
  { articulo: "Grecia · Pintada", medidas: "36hx44Øx20bas", material: "Fibrocemento", pintada: true, precio: 34800 },
  { articulo: "Grecia · Natural / Cruda", medidas: "42hx55Øx25bas", material: "Fibrocemento", pintada: false, precio: 22600 },
  { articulo: "Grecia · Impermeabilizada", medidas: "42hx55Øx25bas", material: "Fibrocemento", pintada: false, precio: 37700 },
  { articulo: "Grecia · Pintada", medidas: "42hx55Øx25bas", material: "Fibrocemento", pintada: true, precio: 41500 },
  { articulo: "Cilindro · Natural / Cruda", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 7300 },
  { articulo: "Cilindro · Impermeabilizada", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 11900 },
  { articulo: "Cilindro · Pintada", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 13200 },
  { articulo: "Cilindro · Natural / Cruda", medidas: "45altx40bocx45bas", material: "Fibrocemento", pintada: false, precio: 15100 },
  { articulo: "Cilindro · Impermeabilizada", medidas: "45altx40bocx45bas", material: "Fibrocemento", pintada: false, precio: 24500 },
  { articulo: "Cilindro · Pintada", medidas: "45altx40bocx45bas", material: "Fibrocemento", pintada: true, precio: 27200 },
  { articulo: "Cilindro · Natural / Cruda", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: false, precio: 15100 },
  { articulo: "Cilindro · Impermeabilizada", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: false, precio: 24500 },
  { articulo: "Cilindro · Pintada", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: true, precio: 27200 },
  { articulo: "Cilindro · Natural / Cruda", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 15300 },
  { articulo: "Cilindro · Impermeabilizada", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 24700 },
  { articulo: "Cilindro · Pintada", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 27500 },
  { articulo: "Cilindro · Natural / Cruda", medidas: "52altx52bocx52bas", material: "Fibrocemento", pintada: false, precio: 18300 },
  { articulo: "Cilindro · Impermeabilizada", medidas: "52altx52bocx52bas", material: "Fibrocemento", pintada: false, precio: 29700 },
  { articulo: "Cilindro · Pintada", medidas: "52altx52bocx52bas", material: "Fibrocemento", pintada: true, precio: 33000 },
  { articulo: "Cilindro · Natural / Cruda", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: false, precio: 34300 },
  { articulo: "Cilindro · Impermeabilizada", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: false, precio: 55600 },
  { articulo: "Cilindro · Pintada", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: true, precio: 61800 },
  { articulo: "Cubo · Natural / Cruda", medidas: "15altx15bocx15bas", material: "Fibrocemento", pintada: false, precio: 3400 },
  { articulo: "Cubo · Impermeabilizada", medidas: "15altx15bocx15bas", material: "Fibrocemento", pintada: false, precio: 5600 },
  { articulo: "Cubo · Pintada", medidas: "15altx15bocx15bas", material: "Fibrocemento", pintada: true, precio: 6200 },
  { articulo: "Cubo · Natural / Cruda", medidas: "20altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 4300 },
  { articulo: "Cubo · Impermeabilizada", medidas: "20altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 6900 },
  { articulo: "Cubo · Pintada", medidas: "20altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 7700 },
  { articulo: "Cubo · Natural / Cruda", medidas: "25altx25bocx25bas", material: "Fibrocemento", pintada: false, precio: 6300 },
  { articulo: "Cubo · Impermeabilizada", medidas: "25altx25bocx25bas", material: "Fibrocemento", pintada: false, precio: 10200 },
  { articulo: "Cubo · Pintada", medidas: "25altx25bocx25bas", material: "Fibrocemento", pintada: true, precio: 11300 },
  { articulo: "Cubo · Natural / Cruda", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 8600 },
  { articulo: "Cubo · Impermeabilizada", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 13900 },
  { articulo: "Cubo · Pintada", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 15400 },
  { articulo: "Cubo · Natural / Cruda", medidas: "35altx35bocx35bas", material: "Fibrocemento", pintada: false, precio: 10900 },
  { articulo: "Cubo · Impermeabilizada", medidas: "35altx35bocx35bas", material: "Fibrocemento", pintada: false, precio: 17600 },
  { articulo: "Cubo · Pintada", medidas: "35altx35bocx35bas", material: "Fibrocemento", pintada: true, precio: 19600 },
  { articulo: "Cubo · Natural / Cruda", medidas: "40altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 12900 },
  { articulo: "Cubo · Impermeabilizada", medidas: "40altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 20900 },
  { articulo: "Cubo · Pintada", medidas: "40altx40bocx40bas", material: "Fibrocemento", pintada: true, precio: 23200 },
  { articulo: "Cubo · Natural / Cruda", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: false, precio: 17200 },
  { articulo: "Cubo · Impermeabilizada", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: false, precio: 27800 },
  { articulo: "Cubo · Pintada", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: true, precio: 30900 },
  { articulo: "Cubo · Natural / Cruda", medidas: "50altx50bocx50bas", material: "Fibrocemento", pintada: false, precio: 22900 },
  { articulo: "Cubo · Impermeabilizada", medidas: "50altx50bocx50bas", material: "Fibrocemento", pintada: false, precio: 37100 },
  { articulo: "Cubo · Pintada", medidas: "50altx50bocx50bas", material: "Fibrocemento", pintada: true, precio: 41200 },
  { articulo: "Cubo · Natural / Cruda", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: false, precio: 41400 },
  { articulo: "Cubo · Impermeabilizada", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: false, precio: 67100 },
  { articulo: "Cubo · Pintada", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: true, precio: 74500 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "40lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 6300 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "40lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 10200 },
  { articulo: "Jardinera · Pintada", medidas: "40lrgx13anchx15alt", material: "Fibrocemento", pintada: true, precio: 11300 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "40lrgx20anchx10alt", material: "Fibrocemento", pintada: false, precio: 5400 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "40lrgx20anchx10alt", material: "Fibrocemento", pintada: false, precio: 8800 },
  { articulo: "Jardinera · Pintada", medidas: "40lrgx20anchx10alt", material: "Fibrocemento", pintada: true, precio: 9800 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "40lrgx20anchx20alt", material: "Fibrocemento", pintada: false, precio: 6600 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "40lrgx20anchx20alt", material: "Fibrocemento", pintada: false, precio: 10700 },
  { articulo: "Jardinera · Pintada", medidas: "40lrgx20anchx20alt", material: "Fibrocemento", pintada: true, precio: 11900 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "50lrgx20anchx20alt", material: "Fibrocemento", pintada: false, precio: 7800 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "50lrgx20anchx20alt", material: "Fibrocemento", pintada: false, precio: 12600 },
  { articulo: "Jardinera · Pintada", medidas: "50lrgx20anchx20alt", material: "Fibrocemento", pintada: true, precio: 14000 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "60lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 7400 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "60lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 12100 },
  { articulo: "Jardinera · Pintada", medidas: "60lrgx13anchx15alt", material: "Fibrocemento", pintada: true, precio: 13400 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "60lrgx20anchx10alt", material: "Fibrocemento", pintada: false, precio: 6400 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "60lrgx20anchx10alt", material: "Fibrocemento", pintada: false, precio: 10400 },
  { articulo: "Jardinera · Pintada", medidas: "60lrgx20anchx10alt", material: "Fibrocemento", pintada: true, precio: 11500 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "60lrgx20anchx30alt", material: "Fibrocemento", pintada: false, precio: 12400 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "60lrgx20anchx30alt", material: "Fibrocemento", pintada: false, precio: 20100 },
  { articulo: "Jardinera · Pintada", medidas: "60lrgx20anchx30alt", material: "Fibrocemento", pintada: true, precio: 22400 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "60lrgx20anchx40alt", material: "Fibrocemento", pintada: false, precio: 13200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "60lrgx20anchx40alt", material: "Fibrocemento", pintada: false, precio: 21400 },
  { articulo: "Jardinera · Pintada", medidas: "60lrgx20anchx40alt", material: "Fibrocemento", pintada: true, precio: 23800 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "60lrgx22anchx20alt", material: "Fibrocemento", pintada: false, precio: 10900 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "60lrgx22anchx20alt", material: "Fibrocemento", pintada: false, precio: 17600 },
  { articulo: "Jardinera · Pintada", medidas: "60lrgx22anchx20alt", material: "Fibrocemento", pintada: true, precio: 19600 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "60lrgx30anchx30alt", material: "Fibrocemento", pintada: false, precio: 14000 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "60lrgx30anchx30alt", material: "Fibrocemento", pintada: false, precio: 22700 },
  { articulo: "Jardinera · Pintada", medidas: "60lrgx30anchx30alt", material: "Fibrocemento", pintada: true, precio: 25200 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "60lrgx30anchx35alt", material: "Fibrocemento", pintada: false, precio: 15200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "60lrgx30anchx35alt", material: "Fibrocemento", pintada: false, precio: 24600 },
  { articulo: "Jardinera · Pintada", medidas: "60lrgx30anchx35alt", material: "Fibrocemento", pintada: true, precio: 27300 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "80lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 9200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "80lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 14800 },
  { articulo: "Jardinera · Pintada", medidas: "80lrgx13anchx15alt", material: "Fibrocemento", pintada: true, precio: 16500 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "80lrgx20anchx30alt", material: "Fibrocemento", pintada: false, precio: 15200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "80lrgx20anchx30alt", material: "Fibrocemento", pintada: false, precio: 24600 },
  { articulo: "Jardinera · Pintada", medidas: "80lrgx20anchx30alt", material: "Fibrocemento", pintada: true, precio: 27300 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "80lrgx20anchx40alt", material: "Fibrocemento", pintada: false, precio: 20000 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "80lrgx20anchx40alt", material: "Fibrocemento", pintada: false, precio: 32400 },
  { articulo: "Jardinera · Pintada", medidas: "80lrgx20anchx40alt", material: "Fibrocemento", pintada: true, precio: 36000 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "80lrgx22anchx20alt", material: "Fibrocemento", pintada: false, precio: 13200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "80lrgx22anchx20alt", material: "Fibrocemento", pintada: false, precio: 21300 },
  { articulo: "Jardinera · Pintada", medidas: "80lrgx22anchx20alt", material: "Fibrocemento", pintada: true, precio: 23700 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "80lrgx30anchx30alt", material: "Fibrocemento", pintada: false, precio: 20000 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "80lrgx30anchx30alt", material: "Fibrocemento", pintada: false, precio: 32400 },
  { articulo: "Jardinera · Pintada", medidas: "80lrgx30anchx30alt", material: "Fibrocemento", pintada: true, precio: 36000 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "80lrgx30anchx35alt", material: "Fibrocemento", pintada: false, precio: 20100 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "80lrgx30anchx35alt", material: "Fibrocemento", pintada: false, precio: 32500 },
  { articulo: "Jardinera · Pintada", medidas: "80lrgx30anchx35alt", material: "Fibrocemento", pintada: true, precio: 36100 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "80lrgx35anchx40alt", material: "Fibrocemento", pintada: false, precio: 22900 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "80lrgx35anchx40alt", material: "Fibrocemento", pintada: false, precio: 37100 },
  { articulo: "Jardinera · Pintada", medidas: "80lrgx35anchx40alt", material: "Fibrocemento", pintada: true, precio: 41200 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 12900 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx13anchx15alt", material: "Fibrocemento", pintada: false, precio: 20900 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx13anchx15alt", material: "Fibrocemento", pintada: true, precio: 23200 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx20anchx30alt", material: "Fibrocemento", pintada: false, precio: 18600 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx20anchx30alt", material: "Fibrocemento", pintada: false, precio: 30100 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx20anchx30alt", material: "Fibrocemento", pintada: true, precio: 33500 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx20anchx40alt", material: "Fibrocemento", pintada: false, precio: 22900 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx20anchx40alt", material: "Fibrocemento", pintada: false, precio: 37100 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx20anchx40alt", material: "Fibrocemento", pintada: true, precio: 41200 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx22anchx20alt", material: "Fibrocemento", pintada: false, precio: 17200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx22anchx20alt", material: "Fibrocemento", pintada: false, precio: 27800 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx22anchx20alt", material: "Fibrocemento", pintada: true, precio: 30900 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx30anchx30alt", material: "Fibrocemento", pintada: false, precio: 22900 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx30anchx30alt", material: "Fibrocemento", pintada: false, precio: 37100 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx30anchx30alt", material: "Fibrocemento", pintada: true, precio: 41200 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx30anchx35alt", material: "Fibrocemento", pintada: false, precio: 25700 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx30anchx35alt", material: "Fibrocemento", pintada: false, precio: 41700 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx30anchx35alt", material: "Fibrocemento", pintada: true, precio: 46300 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx35anchx40alt", material: "Fibrocemento", pintada: false, precio: 31500 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx35anchx40alt", material: "Fibrocemento", pintada: false, precio: 51000 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx35anchx40alt", material: "Fibrocemento", pintada: true, precio: 56600 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "100lrgx40anchx40alt", material: "Fibrocemento", pintada: false, precio: 34300 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "100lrgx40anchx40alt", material: "Fibrocemento", pintada: false, precio: 55600 },
  { articulo: "Jardinera · Pintada", medidas: "100lrgx40anchx40alt", material: "Fibrocemento", pintada: true, precio: 61800 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "115lrgx50anchx45alt", material: "Fibrocemento", pintada: false, precio: 69900 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "115lrgx50anchx45alt", material: "Fibrocemento", pintada: false, precio: 113200 },
  { articulo: "Jardinera · Pintada", medidas: "115lrgx50anchx45alt", material: "Fibrocemento", pintada: true, precio: 125800 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "125lrgx50anchx45alt", material: "Fibrocemento", pintada: false, precio: 71200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "125lrgx50anchx45alt", material: "Fibrocemento", pintada: false, precio: 115300 },
  { articulo: "Jardinera · Pintada", medidas: "125lrgx50anchx45alt", material: "Fibrocemento", pintada: true, precio: 128100 },
  { articulo: "Jardinera · Natural / Cruda", medidas: "135lrgx50anchx45alt", material: "Fibrocemento", pintada: false, precio: 80200 },
  { articulo: "Jardinera · Impermeabilizada", medidas: "135lrgx50anchx45alt", material: "Fibrocemento", pintada: false, precio: 129900 },
  { articulo: "Jardinera · Pintada", medidas: "135lrgx50anchx45alt", material: "Fibrocemento", pintada: true, precio: 144400 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "50altx25bocx18bas", material: "Fibrocemento", pintada: false, precio: 9700 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "50altx25bocx18bas", material: "Fibrocemento", pintada: false, precio: 15700 },
  { articulo: "Piramidal · Pintada", medidas: "50altx25bocx18bas", material: "Fibrocemento", pintada: true, precio: 17500 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "45altx35bocx22bas", material: "Fibrocemento", pintada: false, precio: 11000 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "45altx35bocx22bas", material: "Fibrocemento", pintada: false, precio: 17800 },
  { articulo: "Piramidal · Pintada", medidas: "45altx35bocx22bas", material: "Fibrocemento", pintada: true, precio: 19800 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "45altx45bocx30bas", material: "Fibrocemento", pintada: false, precio: 12300 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "45altx45bocx30bas", material: "Fibrocemento", pintada: false, precio: 19900 },
  { articulo: "Piramidal · Pintada", medidas: "45altx45bocx30bas", material: "Fibrocemento", pintada: true, precio: 22100 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "50altx40bocx30bas", material: "Fibrocemento", pintada: false, precio: 12300 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "50altx40bocx30bas", material: "Fibrocemento", pintada: false, precio: 19900 },
  { articulo: "Piramidal · Pintada", medidas: "50altx40bocx30bas", material: "Fibrocemento", pintada: true, precio: 22100 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "60altx30bocx22bas", material: "Fibrocemento", pintada: false, precio: 12300 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "60altx30bocx22bas", material: "Fibrocemento", pintada: false, precio: 19900 },
  { articulo: "Piramidal · Pintada", medidas: "60altx30bocx22bas", material: "Fibrocemento", pintada: true, precio: 22100 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "60altx35bocx25bas", material: "Fibrocemento", pintada: false, precio: 12900 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "60altx35bocx25bas", material: "Fibrocemento", pintada: false, precio: 21000 },
  { articulo: "Piramidal · Pintada", medidas: "60altx35bocx25bas", material: "Fibrocemento", pintada: true, precio: 23300 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "70altx30bocx20bas", material: "Fibrocemento", pintada: false, precio: 12900 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "70altx30bocx20bas", material: "Fibrocemento", pintada: false, precio: 21000 },
  { articulo: "Piramidal · Pintada", medidas: "70altx30bocx20bas", material: "Fibrocemento", pintada: true, precio: 23300 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "70altx35bocx25bas", material: "Fibrocemento", pintada: false, precio: 17500 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "70altx35bocx25bas", material: "Fibrocemento", pintada: false, precio: 28300 },
  { articulo: "Piramidal · Pintada", medidas: "70altx35bocx25bas", material: "Fibrocemento", pintada: true, precio: 31400 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "80altx30bocx20bas", material: "Fibrocemento", pintada: false, precio: 17500 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "80altx30bocx20bas", material: "Fibrocemento", pintada: false, precio: 28300 },
  { articulo: "Piramidal · Pintada", medidas: "80altx30bocx20bas", material: "Fibrocemento", pintada: true, precio: 31400 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "80altx35bocx25bas", material: "Fibrocemento", pintada: false, precio: 20700 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "80altx35bocx25bas", material: "Fibrocemento", pintada: false, precio: 33500 },
  { articulo: "Piramidal · Pintada", medidas: "80altx35bocx25bas", material: "Fibrocemento", pintada: true, precio: 37300 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: false, precio: 23300 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: false, precio: 37700 },
  { articulo: "Piramidal · Pintada", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: true, precio: 41900 },
  { articulo: "Piramidal · Natural / Cruda", medidas: "80altx50bocx30bas", material: "Fibrocemento", pintada: false, precio: 34900 },
  { articulo: "Piramidal · Impermeabilizada", medidas: "80altx50bocx30bas", material: "Fibrocemento", pintada: false, precio: 56600 },
  { articulo: "Piramidal · Pintada", medidas: "80altx50bocx30bas", material: "Fibrocemento", pintada: true, precio: 62900 },
  { articulo: "Prisma · Natural / Cruda", medidas: "30altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 4500 },
  { articulo: "Prisma · Impermeabilizada", medidas: "30altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 7200 },
  { articulo: "Prisma · Pintada", medidas: "30altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 8000 },
  { articulo: "Prisma · Natural / Cruda", medidas: "40altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 5400 },
  { articulo: "Prisma · Impermeabilizada", medidas: "40altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 8700 },
  { articulo: "Prisma · Pintada", medidas: "40altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 9600 },
  { articulo: "Prisma · Natural / Cruda", medidas: "40altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 8200 },
  { articulo: "Prisma · Impermeabilizada", medidas: "40altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 13300 },
  { articulo: "Prisma · Pintada", medidas: "40altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 14800 },
  { articulo: "Prisma · Natural / Cruda", medidas: "50altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 7300 },
  { articulo: "Prisma · Impermeabilizada", medidas: "50altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 11900 },
  { articulo: "Prisma · Pintada", medidas: "50altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 13200 },
  { articulo: "Prisma · Natural / Cruda", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 12800 },
  { articulo: "Prisma · Impermeabilizada", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 20700 },
  { articulo: "Prisma · Pintada", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 23100 },
  { articulo: "Prisma · Natural / Cruda", medidas: "50altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 16000 },
  { articulo: "Prisma · Impermeabilizada", medidas: "50altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 25900 },
  { articulo: "Prisma · Pintada", medidas: "50altx40bocx40bas", material: "Fibrocemento", pintada: true, precio: 28800 },
  { articulo: "Prisma · Natural / Cruda", medidas: "60altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 7800 },
  { articulo: "Prisma · Impermeabilizada", medidas: "60altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 12600 },
  { articulo: "Prisma · Pintada", medidas: "60altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 14000 },
  { articulo: "Prisma · Natural / Cruda", medidas: "60altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 14600 },
  { articulo: "Prisma · Impermeabilizada", medidas: "60altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 23700 },
  { articulo: "Prisma · Pintada", medidas: "60altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 26300 },
  { articulo: "Prisma · Natural / Cruda", medidas: "60altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 17400 },
  { articulo: "Prisma · Impermeabilizada", medidas: "60altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 28200 },
  { articulo: "Prisma · Pintada", medidas: "60altx40bocx40bas", material: "Fibrocemento", pintada: true, precio: 31300 },
  { articulo: "Prisma · Natural / Cruda", medidas: "80altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 11000 },
  { articulo: "Prisma · Impermeabilizada", medidas: "80altx20bocx20bas", material: "Fibrocemento", pintada: false, precio: 17800 },
  { articulo: "Prisma · Pintada", medidas: "80altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 19800 },
  { articulo: "Prisma · Natural / Cruda", medidas: "80altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 16500 },
  { articulo: "Prisma · Impermeabilizada", medidas: "80altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 26700 },
  { articulo: "Prisma · Pintada", medidas: "80altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 29600 },
  { articulo: "Prisma · Natural / Cruda", medidas: "80altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 31900 },
  { articulo: "Prisma · Impermeabilizada", medidas: "80altx40bocx40bas", material: "Fibrocemento", pintada: false, precio: 51700 },
  { articulo: "Prisma · Pintada", medidas: "80altx40bocx40bas", material: "Fibrocemento", pintada: true, precio: 57400 },
  { articulo: "Plato · Natural / Cruda", medidas: "20cm", material: "Fibrocemento", pintada: false, precio: 2100 },
  { articulo: "Plato · Pintada", medidas: "20cm", material: "Fibrocemento", pintada: true, precio: 3700 },
  { articulo: "Plato · Natural / Cruda", medidas: "30cm", material: "Fibrocemento", pintada: false, precio: 3400 },
  { articulo: "Plato · Pintada", medidas: "30cm", material: "Fibrocemento", pintada: true, precio: 6200 },
  { articulo: "Plato · Natural / Cruda", medidas: "40cm", material: "Fibrocemento", pintada: false, precio: 5400 },
  { articulo: "Plato · Pintada", medidas: "40cm", material: "Fibrocemento", pintada: true, precio: 9800 },
  { articulo: "Plato · Natural / Cruda", medidas: "45cm", material: "Fibrocemento", pintada: false, precio: 7500 },
  { articulo: "Plato · Pintada", medidas: "45cm", material: "Fibrocemento", pintada: true, precio: 13500 },
  { articulo: "Plato · Natural / Cruda", medidas: "50cm", material: "Fibrocemento", pintada: false, precio: 9200 },
  { articulo: "Plato · Pintada", medidas: "50cm", material: "Fibrocemento", pintada: true, precio: 16500 },
  { articulo: "Buda (cabeza) · Natural / Cruda", medidas: "45cmx30cm", material: "Fibrocemento", pintada: false, precio: 25200 },
];
