window.LYL_MIN = [
  // BARRO — BLUM
  { articulo: "Frutillera", medidas: "60", material: "Barro", pintada: false, precio: 174920 },
  { articulo: "Mac. Comun", medidas: "Nº 16 PINTADA", material: "Barro", pintada: true, precio: 6400 },
  { articulo: "Mac. Comun", medidas: "Nº 18 PINTADA", material: "Barro", pintada: true, precio: 8750 },
  { articulo: "Porteña", medidas: "Nº20", material: "Barro", pintada: false, precio: 4750 },
  { articulo: "Porteña", medidas: "Nº45", material: "Barro", pintada: false, precio: 49510 },
  { articulo: "Cilindro", medidas: "N26 GRAFITO", material: "Barro", pintada: true, precio: 19030 },
  { articulo: "Cilindro", medidas: "N22 GRAFITO", material: "Barro", pintada: true, precio: 12970 },
  { articulo: "Cilindro", medidas: "N18 GRAFITO", material: "Barro", pintada: true, precio: 8380 },
  { articulo: "Cilindro", medidas: "N14 GRAFITO", material: "Barro", pintada: true, precio: 4640 },
  { articulo: "Cilindro", medidas: "N12 GRAFITO", material: "Barro", pintada: true, precio: 1960 },
  { articulo: "Bomba", medidas: "N23 GRAFITO", material: "Barro", pintada: true, precio: 14390 },
  { articulo: "Mac Premium", medidas: "N22 GRAFITO", material: "Barro", pintada: true, precio: 6900 },
  { articulo: "Cilindro", medidas: "N18 ESMALTADO", material: "Barro", pintada: true, precio: 12980 },
  { articulo: "Mac. Comun", medidas: "N14 PINTADA", material: "Barro", pintada: true, precio: 5400 },
  { articulo: "Cilindro Esmaltado", medidas: "N12", material: "Barro", pintada: true, precio: 4540 },
  { articulo: "Cilindro Esmaltado", medidas: "N14", material: "Barro", pintada: true, precio: 8770 },
  { articulo: "Mac Premium Esmaltada", medidas: "N22", material: "Barro", pintada: true, precio: 13920 },
  { articulo: "Icono", medidas: "N12", material: "Barro", pintada: false, precio: 1770 },
  { articulo: "Icono", medidas: "N14", material: "Barro", pintada: false, precio: 1860 },
  { articulo: "Icono", medidas: "N16", material: "Barro", pintada: false, precio: 2780 },
  { articulo: "Icono", medidas: "N18", material: "Barro", pintada: false, precio: 3370 },
  { articulo: "Icono", medidas: "N20", material: "Barro", pintada: false, precio: 4130 },
  { articulo: "Cilindro Esmaltado", medidas: "N22", material: "Barro", pintada: true, precio: 25850 },
  { articulo: "Americana", medidas: "Nº23", material: "Barro", pintada: false, precio: 8380 },
  { articulo: "Americana", medidas: "Nº29", material: "Barro", pintada: false, precio: 15550 },
  { articulo: "Americana", medidas: "Nº36", material: "Barro", pintada: false, precio: 25140 },
  { articulo: "Balconera", medidas: "Nº45", material: "Barro", pintada: false, precio: 17000 },
  { articulo: "Bols Colgante", medidas: "N24", material: "Barro", pintada: false, precio: 7010 },
  { articulo: "Bols", medidas: "Nº13", material: "Barro", pintada: false, precio: 2940 },
  { articulo: "Bols", medidas: "Nº17", material: "Barro", pintada: false, precio: 4560 },
  { articulo: "Bols", medidas: "Nº21", material: "Barro", pintada: false, precio: 7210 },
  { articulo: "Bols", medidas: "Nº25", material: "Barro", pintada: false, precio: 9850 },
  { articulo: "Bomba", medidas: "Nº08", material: "Barro", pintada: false, precio: 3420 },
  { articulo: "Bomba", medidas: "Nº14", material: "Barro", pintada: false, precio: 6790 },
  { articulo: "Bomba", medidas: "Nº16", material: "Barro", pintada: false, precio: 8450 },
  { articulo: "Bomba", medidas: "Nº19", material: "Barro", pintada: false, precio: 10790 },
  { articulo: "Bomba", medidas: "Nº23", material: "Barro", pintada: false, precio: 16620 },
  { articulo: "Bomba", medidas: "Nº35", material: "Barro", pintada: false, precio: 40580 },
  { articulo: "Bomba", medidas: "Nº40", material: "Barro", pintada: false, precio: 60250 },
  { articulo: "Bomba", medidas: "Nº50", material: "Barro", pintada: false, precio: 91290 },
  { articulo: "Cilindro c/Borde", medidas: "Nº15", material: "Barro", pintada: false, precio: 3860 },
  { articulo: "Cilindro c/Borde", medidas: "Nº19", material: "Barro", pintada: false, precio: 5740 },
  { articulo: "Cilindro c/Borde", medidas: "Nº24", material: "Barro", pintada: false, precio: 9240 },
  { articulo: "Cilindro c/Borde", medidas: "Nº30", material: "Barro", pintada: false, precio: 19490 },
  { articulo: "Cilindro c/Borde", medidas: "Nº38", material: "Barro", pintada: false, precio: 34820 },
  { articulo: "Cilindro c/Borde", medidas: "Nº48", material: "Barro", pintada: false, precio: 79250 },
  { articulo: "Cilindro", medidas: "Nº12", material: "Barro", pintada: false, precio: 2260 },
  { articulo: "Cilindro", medidas: "Nº14", material: "Barro", pintada: false, precio: 5360 },
  { articulo: "Cilindro", medidas: "Nº18", material: "Barro", pintada: false, precio: 9680 },
  { articulo: "Cilindro", medidas: "Nº22", material: "Barro", pintada: false, precio: 14970 },
  { articulo: "Cilindro", medidas: "Nº26", material: "Barro", pintada: false, precio: 21960 },
  { articulo: "Cilindro", medidas: "Nº30", material: "Barro", pintada: false, precio: 32320 },
  { articulo: "Colgadera", medidas: "Nº25", material: "Barro", pintada: false, precio: 10390 },
  { articulo: "Colgadera", medidas: "Nº30", material: "Barro", pintada: false, precio: 18120 },
  { articulo: "Cono", medidas: "31", material: "Barro", pintada: false, precio: 10280 },
  { articulo: "Cono", medidas: "40", material: "Barro", pintada: false, precio: 20390 },
  { articulo: "Cono", medidas: "48", material: "Barro", pintada: false, precio: 31210 },
  { articulo: "Cono", medidas: "55 CM", material: "Barro", pintada: false, precio: 52730 },
  { articulo: "Festoneada", medidas: "Nº08", material: "Barro", pintada: false, precio: 3360 },
  { articulo: "Festoneada", medidas: "Nº10", material: "Barro", pintada: false, precio: 4420 },
  { articulo: "Festoneada", medidas: "Nº16", material: "Barro", pintada: false, precio: 8210 },
  { articulo: "Festoneada", medidas: "Nº19", material: "Barro", pintada: false, precio: 11330 },
  { articulo: "Festoneada", medidas: "Nº24", material: "Barro", pintada: false, precio: 13020 },
  { articulo: "Festoneada", medidas: "Nº30", material: "Barro", pintada: false, precio: 31420 },
  { articulo: "Festoneada", medidas: "Nº45", material: "Barro", pintada: false, precio: 92230 },
  { articulo: "Festoneada", medidas: "Nº58", material: "Barro", pintada: false, precio: 138360 },
  { articulo: "Frutillera", medidas: "40", material: "Barro", pintada: false, precio: 87460 },
  { articulo: "Italiana", medidas: "Nº14", material: "Barro", pintada: false, precio: 2630 },
  { articulo: "Italiana", medidas: "Nº16", material: "Barro", pintada: false, precio: 3110 },
  { articulo: "Italiana", medidas: "Nº18", material: "Barro", pintada: false, precio: 4240 },
  { articulo: "Italiana", medidas: "Nº20", material: "Barro", pintada: false, precio: 5610 },
  { articulo: "Italiana", medidas: "Nº22", material: "Barro", pintada: false, precio: 7870 },
  { articulo: "Italiana", medidas: "Nº24", material: "Barro", pintada: false, precio: 10210 },
  { articulo: "Italiana", medidas: "Nº26", material: "Barro", pintada: false, precio: 13510 },
  { articulo: "Italiana", medidas: "Nº30", material: "Barro", pintada: false, precio: 17030 },
  { articulo: "Italiana", medidas: "Nº35", material: "Barro", pintada: false, precio: 24760 },
  { articulo: "Italiana", medidas: "Nº40", material: "Barro", pintada: false, precio: 32140 },
  { articulo: "Italiana", medidas: "Nº48", material: "Barro", pintada: false, precio: 53540 },
  { articulo: "Italiana", medidas: "Nº52", material: "Barro", pintada: false, precio: 77780 },
  { articulo: "Jard. C.Roma", medidas: "Nº31", material: "Barro", pintada: false, precio: 14630 },
  { articulo: "Jard. C.Roma", medidas: "Nº52", material: "Barro", pintada: false, precio: 37680 },
  { articulo: "Jardinera", medidas: "Nº30", material: "Barro", pintada: false, precio: 13330 },
  { articulo: "Jardinera", medidas: "Nº40", material: "Barro", pintada: false, precio: 24380 },
  { articulo: "Jardinera", medidas: "Nº50", material: "Barro", pintada: false, precio: 35170 },
  { articulo: "Lebrillo", medidas: "Nº22", material: "Barro", pintada: false, precio: 6920 },
  { articulo: "Lebrillo", medidas: "Nº26", material: "Barro", pintada: false, precio: 9740 },
  { articulo: "Lebrillo", medidas: "Nº30", material: "Barro", pintada: false, precio: 13380 },
  { articulo: "Lebrillo", medidas: "Nº34", material: "Barro", pintada: false, precio: 16710 },
  { articulo: "Lebrillo", medidas: "Nº38", material: "Barro", pintada: false, precio: 20550 },
  { articulo: "Lebrillo", medidas: "Nº45", material: "Barro", pintada: false, precio: 33530 },
  { articulo: "Lebrillo", medidas: "Nº52", material: "Barro", pintada: false, precio: 49910 },
  { articulo: "Mac. Comun", medidas: "Nº 04", material: "Barro", pintada: false, precio: 1080 },
  { articulo: "Mac. Comun", medidas: "Nº 05", material: "Barro", pintada: false, precio: 1100 },
  { articulo: "Mac. Comun", medidas: "Nº 07", material: "Barro", pintada: false, precio: 1390 },
  { articulo: "Mac. Comun", medidas: "Nº 08", material: "Barro", pintada: false, precio: 1600 },
  { articulo: "Mac. Comun", medidas: "Nº 10", material: "Barro", pintada: false, precio: 1650 },
  { articulo: "Mac. Comun", medidas: "Nº 12", material: "Barro", pintada: false, precio: 1850 },
  { articulo: "Mac. Comun", medidas: "Nº 14", material: "Barro", pintada: false, precio: 2200 },
  { articulo: "Mac. Comun", medidas: "Nº 16", material: "Barro", pintada: false, precio: 2890 },
  { articulo: "Mac. Comun", medidas: "Nº 18", material: "Barro", pintada: false, precio: 4020 },
  { articulo: "Mac. Comun", medidas: "Nº 20", material: "Barro", pintada: false, precio: 4960 },
  { articulo: "Mac. Comun", medidas: "Nº 22", material: "Barro", pintada: false, precio: 7970 },
  { articulo: "Mac. Comun", medidas: "Nº 24", material: "Barro", pintada: false, precio: 9260 },
  { articulo: "Mac. Comun", medidas: "Nº 26", material: "Barro", pintada: false, precio: 11460 },
  { articulo: "Mac. Comun", medidas: "Nº 28", material: "Barro", pintada: false, precio: 13120 },
  { articulo: "Mac. Comun", medidas: "Nº 30", material: "Barro", pintada: false, precio: 15530 },
  { articulo: "Mac. Comun", medidas: "Nº 35", material: "Barro", pintada: false, precio: 20390 },
  { articulo: "Mac. Comun", medidas: "Nº 40", material: "Barro", pintada: false, precio: 32010 },
  { articulo: "Mac. Comun", medidas: "Nº 48", material: "Barro", pintada: false, precio: 48850 },
  { articulo: "Mac. Comun", medidas: "Nº 52", material: "Barro", pintada: false, precio: 76350 },
  { articulo: "Agustiniana", medidas: "Nº20", material: "Barro", pintada: false, precio: 10260 },
  { articulo: "Agustiniana", medidas: "Nº27", material: "Barro", pintada: false, precio: 23050 },
  { articulo: "Agustiniana", medidas: "Nº34", material: "Barro", pintada: false, precio: 44870 },
  { articulo: "Agustiniana", medidas: "Nº40", material: "Barro", pintada: false, precio: 71350 },
  { articulo: "Agustiniana", medidas: "Nº60", material: "Barro", pintada: false, precio: 136680 },
  { articulo: "Nido De Paloma", medidas: "Nº24", material: "Barro", pintada: false, precio: 9150 },
  { articulo: "Paila", medidas: "Nº35", material: "Barro", pintada: false, precio: 15670 },
  { articulo: "Paila", medidas: "Nº48", material: "Barro", pintada: false, precio: 33680 },
  { articulo: "Paila", medidas: "Nº62", material: "Barro", pintada: false, precio: 60130 },
  { articulo: "Pie De Maceta", medidas: "Nº45", material: "Barro", pintada: false, precio: 1780 },
  { articulo: "Pie De Maceta", medidas: "Nº90", material: "Barro", pintada: false, precio: 2340 },
  { articulo: "Plato", medidas: "Nº 08", material: "Barro", pintada: false, precio: 1480 },
  { articulo: "Plato", medidas: "Nº 10", material: "Barro", pintada: false, precio: 1600 },
  { articulo: "Plato", medidas: "Nº 12", material: "Barro", pintada: false, precio: 1680 },
  { articulo: "Plato", medidas: "Nº 14", material: "Barro", pintada: false, precio: 2070 },
  { articulo: "Plato", medidas: "Nº 16", material: "Barro", pintada: false, precio: 2690 },
  { articulo: "Plato", medidas: "Nº 18", material: "Barro", pintada: false, precio: 3300 },
  { articulo: "Plato", medidas: "Nº 20", material: "Barro", pintada: false, precio: 4070 },
  { articulo: "Plato", medidas: "Nº 22", material: "Barro", pintada: false, precio: 6300 },
  { articulo: "Plato", medidas: "Nº 24", material: "Barro", pintada: false, precio: 8290 },
  { articulo: "Plato", medidas: "Nº 26", material: "Barro", pintada: false, precio: 10270 },
  { articulo: "Plato", medidas: "Nº 28", material: "Barro", pintada: false, precio: 12410 },
  { articulo: "Plato", medidas: "Nº 30", material: "Barro", pintada: false, precio: 15010 },
  { articulo: "Plato", medidas: "Nº 35", material: "Barro", pintada: false, precio: 17570 },
  { articulo: "Plato", medidas: "Nº 40", material: "Barro", pintada: false, precio: 21270 },
  { articulo: "Plato", medidas: "Nº 45", material: "Barro", pintada: false, precio: 29640 },
  { articulo: "Plato", medidas: "Nº 52", material: "Barro", pintada: false, precio: 36760 },
  { articulo: "Terrina", medidas: "Nº10", material: "Barro", pintada: false, precio: 2560 },
  { articulo: "Terrina", medidas: "Nº12", material: "Barro", pintada: false, precio: 2870 },
  { articulo: "Terrina", medidas: "Nº14", material: "Barro", pintada: false, precio: 3090 },
  { articulo: "Terrina", medidas: "Nº22", material: "Barro", pintada: false, precio: 7650 },
  { articulo: "Terrina", medidas: "Nº24", material: "Barro", pintada: false, precio: 10040 },
  { articulo: "Terrina", medidas: "Nº27", material: "Barro", pintada: false, precio: 14800 },
  { articulo: "MAC. COMUN N*6", medidas: "", material: "Barro", pintada: false, precio: 1240 },
  { articulo: "Mac. Premium", medidas: "N22", material: "Barro", pintada: false, precio: 7970 },
  { articulo: "Bomba", medidas: "Nº30", material: "Barro", pintada: false, precio: 29990 },
  { articulo: "Mac. Comun", medidas: "Nº 10 PINTADA", material: "Barro", pintada: true, precio: 3560 },
  { articulo: "Mac. Comun", medidas: "Nº 12 PINTADA", material: "Barro", pintada: true, precio: 4150 },
  { articulo: "Mac. Comun", medidas: "Nº 22 PINTADA", material: "Barro", pintada: true, precio: 14050 },
  { articulo: "Mac. Comun", medidas: "Nº 08 PINTADA", material: "Barro", pintada: true, precio: 2990 },
  { articulo: "Icono", medidas: "Nº 8", material: "Barro", pintada: false, precio: 1600 },
  { articulo: "Icono", medidas: "Nº 10", material: "Barro", pintada: false, precio: 1650 },
  { articulo: "Icono", medidas: "Nº 8  PINTADA", material: "Barro", pintada: true, precio: 2850 },
  { articulo: "Icono", medidas: "Nº 10  PINTADA", material: "Barro", pintada: true, precio: 3390 },
  // BARRO ARTESANAL — CACHARROS
  { articulo: "Nº3 (*) 20CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 14950 },
  { articulo: "MATERON GIGANTE 10CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 4370 },
  { articulo: "Nº1  (*) 16CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 7240 },
  { articulo: "TIRAS *1 DOC. DEDAL 2CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 13800 },
  { articulo: "PREMIUM N22", medidas: "", material: "Barro Artesanal", pintada: false, precio: 12190 },
  { articulo: "PREMIUM N18", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9090 },
  { articulo: "1/2 PARED", medidas: "", material: "Barro Artesanal", pintada: false, precio: 13800 },
  { articulo: "BANDEJA OVAL GRANDE 30CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 22730 },
  { articulo: "TIRAS *1 DOC. SARTA 5CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 18400 },
  { articulo: "OLLA CHICA CUADRADA Y REDONDA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 22730 },
  { articulo: "OLLA MEDIANA REDONDA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 30300 },
  { articulo: "OLLA EXTRA GRANDE OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 41400 },
  { articulo: "SARTEN C/TAPA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 30300 },
  { articulo: "PAVA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 20700 },
  { articulo: "CASUELA REDONDA 16CM X 7CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9660 },
  { articulo: "CASUELA REDONDO 14CM X 5CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9660 },
  { articulo: "VOLCADO 2  26CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 29320 },
  { articulo: "VOLCADO GIGANTE SUPER 40CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 75900 },
  { articulo: "MATERA EXTRA GRANDE NUEVA 13CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 6040 },
  { articulo: "CHANCHITOS CH.", medidas: "", material: "Barro Artesanal", pintada: false, precio: 10100 },
  { articulo: "CHANCHITOS GRANDE", medidas: "", material: "Barro Artesanal", pintada: false, precio: 14140 },
  { articulo: "TIRAS *1 DOC. OJAL 3CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 20700 },
  { articulo: "MATERA SARTA 8CM BOCA 6CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 2420 },
  { articulo: "N4 30CM BOCA C/MANIJA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 37260 },
  { articulo: "JARRAS GRANDE 24CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 11110 },
  { articulo: "BANDEJA OVAL CHICA 18CM X 6CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 12070 },
  { articulo: "MATERA MEDIANA 6CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 1440 },
  { articulo: "JARRA CHICA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 7580 },
  { articulo: "GIGANTE SUPER", medidas: "", material: "Barro Artesanal", pintada: false, precio: 29320 },
  { articulo: "VOLCADO 1 30CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 29320 },
  // FIBROCEMENTO PINTADO
  // FIBROCEMENTO SIN PINTAR
  // ROTOMOLDEADO
  { articulo: "Misionera", medidas: "20cm c/plato", material: "Rotomoldeado", pintada: false, precio: 8700 },
  { articulo: "Misionera", medidas: "30cm c/plato", material: "Rotomoldeado", pintada: false, precio: 20900 },
  { articulo: "Misionera", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 47900 },
  { articulo: "Misionera", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 80400 },
  { articulo: "Misionera", medidas: "60cm", material: "Rotomoldeado", pintada: false, precio: 119600 },
  { articulo: "Misionera Texturada", medidas: "20h x 15Ø x 18b", material: "Rotomoldeado", pintada: false, precio: 8100 },
  { articulo: "Misionera Texturada", medidas: "30h x 22Ø x 18b", material: "Rotomoldeado", pintada: false, precio: 25110 },
  { articulo: "Misionera Texturada", medidas: "40cm (29h x 22Ø x 18b)", material: "Rotomoldeado", pintada: false, precio: 42590 },
  { articulo: "Salteña con Pie", medidas: "25h x 20Ø x 20b (patas 10cm)", material: "Rotomoldeado", pintada: false, precio: 26500 },
  { articulo: "Cuenco", medidas: "32cm c/plato", material: "Rotomoldeado", pintada: false, precio: 52500 },
  { articulo: "Cuenco", medidas: "48cm c/plato", material: "Rotomoldeado", pintada: false, precio: 123500 },
  { articulo: "Gota", medidas: "40cm c/plato", material: "Rotomoldeado", pintada: false, precio: 49600 },
  { articulo: "Gota", medidas: "55cm c/plato", material: "Rotomoldeado", pintada: false, precio: 69600 },
  { articulo: "Gota", medidas: "70cm c/plato", material: "Rotomoldeado", pintada: false, precio: 83500 },
  { articulo: "Copa", medidas: "40cm c/plato", material: "Rotomoldeado", pintada: false, precio: 37900 },
  { articulo: "Copa", medidas: "55cm c/plato", material: "Rotomoldeado", pintada: false, precio: 73900 },
  { articulo: "Copa", medidas: "70cm c/plato", material: "Rotomoldeado", pintada: false, precio: 122500 },
  { articulo: "Cubo", medidas: "20x20x20", material: "Rotomoldeado", pintada: false, precio: 15200 },
  { articulo: "Cubo", medidas: "30x30x30", material: "Rotomoldeado", pintada: false, precio: 27100 },
  { articulo: "Cubo", medidas: "40x40x40", material: "Rotomoldeado", pintada: false, precio: 58700 },
  { articulo: "Cubo", medidas: "50x50x50", material: "Rotomoldeado", pintada: false, precio: 100600 },
  { articulo: "Piramidal", medidas: "40h x 25bo x 22b", material: "Rotomoldeado", pintada: false, precio: 26200 },
  { articulo: "Piramidal", medidas: "60h x 30bo x 25b", material: "Rotomoldeado", pintada: false, precio: 46300 },
  { articulo: "Piramidal", medidas: "70h x 35bo x 30b", material: "Rotomoldeado", pintada: false, precio: 61700 },
  { articulo: "Cilindro", medidas: "30x30", material: "Rotomoldeado", pintada: false, precio: 48960 },
  { articulo: "Cilindro", medidas: "50x50", material: "Rotomoldeado", pintada: false, precio: 72900 },
  { articulo: "Jardinera", medidas: "60x20x20", material: "Rotomoldeado", pintada: false, precio: 35200 },
  { articulo: "Jardinera", medidas: "80x27x30", material: "Rotomoldeado", pintada: false, precio: 73600 },
  { articulo: "Jardinera", medidas: "100x27x30", material: "Rotomoldeado", pintada: false, precio: 91500 },
  { articulo: "Jardinera", medidas: "100x40x30", material: "Rotomoldeado", pintada: false, precio: 139700 },
  { articulo: "Van Gogh", medidas: "", material: "Rotomoldeado", pintada: false, precio: 24300 },
  { articulo: "Paris", medidas: "30cm", material: "Rotomoldeado", pintada: false, precio: 47700 },
  { articulo: "Paris", medidas: "44cm", material: "Rotomoldeado", pintada: false, precio: 55700 },
  { articulo: "🎁 Combo Copa Trío", medidas: "Copa 40 + 50 + 60cm", material: "Combo", pintada: false, precio: 234000 },
  { articulo: "🎁 Combo Misionera Trío", medidas: "Misionera 40 + 55 + 70cm c/plato", material: "Combo", pintada: false, precio: 191500 },
  { articulo: "🎁 Combo Salteña Trío", medidas: "Salteña 40 + 55 + 70cm c/plato", material: "Combo", pintada: false, precio: 200000 },
  { articulo: "🎁 Combo Entrada", medidas: "2× Misionera 55cm + Copa 40cm", material: "Combo", pintada: false, precio: 179000 },
  { articulo: "🎁 Combo Terraza", medidas: "2× Copa 50cm + Cuenco 32cm", material: "Combo", pintada: false, precio: 205500 },
  { articulo: "🎁 Combo Living", medidas: "2× Misionera 70cm + Misionera 40cm", material: "Combo", pintada: false, precio: 204000 },
  { articulo: "🎁 Combo Misionera Texturada", medidas: "30cm + 40cm", material: "Combo", pintada: false, precio: 59000 },
  // CERÁMICA
  { articulo: "Coco N°1", medidas: "10h x 11d x 8b", material: "Cerámica", pintada: false, precio: 26020 },
  { articulo: "Coco N°2", medidas: "14h x 14d x 11b", material: "Cerámica", pintada: false, precio: 39960 },
  { articulo: "Coco N°3", medidas: "18h x 17d x 14b", material: "Cerámica", pintada: false, precio: 71410 },
  { articulo: "Coco N°4", medidas: "24h x 22d x 18b", material: "Cerámica", pintada: false, precio: 131910 },
  { articulo: "Coco N°5", medidas: "32h x 28d x 28b", material: "Cerámica", pintada: false, precio: 208310 },
  { articulo: "Maceta N°1", medidas: "9h x 11d x 6b", material: "Cerámica", pintada: false, precio: 14730 },
  { articulo: "Maceta N°2", medidas: "14h x 16d x 10b", material: "Cerámica", pintada: false, precio: 25990 },
  { articulo: "Maceta N°3", medidas: "18h x 20d x 12b", material: "Cerámica", pintada: false, precio: 37100 },
  { articulo: "Maceta N°4", medidas: "31h x 29d x 18b", material: "Cerámica", pintada: false, precio: 83760 },
  // PLÁSTICO (muestra)
  { articulo: "Matri Plato", medidas: "Nº12", material: "Plástico", pintada: false, precio: 890 },
  { articulo: "Matri Plato", medidas: "Nº16", material: "Plástico", pintada: false, precio: 960 },
  { articulo: "Matri Plato", medidas: "Nº20", material: "Plástico", pintada: false, precio: 1240 },
  { articulo: "Matri Plato", medidas: "Nº24", material: "Plástico", pintada: false, precio: 1640 },
  { articulo: "Matri Plato", medidas: "Nº30", material: "Plástico", pintada: false, precio: 2040 },
  { articulo: "Matri Plato", medidas: "Nº36", material: "Plástico", pintada: false, precio: 2860 },
  { articulo: "Matri Plato", medidas: "Nº40", material: "Plástico", pintada: false, precio: 3770 },
  { articulo: "Matri Regadera", medidas: "2 lts", material: "Plástico", pintada: false, precio: 7830 },
  { articulo: "Matri Regadera", medidas: "5 lts", material: "Plástico", pintada: false, precio: 13730 },
  { articulo: "Matri Regadera", medidas: "10 lts", material: "Plástico", pintada: false, precio: 24770 },
  { articulo: "Matri Jardinera", medidas: "35 CM", material: "Plástico", pintada: false, precio: 3540 },
  { articulo: "Matri Jardinera", medidas: "45 CM", material: "Plástico", pintada: false, precio: 5220 },
  { articulo: "Matri Jardinera", medidas: "60 CM", material: "Plástico", pintada: false, precio: 10600 },
  { articulo: "Matri Jardinera Imperio", medidas: "50 CM", material: "Plástico", pintada: false, precio: 15880 },
  { articulo: "Matri Jardinera Imperio", medidas: "80 CM", material: "Plástico", pintada: false, precio: 35530 },
  // INSUMOS — Fertilizantes (se clasifican automáticamente)
  { articulo: "GUANO MURCIELAGO X 250 GRS", medidas: "", material: "Insumos", pintada: false, precio: 13450 },
  { articulo: "HUMUS DE LOMBRIS X 500CC", medidas: "", material: "Insumos", pintada: false, precio: 11450 },
  { articulo: "MICORRIZAS X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 10480 },
  { articulo: "TRICHODERMA ENRAIZANTE X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 13470 },
  { articulo: "FERTILIZ ANTISHOCK *100 CC", medidas: "", material: "Insumos", pintada: false, precio: 12710 },
  { articulo: "FERTILIZ ANTISHOCK *500 CC", medidas: "", material: "Insumos", pintada: false, precio: 47200 },
  { articulo: "FERTILIZ *200 CC FLORA/folla/poten.", medidas: "", material: "Insumos", pintada: false, precio: 7040 },
  { articulo: "FERTILIZ *1000CC FLORA/folla/peton.", medidas: "", material: "Insumos", pintada: false, precio: 22120 },
  { articulo: "FERTILIZ ESPECIAL ORQUIDEAS *200 CM.", medidas: "", material: "Insumos", pintada: false, precio: 11110 },
  { articulo: "LJF-TRIPLE 15 *1000GRS", medidas: "", material: "Insumos", pintada: false, precio: 6620 },
  { articulo: "LJF-UREA *1000GRS", medidas: "", material: "Insumos", pintada: false, precio: 6560 },
  { articulo: "JF ABONO ESPECIAL * 120CC", medidas: "", material: "Insumos", pintada: false, precio: 4810 },
  { articulo: "JF ABONO X 200CC FLORACION -FOLLAJE-HORMONA", medidas: "", material: "Insumos", pintada: false, precio: 5880 },
  { articulo: "ACRECIO FERTILIZANTE X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 12380 },
  { articulo: "MEGAGREEN FERTILIZANTE POLVO 50GMS", medidas: "", material: "Insumos", pintada: false, precio: 16600 },
  // INSUMOS — Insecticidas
  { articulo: "PARAISO ORUGUICIDA X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 10650 },
  { articulo: "BTI LARVICIDA INSECTICIDA BIOLOGICO * 30 cc", medidas: "", material: "Insumos", pintada: false, precio: 3720 },
  { articulo: "JABON POTASICO CANELA Y NEEM X 250CC", medidas: "", material: "Insumos", pintada: false, precio: 14510 },
  { articulo: "JABON POTASICO NEUTRO X 500CC", medidas: "", material: "Insumos", pintada: false, precio: 24780 },
  { articulo: "NEEM PURO X 30CC", medidas: "", material: "Insumos", pintada: false, precio: 6380 },
  { articulo: "BEAUVERIA X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 4720 },
  { articulo: "ARAÑUELA X 30CC (ACARICIDA)", medidas: "", material: "Insumos", pintada: false, precio: 2820 },
  { articulo: "REPELENTE DE INSECTOS * 30 cc", medidas: "", material: "Insumos", pintada: false, precio: 4990 },
  { articulo: "HORMIGUICIDA *120 CC.", medidas: "", material: "Insumos", pintada: false, precio: 6270 },
  { articulo: "HORMIGUICIDA *500 CC.", medidas: "", material: "Insumos", pintada: false, precio: 18120 },
  { articulo: "X-TERMIXAN *1000 GRS. POTE", medidas: "", material: "Insumos", pintada: false, precio: 17380 },
  { articulo: "X-VELOXAN *250 CC", medidas: "", material: "Insumos", pintada: false, precio: 16260 },
  { articulo: "X-FUMIXAN FOG * 120 cc", medidas: "", material: "Insumos", pintada: false, precio: 11430 },
  { articulo: "X-MATA-HORMIGAS *250 CC.", medidas: "", material: "Insumos", pintada: false, precio: 8910 },
  { articulo: "X-SISTEMICO *60 CC. 'D'", medidas: "", material: "Insumos", pintada: false, precio: 9980 },
  { articulo: "MYRMEC. X 200GMS 20+5 DE REGALO", medidas: "", material: "Insumos", pintada: false, precio: 4070 },
  { articulo: "MIREX X 100GMS", medidas: "", material: "Insumos", pintada: false, precio: 2590 },
  { articulo: "GEL MATA CUCARACHA * 60 GRS", medidas: "", material: "Insumos", pintada: false, precio: 19470 },
  { articulo: "GEL MATA HORMIGAS X 40 GRS", medidas: "", material: "Insumos", pintada: false, precio: 15680 },
  { articulo: "KAOTRINA X 60 CC", medidas: "", material: "Insumos", pintada: false, precio: 7410 },
  { articulo: "TUTORES *040 CM.", medidas: "", material: "Insumos", pintada: false, precio: 3280 },
  { articulo: "TUTORES *060 CM", medidas: "", material: "Insumos", pintada: false, precio: 4280 },
  { articulo: "TUTORES *100 CM", medidas: "", material: "Insumos", pintada: false, precio: 6560 },
  { articulo: "TUTORES *120CM", medidas: "", material: "Insumos", pintada: false, precio: 8260 },
  { articulo: "TUTORES *160 CM", medidas: "", material: "Insumos", pintada: false, precio: 11400 },
  // INSUMOS — Sustratos
  { articulo: "J-TIERRA *05 DM3", medidas: "", material: "Insumos", pintada: false, precio: 2220 },
  { articulo: "J-TIERRA *25 DM3", medidas: "", material: "Insumos", pintada: false, precio: 5420 },
  { articulo: "J-TURBA JOR *5DM", medidas: "", material: "Insumos", pintada: false, precio: 5390 },
  { articulo: "J-TURBA JOR *25DM", medidas: "", material: "Insumos", pintada: false, precio: 13680 },
  { articulo: "J-PERLITA *3DM NUTRI VIDA", medidas: "", material: "Insumos", pintada: false, precio: 2140 },
  { articulo: "J-PERLITA PERLINO *25DM", medidas: "", material: "Insumos", pintada: false, precio: 14820 },
  { articulo: "J-POMEX *10DM", medidas: "", material: "Insumos", pintada: false, precio: 7600 },
  { articulo: "J-POMEX *25DM", medidas: "", material: "Insumos", pintada: false, precio: 16150 },
  { articulo: "J-HUMUS *05 DM3", medidas: "", material: "Insumos", pintada: false, precio: 3140 },
  { articulo: "J-HUMUS *25 DM3", medidas: "", material: "Insumos", pintada: false, precio: 11680 },
  { articulo: "J-COMPUESTO ORGANICO *10 DM3", medidas: "", material: "Insumos", pintada: false, precio: 3420 },
  { articulo: "J-COMPUESTO ORGANICO *25 DM3", medidas: "", material: "Insumos", pintada: false, precio: 6410 },
  { articulo: "J-SUSTRATO ORQUIDEAS X *3 DM ECO", medidas: "", material: "Insumos", pintada: false, precio: 2710 },
  { articulo: "J-CHIP *10DM", medidas: "", material: "Insumos", pintada: false, precio: 2990 },
  { articulo: "J-CHIP *25DM", medidas: "", material: "Insumos", pintada: false, precio: 6470 },
  { articulo: "J-VERMICULITA NUTRI VIDA *3DM", medidas: "", material: "Insumos", pintada: false, precio: 6610 },
  { articulo: "J-VERMICULITA *25DM", medidas: "", material: "Insumos", pintada: false, precio: 38000 },
  { articulo: "MUSGO BOLSA 25DM", medidas: "", material: "Insumos", pintada: false, precio: 9980 },
  { articulo: "Tierra Abonada", medidas: "5 DM", material: "Insumos", pintada: false, precio: 4180 },
  { articulo: "Tierra Abonada", medidas: "10 DM", material: "Insumos", pintada: false, precio: 4940 },
  { articulo: "Tierra Abonada", medidas: "25 DM", material: "Insumos", pintada: false, precio: 6650 },
  { articulo: "Resaca", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5320 },
  { articulo: "Resaca", medidas: "25 DM", material: "Insumos", pintada: false, precio: 8550 },
  { articulo: "Pinocha", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5600 },
  { articulo: "Pinocha", medidas: "10 DM", material: "Insumos", pintada: false, precio: 6200 },
  { articulo: "Compost", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5320 },
  { articulo: "Compost", medidas: "25 DM", material: "Insumos", pintada: false, precio: 8740 },
  { articulo: "Perlita", medidas: "5 DM", material: "Insumos", pintada: false, precio: 6200 },
  { articulo: "Perlita", medidas: "10 DM", material: "Insumos", pintada: false, precio: 9200 },
  { articulo: "Turba", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Turba", medidas: "10 DM", material: "Insumos", pintada: false, precio: 8740 },
  { articulo: "Sustrato Cactus y Suculentas", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Sustrato Cactus y Suculentas", medidas: "10 DM", material: "Insumos", pintada: false, precio: 7220 },
  { articulo: "Tierra Abonada Ferticam", medidas: "5 DM", material: "Insumos", pintada: false, precio: 4180 },
  { articulo: "Tierra Abonada Ferticam", medidas: "25 DM", material: "Insumos", pintada: false, precio: 6650 },
  { articulo: "Turba Ferticam", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Turba Ferticam", medidas: "10 DM", material: "Insumos", pintada: false, precio: 8740 },
  { articulo: "Cactus y Suculentas Ferticam", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Cactus y Suculentas Ferticam", medidas: "10 DM", material: "Insumos", pintada: false, precio: 7220 },

  // ROTOMOLDEADO — nuevos modelos
  { articulo: "Cubo", medidas: "25x25x25", material: "Rotomoldeado", pintada: false, precio: 21000 },
  { articulo: "Cubo", medidas: "35x35x35", material: "Rotomoldeado", pintada: false, precio: 39800 },
  { articulo: "Piramidal", medidas: "50h x 25bo x 22b", material: "Rotomoldeado", pintada: false, precio: 32100 },
  { articulo: "Jardinera", medidas: "80x20x20", material: "Rotomoldeado", pintada: false, precio: 46200 },
  { articulo: "Jardinera", medidas: "100x20x20", material: "Rotomoldeado", pintada: false, precio: 55700 },
  { articulo: "Jardinera", medidas: "60x27x30", material: "Rotomoldeado", pintada: false, precio: 55700 },
  { articulo: "Cilindro", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 54100 },
  { articulo: "Cilindro", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 80600 },
  { articulo: "Misionera Texturada", medidas: "20cm", material: "Rotomoldeado", pintada: false, precio: 8000 },
  { articulo: "Misionera Texturada", medidas: "30cm", material: "Rotomoldeado", pintada: false, precio: 24900 },
  { articulo: "Misionera Texturada", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 48700 },
  { articulo: "Misionera Texturada", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 95500 },
  { articulo: "Plato Misionera", medidas: "Chico", material: "Rotomoldeado", pintada: false, precio: 7700 },
  { articulo: "Plato Misionera", medidas: "Mediano", material: "Rotomoldeado", pintada: false, precio: 13100 },
  { articulo: "Plato Misionera", medidas: "Grande", material: "Rotomoldeado", pintada: false, precio: 18600 },

  // ROTOMOLDEADO — RAYUM Andina (actualizado)
  { articulo: "Jardinera", medidas: "40x20x30", material: "Rotomoldeado", pintada: false, precio: 43700 },
  { articulo: "Jardinera", medidas: "60x20x30", material: "Rotomoldeado", pintada: false, precio: 81800 },
  { articulo: "Jardinera", medidas: "80x20x30", material: "Rotomoldeado", pintada: false, precio: 114000 },

  // ROTOMOLDEADO — RAYUM Andina (actualizado)
  { articulo: "Andina Rústica", medidas: "N27", material: "Rotomoldeado", pintada: false, precio: 27800 },
  { articulo: "Andina Rústica", medidas: "N40", material: "Rotomoldeado", pintada: false, precio: 60600 },
  { articulo: "Andina Rústica", medidas: "N50", material: "Rotomoldeado", pintada: false, precio: 103500 },
  { articulo: "Andina Rústica", medidas: "N65", material: "Rotomoldeado", pintada: false, precio: 205100 },
  { articulo: "Andina Rústica", medidas: "N80", material: "Rotomoldeado", pintada: false, precio: 327300 },
  { articulo: "Andina Lisa", medidas: "N40", material: "Rotomoldeado", pintada: false, precio: 51100 },
  { articulo: "Andina Lisa", medidas: "N50", material: "Rotomoldeado", pintada: false, precio: 87300 },
  { articulo: "Andina Lisa", medidas: "N65", material: "Rotomoldeado", pintada: false, precio: 173000 },
  { articulo: "Andina Lisa", medidas: "N80", material: "Rotomoldeado", pintada: false, precio: 276100 },
  { articulo: "JARDINERA RAYUM", medidas: "40x20x30", material: "Rotomoldeado", pintada: false, precio: 48100 },
  { articulo: "JARDINERA RAYUM", medidas: "60x20x30", material: "Rotomoldeado", pintada: false, precio: 90000 },
  { articulo: "JARDINERA RAYUM", medidas: "80x20x30", material: "Rotomoldeado", pintada: false, precio: 125400 },


  // ── FIBROCEMENTO ──
  { articulo: "Misionera", medidas: "20altx18bocx16bas", material: "Fibrocemento", acabados: "all", precio: 6400, min_cruda: 6400, min_imp: 10500, min_pint: 11400 },
  { articulo: "Misionera", medidas: "28altx18bocx15bas", material: "Fibrocemento", acabados: "all", precio: 14200, min_cruda: 14200, min_imp: 23200, min_pint: 25100 },
  { articulo: "Misionera", medidas: "38altx28bocx20bas", material: "Fibrocemento", acabados: "all", precio: 22600, min_cruda: 22600, min_imp: 36900, min_pint: 40000 },
  { articulo: "Misionera", medidas: "50altx37bocx32bas", material: "Fibrocemento", acabados: "all", precio: 27700, min_cruda: 27700, min_imp: 45400, min_pint: 49100 },
  { articulo: "Misionera", medidas: "63altx40bocx32bas", material: "Fibrocemento", acabados: "all", precio: 41900, min_cruda: 41900, min_imp: 68600, min_pint: 74300 },
  { articulo: "Misionera", medidas: "67altx37bocx32bas", material: "Fibrocemento", acabados: "all", precio: 40600, min_cruda: 40600, min_imp: 66400, min_pint: 71900 },
  { articulo: "Misionera", medidas: "90altx40bocx35bas", material: "Fibrocemento", acabados: "all", precio: 68500, min_cruda: 68500, min_imp: 112100, min_pint: 121400 },
  { articulo: "Misionera", medidas: "80altx50bocx40bas", material: "Fibrocemento", acabados: "all", precio: 72500, min_cruda: 72500, min_imp: 118700, min_pint: 128600 },
  { articulo: "Misionera con Borde", medidas: "35altx32bocx30bas", material: "Fibrocemento", acabados: "all", precio: 22700, min_cruda: 22700, min_imp: 37200, min_pint: 40300 },
  { articulo: "Misionera con Borde", medidas: "45altx45bocx42bas", material: "Fibrocemento", acabados: "all", precio: 29800, min_cruda: 29800, min_imp: 48700, min_pint: 52800 },
  { articulo: "Misionera con Borde", medidas: "55altx50bocx45bas", material: "Fibrocemento", acabados: "all", precio: 54100, min_cruda: 54100, min_imp: 88400, min_pint: 95800 },
  { articulo: "Misionera Recta", medidas: "40hx35Øx40bas", material: "Fibrocemento", acabados: "all", precio: 28700, min_cruda: 28700, min_imp: 47000, min_pint: 50900 },
  { articulo: "Misionera Recta", medidas: "55hx35Øx40bas", material: "Fibrocemento", acabados: "all", precio: 32400, min_cruda: 32400, min_imp: 53000, min_pint: 57500 },
  { articulo: "Misionera Recta", medidas: "70hx35Øx40bas", material: "Fibrocemento", acabados: "all", precio: 41000, min_cruda: 41000, min_imp: 67100, min_pint: 72700 },
  { articulo: "Salteña", medidas: "27altx24bocx20bas", material: "Fibrocemento", acabados: "all", precio: 11700, min_cruda: 11700, min_imp: 19100, min_pint: 20700 },
  { articulo: "Salteña", medidas: "45altx35bocx20bas", material: "Fibrocemento", acabados: "all", precio: 20900, min_cruda: 20900, min_imp: 34300, min_pint: 37100 },
  { articulo: "Salteña", medidas: "45altx40bocx20bas", material: "Fibrocemento", acabados: "all", precio: 22200, min_cruda: 22200, min_imp: 36300, min_pint: 39300 },
  { articulo: "Salteña", medidas: "41altx50bocx35bas", material: "Fibrocemento", acabados: "all", precio: 28200, min_cruda: 28200, min_imp: 46200, min_pint: 50000 },
  { articulo: "Salteña", medidas: "65altx50bocx25bas", material: "Fibrocemento", acabados: "all", precio: 45200, min_cruda: 45200, min_imp: 74000, min_pint: 80200 },
  { articulo: "Salteña", medidas: "50altx65bocx32bas", material: "Fibrocemento", acabados: "all", precio: 69200, min_cruda: 69200, min_imp: 113300, min_pint: 122700 },
  { articulo: "Salteña", medidas: "77altx65bocx32bas", material: "Fibrocemento", acabados: "all", precio: 83000, min_cruda: 83000, min_imp: 135800, min_pint: 147100 },
  { articulo: "Copa", medidas: "40altx33bocx16bas", material: "Fibrocemento", acabados: "all", precio: 16100, min_cruda: 16100, min_imp: 26400, min_pint: 28600 },
  { articulo: "Copa", medidas: "55altx45bocx28bas", material: "Fibrocemento", acabados: "all", precio: 32200, min_cruda: 32200, min_imp: 52700, min_pint: 57100 },
  { articulo: "Copa", medidas: "70altx50bocx28bas", material: "Fibrocemento", acabados: "all", precio: 70100, min_cruda: 70100, min_imp: 114700, min_pint: 124300 },
  { articulo: "Bols", medidas: "28altx55bocx27bas", material: "Fibrocemento", acabados: "all", precio: 20600, min_cruda: 20600, min_imp: 33800, min_pint: 36600 },
  { articulo: "Bols", medidas: "30altx80bocx33bas", material: "Fibrocemento", acabados: "all", precio: 33000, min_cruda: 33000, min_imp: 54100, min_pint: 58600 },
  { articulo: "Cónica / Tradicional", medidas: "30altx30bocx18bas", material: "Fibrocemento", acabados: "all", precio: 12100, min_cruda: 12100, min_imp: 19800, min_pint: 21400 },
  { articulo: "Cónica / Tradicional", medidas: "40altx40bocx25bas", material: "Fibrocemento", acabados: "all", precio: 24000, min_cruda: 24000, min_imp: 39300, min_pint: 42500 },
  { articulo: "Cónica / Tradicional", medidas: "50altx50bocx29bas", material: "Fibrocemento", acabados: "all", precio: 26200, min_cruda: 26200, min_imp: 42900, min_pint: 46400 },
  { articulo: "Cónica / Tradicional", medidas: "60altx60bocx36bas", material: "Fibrocemento", acabados: "all", precio: 36300, min_cruda: 36300, min_imp: 59400, min_pint: 64300 },
  { articulo: "Cónica / Tradicional", medidas: "70altx70bocx44bas", material: "Fibrocemento", acabados: "all", precio: 65100, min_cruda: 65100, min_imp: 106500, min_pint: 115400 },
  { articulo: "Andina", medidas: "35altx40bocx26bas", material: "Fibrocemento", acabados: "all", precio: 22000, min_cruda: 22000, min_imp: 36000, min_pint: 39000 },
  { articulo: "Andina", medidas: "43altx50bocx33bas", material: "Fibrocemento", acabados: "all", precio: 30900, min_cruda: 30900, min_imp: 50500, min_pint: 54800 },
  { articulo: "Andina", medidas: "55altx65bocx43bas", material: "Fibrocemento", acabados: "all", precio: 55200, min_cruda: 55200, min_imp: 90300, min_pint: 97800 },
  { articulo: "Andina", medidas: "69altx80bocx53bas", material: "Fibrocemento", acabados: "all", precio: 147300, min_cruda: 147300, min_imp: 241100, min_pint: 261200 },
  { articulo: "Cono", medidas: "60altx38bocx30bas", material: "Fibrocemento", acabados: "all", precio: 22600, min_cruda: 22600, min_imp: 36900, min_pint: 40000 },
  { articulo: "Cono", medidas: "80altx40bocx30bas", material: "Fibrocemento", acabados: "all", precio: 29000, min_cruda: 29000, min_imp: 47500, min_pint: 51400 },
  { articulo: "Cono", medidas: "100altx45bocx30bas", material: "Fibrocemento", acabados: "all", precio: 45100, min_cruda: 45100, min_imp: 73900, min_pint: 80000 },
  { articulo: "Cono Moderno", medidas: "40altx31bocx22bas", material: "Fibrocemento", acabados: "all", precio: 16200, min_cruda: 16200, min_imp: 26500, min_pint: 28700 },
  { articulo: "Cono Moderno", medidas: "55altx36bocx24bas", material: "Fibrocemento", acabados: "all", precio: 21000, min_cruda: 21000, min_imp: 34300, min_pint: 37200 },
  { articulo: "Cono Moderno", medidas: "70altx46bocx24bas", material: "Fibrocemento", acabados: "all", precio: 28200, min_cruda: 28200, min_imp: 46200, min_pint: 50000 },
  { articulo: "Cono Moderno", medidas: "80altx46bocx28bas", material: "Fibrocemento", acabados: "all", precio: 37000, min_cruda: 37000, min_imp: 60600, min_pint: 65600 },
  { articulo: "Esfera", medidas: "20cm", material: "Fibrocemento", acabados: "all", precio: 9000, min_cruda: 9000, min_imp: 14800, min_pint: 16000 },
  { articulo: "Esfera", medidas: "28cm", material: "Fibrocemento", acabados: "all", precio: 12600, min_cruda: 12600, min_imp: 20700, min_pint: 22400 },
  { articulo: "Esfera", medidas: "40cm", material: "Fibrocemento", acabados: "all", precio: 18100, min_cruda: 18100, min_imp: 29600, min_pint: 32000 },
  { articulo: "Esfera", medidas: "50cm", material: "Fibrocemento", acabados: "all", precio: 36100, min_cruda: 36100, min_imp: 59100, min_pint: 64100 },
  { articulo: "Maceta Esférica", medidas: "20Ø", material: "Fibrocemento", acabados: "all", precio: 8100, min_cruda: 8100, min_imp: 13200, min_pint: 14300 },
  { articulo: "Maceta Esférica", medidas: "30Ø", material: "Fibrocemento", acabados: "all", precio: 11300, min_cruda: 11300, min_imp: 18500, min_pint: 20000 },
  { articulo: "Maceta Esférica", medidas: "40Ø", material: "Fibrocemento", acabados: "all", precio: 16100, min_cruda: 16100, min_imp: 26400, min_pint: 28600 },
  { articulo: "Maceta Esférica", medidas: "50Ø", material: "Fibrocemento", acabados: "all", precio: 32200, min_cruda: 32200, min_imp: 52700, min_pint: 57100 },
  { articulo: "Paila", medidas: "33cm", material: "Fibrocemento", acabados: "all", precio: 7700, min_cruda: 7700, min_imp: 12700, min_pint: 13700 },
  { articulo: "Paila", medidas: "48cm", material: "Fibrocemento", acabados: "all", precio: 11700, min_cruda: 11700, min_imp: 19100, min_pint: 20700 },
  { articulo: "Paila", medidas: "60cm", material: "Fibrocemento", acabados: "all", precio: 14900, min_cruda: 14900, min_imp: 24300, min_pint: 26300 },
  { articulo: "Premium", medidas: "20cmx22", material: "Fibrocemento", acabados: "all", precio: 6200, min_cruda: 6200, min_imp: 10100, min_pint: 11000 },
  { articulo: "Premium", medidas: "24cmx27", material: "Fibrocemento", acabados: "all", precio: 9300, min_cruda: 9300, min_imp: 15200, min_pint: 16500 },
  { articulo: "Premium", medidas: "30cmx35", material: "Fibrocemento", acabados: "all", precio: 14200, min_cruda: 14200, min_imp: 23300, min_pint: 25200 },
  { articulo: "Sanjuanina", medidas: "53altx36bocx30bas", material: "Fibrocemento", acabados: "all", precio: 32300, min_cruda: 32300, min_imp: 52800, min_pint: 57200 },
  { articulo: "Sanjuanina", medidas: "63altx39bocx33bas", material: "Fibrocemento", acabados: "all", precio: 38700, min_cruda: 38700, min_imp: 63300, min_pint: 68600 },
  { articulo: "Tinaja", medidas: "50cm", material: "Fibrocemento", acabados: "all", precio: 29200, min_cruda: 29200, min_imp: 47700, min_pint: 51700 },
  { articulo: "Tinaja", medidas: "60cm", material: "Fibrocemento", acabados: "all", precio: 32800, min_cruda: 32800, min_imp: 53700, min_pint: 58200 },
  { articulo: "Tinaja", medidas: "80cm", material: "Fibrocemento", acabados: "all", precio: 100300, min_cruda: 100300, min_imp: 164100, min_pint: 177800 },
  { articulo: "Ánfora", medidas: "75cm de alto", material: "Fibrocemento", acabados: "all", precio: 54700, min_cruda: 54700, min_imp: 89500, min_pint: 97000 },
  { articulo: "Ánfora", medidas: "90cm de alto", material: "Fibrocemento", acabados: "all", precio: 78400, min_cruda: 78400, min_imp: 128300, min_pint: 139000 },
  { articulo: "Grecia", medidas: "24hx32Øx15bas", material: "Fibrocemento", acabados: "all", precio: 23200, min_cruda: 23200, min_imp: 37900, min_pint: 41000 },
  { articulo: "Grecia", medidas: "36hx44Øx20bas", material: "Fibrocemento", acabados: "all", precio: 24800, min_cruda: 24800, min_imp: 40600, min_pint: 44000 },
  { articulo: "Grecia", medidas: "42hx55Øx25bas", material: "Fibrocemento", acabados: "all", precio: 29500, min_cruda: 29500, min_imp: 48300, min_pint: 52400 },
  { articulo: "Cilindro", medidas: "30altx30bocx30bas", material: "Fibrocemento", acabados: "all", precio: 9400, min_cruda: 9400, min_imp: 15500, min_pint: 16900 },
  { articulo: "Cilindro", medidas: "45altx40bocx45bas", material: "Fibrocemento", acabados: "all", precio: 19300, min_cruda: 19300, min_imp: 31900, min_pint: 34800 },
  { articulo: "Cilindro", medidas: "45altx45bocx45bas", material: "Fibrocemento", acabados: "all", precio: 19300, min_cruda: 19300, min_imp: 31900, min_pint: 34800 },
  { articulo: "Cilindro", medidas: "50altx30bocx30bas", material: "Fibrocemento", acabados: "all", precio: 19600, min_cruda: 19600, min_imp: 32300, min_pint: 35200 },
  { articulo: "Cilindro", medidas: "52altx52bocx52bas", material: "Fibrocemento", acabados: "all", precio: 23500, min_cruda: 23500, min_imp: 38700, min_pint: 42200 },
  { articulo: "Cilindro", medidas: "60altx60bocx60bas", material: "Fibrocemento", acabados: "all", precio: 44000, min_cruda: 44000, min_imp: 72500, min_pint: 79100 },
  { articulo: "Cubo", medidas: "15altx15bocx15bas", material: "Fibrocemento", acabados: "all", precio: 4400, min_cruda: 4400, min_imp: 7200, min_pint: 7900 },
  { articulo: "Cubo", medidas: "20altx20bocx20bas", material: "Fibrocemento", acabados: "all", precio: 5500, min_cruda: 5500, min_imp: 9100, min_pint: 9900 },
  { articulo: "Cubo", medidas: "25altx25bocx25bas", material: "Fibrocemento", acabados: "all", precio: 8100, min_cruda: 8100, min_imp: 13300, min_pint: 14500 },
  { articulo: "Cubo", medidas: "30altx30bocx30bas", material: "Fibrocemento", acabados: "all", precio: 11000, min_cruda: 11000, min_imp: 18100, min_pint: 19800 },
  { articulo: "Cubo", medidas: "35altx35bocx35bas", material: "Fibrocemento", acabados: "all", precio: 13900, min_cruda: 13900, min_imp: 23000, min_pint: 25100 },
  { articulo: "Cubo", medidas: "40altx40bocx40bas", material: "Fibrocemento", acabados: "all", precio: 16500, min_cruda: 16500, min_imp: 27200, min_pint: 29700 },
  { articulo: "Cubo", medidas: "45altx45bocx45bas", material: "Fibrocemento", acabados: "all", precio: 22000, min_cruda: 22000, min_imp: 36300, min_pint: 39600 },
  { articulo: "Cubo", medidas: "50altx50bocx50bas", material: "Fibrocemento", acabados: "all", precio: 29300, min_cruda: 29300, min_imp: 48400, min_pint: 52700 },
  { articulo: "Cubo", medidas: "60altx60bocx60bas", material: "Fibrocemento", acabados: "all", precio: 53000, min_cruda: 53000, min_imp: 87500, min_pint: 95500 },
  { articulo: "Jardinera", medidas: "40lrgx13anchx15alt", material: "Fibrocemento", acabados: "all", precio: 8100, min_cruda: 8100, min_imp: 13300, min_pint: 14500 },
  { articulo: "Jardinera", medidas: "40lrgx20anchx10alt", material: "Fibrocemento", acabados: "all", precio: 7000, min_cruda: 7000, min_imp: 11500, min_pint: 12500 },
  { articulo: "Jardinera", medidas: "40lrgx20anchx20alt", material: "Fibrocemento", acabados: "all", precio: 8500, min_cruda: 8500, min_imp: 13900, min_pint: 15200 },
  { articulo: "Jardinera", medidas: "50lrgx20anchx20alt", material: "Fibrocemento", acabados: "all", precio: 9900, min_cruda: 9900, min_imp: 16400, min_pint: 17900 },
  { articulo: "Jardinera", medidas: "60lrgx13anchx15alt", material: "Fibrocemento", acabados: "all", precio: 9500, min_cruda: 9500, min_imp: 15700, min_pint: 17200 },
  { articulo: "Jardinera", medidas: "60lrgx20anchx10alt", material: "Fibrocemento", acabados: "all", precio: 8200, min_cruda: 8200, min_imp: 13500, min_pint: 14800 },
  { articulo: "Jardinera", medidas: "60lrgx20anchx30alt", material: "Fibrocemento", acabados: "all", precio: 15900, min_cruda: 15900, min_imp: 26300, min_pint: 28600 },
  { articulo: "Jardinera", medidas: "60lrgx20anchx40alt", material: "Fibrocemento", acabados: "all", precio: 16900, min_cruda: 16900, min_imp: 27900, min_pint: 30400 },
  { articulo: "Jardinera", medidas: "60lrgx22anchx20alt", material: "Fibrocemento", acabados: "all", precio: 13900, min_cruda: 13900, min_imp: 23000, min_pint: 25100 },
  { articulo: "Jardinera", medidas: "60lrgx30anchx30alt", material: "Fibrocemento", acabados: "all", precio: 18000, min_cruda: 18000, min_imp: 29600, min_pint: 32300 },
  { articulo: "Jardinera", medidas: "60lrgx30anchx35alt", material: "Fibrocemento", acabados: "all", precio: 19400, min_cruda: 19400, min_imp: 32100, min_pint: 35000 },
  { articulo: "Jardinera", medidas: "80lrgx13anchx15alt", material: "Fibrocemento", acabados: "all", precio: 11700, min_cruda: 11700, min_imp: 19400, min_pint: 21100 },
  { articulo: "Jardinera", medidas: "80lrgx20anchx30alt", material: "Fibrocemento", acabados: "all", precio: 19400, min_cruda: 19400, min_imp: 32100, min_pint: 35000 },
  { articulo: "Jardinera", medidas: "80lrgx20anchx40alt", material: "Fibrocemento", acabados: "all", precio: 25600, min_cruda: 25600, min_imp: 42300, min_pint: 46200 },
  { articulo: "Jardinera", medidas: "80lrgx22anchx20alt", material: "Fibrocemento", acabados: "all", precio: 16900, min_cruda: 16900, min_imp: 27800, min_pint: 30400 },
  { articulo: "Jardinera", medidas: "80lrgx30anchx30alt", material: "Fibrocemento", acabados: "all", precio: 25600, min_cruda: 25600, min_imp: 42300, min_pint: 46200 },
  { articulo: "Jardinera", medidas: "80lrgx30anchx35alt", material: "Fibrocemento", acabados: "all", precio: 25700, min_cruda: 25700, min_imp: 42400, min_pint: 46200 },
  { articulo: "Jardinera", medidas: "80lrgx35anchx40alt", material: "Fibrocemento", acabados: "all", precio: 29300, min_cruda: 29300, min_imp: 48400, min_pint: 52700 },
  { articulo: "Jardinera", medidas: "100lrgx13anchx15alt", material: "Fibrocemento", acabados: "all", precio: 16500, min_cruda: 16500, min_imp: 27200, min_pint: 29700 },
  { articulo: "Jardinera", medidas: "100lrgx20anchx30alt", material: "Fibrocemento", acabados: "all", precio: 23800, min_cruda: 23800, min_imp: 39300, min_pint: 42900 },
  { articulo: "Jardinera", medidas: "100lrgx20anchx40alt", material: "Fibrocemento", acabados: "all", precio: 29300, min_cruda: 29300, min_imp: 48400, min_pint: 52700 },
  { articulo: "Jardinera", medidas: "100lrgx22anchx20alt", material: "Fibrocemento", acabados: "all", precio: 22000, min_cruda: 22000, min_imp: 36300, min_pint: 39600 },
  { articulo: "Jardinera", medidas: "100lrgx30anchx30alt", material: "Fibrocemento", acabados: "all", precio: 29300, min_cruda: 29300, min_imp: 48400, min_pint: 52700 },
  { articulo: "Jardinera", medidas: "100lrgx30anchx35alt", material: "Fibrocemento", acabados: "all", precio: 33000, min_cruda: 33000, min_imp: 54400, min_pint: 59400 },
  { articulo: "Jardinera", medidas: "100lrgx35anchx40alt", material: "Fibrocemento", acabados: "all", precio: 40300, min_cruda: 40300, min_imp: 66500, min_pint: 72500 },
  { articulo: "Jardinera", medidas: "100lrgx40anchx40alt", material: "Fibrocemento", acabados: "all", precio: 44000, min_cruda: 44000, min_imp: 72500, min_pint: 79100 },
  { articulo: "Jardinera", medidas: "115lrgx50anchx45alt", material: "Fibrocemento", acabados: "all", precio: 89500, min_cruda: 89500, min_imp: 147700, min_pint: 161100 },
  { articulo: "Jardinera", medidas: "125lrgx50anchx45alt", material: "Fibrocemento", acabados: "all", precio: 91200, min_cruda: 91200, min_imp: 150400, min_pint: 164100 },
  { articulo: "Jardinera", medidas: "135lrgx50anchx45alt", material: "Fibrocemento", acabados: "all", precio: 102800, min_cruda: 102800, min_imp: 169600, min_pint: 185000 },
  { articulo: "Piramidal", medidas: "50altx25bocx18bas", material: "Fibrocemento", acabados: "all", precio: 12400, min_cruda: 12400, min_imp: 20500, min_pint: 22400 },
  { articulo: "Piramidal", medidas: "45altx35bocx22bas", material: "Fibrocemento", acabados: "all", precio: 14100, min_cruda: 14100, min_imp: 23200, min_pint: 25400 },
  { articulo: "Piramidal", medidas: "45altx45bocx30bas", material: "Fibrocemento", acabados: "all", precio: 15700, min_cruda: 15700, min_imp: 26000, min_pint: 28300 },
  { articulo: "Piramidal", medidas: "50altx40bocx30bas", material: "Fibrocemento", acabados: "all", precio: 15700, min_cruda: 15700, min_imp: 26000, min_pint: 28300 },
  { articulo: "Piramidal", medidas: "60altx30bocx22bas", material: "Fibrocemento", acabados: "all", precio: 15700, min_cruda: 15700, min_imp: 26000, min_pint: 28300 },
  { articulo: "Piramidal", medidas: "60altx35bocx25bas", material: "Fibrocemento", acabados: "all", precio: 16600, min_cruda: 16600, min_imp: 27300, min_pint: 29800 },
  { articulo: "Piramidal", medidas: "70altx30bocx20bas", material: "Fibrocemento", acabados: "all", precio: 16600, min_cruda: 16600, min_imp: 27300, min_pint: 29800 },
  { articulo: "Piramidal", medidas: "70altx35bocx25bas", material: "Fibrocemento", acabados: "all", precio: 22400, min_cruda: 22400, min_imp: 36900, min_pint: 40300 },
  { articulo: "Piramidal", medidas: "80altx30bocx20bas", material: "Fibrocemento", acabados: "all", precio: 22400, min_cruda: 22400, min_imp: 36900, min_pint: 40300 },
  { articulo: "Piramidal", medidas: "80altx35bocx25bas", material: "Fibrocemento", acabados: "all", precio: 26500, min_cruda: 26500, min_imp: 43800, min_pint: 47700 },
  { articulo: "Piramidal", medidas: "80altx40bocx30bas", material: "Fibrocemento", acabados: "all", precio: 29800, min_cruda: 29800, min_imp: 49200, min_pint: 53700 },
  { articulo: "Piramidal", medidas: "80altx50bocx30bas", material: "Fibrocemento", acabados: "all", precio: 44800, min_cruda: 44800, min_imp: 73800, min_pint: 80600 },
  { articulo: "Prisma", medidas: "30altx20bocx20bas", material: "Fibrocemento", acabados: "all", precio: 5700, min_cruda: 5700, min_imp: 9400, min_pint: 10300 },
  { articulo: "Prisma", medidas: "40altx20bocx20bas", material: "Fibrocemento", acabados: "all", precio: 6900, min_cruda: 6900, min_imp: 11300, min_pint: 12300 },
  { articulo: "Prisma", medidas: "40altx30bocx30bas", material: "Fibrocemento", acabados: "all", precio: 10500, min_cruda: 10500, min_imp: 17400, min_pint: 19000 },
  { articulo: "Prisma", medidas: "50altx20bocx20bas", material: "Fibrocemento", acabados: "all", precio: 9400, min_cruda: 9400, min_imp: 15500, min_pint: 16900 },
  { articulo: "Prisma", medidas: "50altx30bocx30bas", material: "Fibrocemento", acabados: "all", precio: 16400, min_cruda: 16400, min_imp: 27100, min_pint: 29500 },
  { articulo: "Prisma", medidas: "50altx40bocx40bas", material: "Fibrocemento", acabados: "all", precio: 20500, min_cruda: 20500, min_imp: 33800, min_pint: 36900 },
  { articulo: "Prisma", medidas: "60altx20bocx20bas", material: "Fibrocemento", acabados: "all", precio: 10000, min_cruda: 10000, min_imp: 16400, min_pint: 17900 },
  { articulo: "Prisma", medidas: "60altx30bocx30bas", material: "Fibrocemento", acabados: "all", precio: 18800, min_cruda: 18800, min_imp: 30900, min_pint: 33800 },
  { articulo: "Prisma", medidas: "60altx40bocx40bas", material: "Fibrocemento", acabados: "all", precio: 22300, min_cruda: 22300, min_imp: 36700, min_pint: 40100 },
  { articulo: "Prisma", medidas: "80altx20bocx20bas", material: "Fibrocemento", acabados: "all", precio: 14100, min_cruda: 14100, min_imp: 23200, min_pint: 25300 },
  { articulo: "Prisma", medidas: "80altx30bocx30bas", material: "Fibrocemento", acabados: "all", precio: 21100, min_cruda: 21100, min_imp: 34800, min_pint: 38000 },
  { articulo: "Prisma", medidas: "80altx40bocx40bas", material: "Fibrocemento", acabados: "all", precio: 40900, min_cruda: 40900, min_imp: 67500, min_pint: 73600 },
  { articulo: "Plato", medidas: "20cm", material: "Fibrocemento", acabados: "cruda_pint", precio: 2700, min_cruda: 2700, min_pint: 4800 },
  { articulo: "Plato", medidas: "30cm", material: "Fibrocemento", acabados: "cruda_pint", precio: 4400, min_cruda: 4400, min_pint: 7900 },
  { articulo: "Plato", medidas: "40cm", material: "Fibrocemento", acabados: "cruda_pint", precio: 7000, min_cruda: 7000, min_pint: 12500 },
  { articulo: "Plato", medidas: "45cm", material: "Fibrocemento", acabados: "cruda_pint", precio: 9600, min_cruda: 9600, min_pint: 17300 },
  { articulo: "Plato", medidas: "50cm", material: "Fibrocemento", acabados: "cruda_pint", precio: 11800, min_cruda: 11800, min_pint: 21200 },
  { articulo: "Buda (cabeza)", medidas: "45cmx30cm", material: "Fibrocemento", acabados: "cruda", precio: 32800, min_cruda: 32800 },




  // ── FIBRA DE VIDRIO ──
  { articulo: "Cilindro FV", medidas: "28×18", material: "Fibra de Vidrio", pintada: false, precio: 89000 },
  { articulo: "Cilindro FV", medidas: "28×26", material: "Fibra de Vidrio", pintada: false, precio: 102000 },
  { articulo: "Cilindro FV", medidas: "30×30", material: "Fibra de Vidrio", pintada: false, precio: 114000 },
  { articulo: "Cilindro FV", medidas: "30×34", material: "Fibra de Vidrio", pintada: false, precio: 125000 },
  { articulo: "Cilindro FV", medidas: "34×34", material: "Fibra de Vidrio", pintada: false, precio: 135000 },
  { articulo: "Cilindro FV", medidas: "39×25", material: "Fibra de Vidrio", pintada: false, precio: 119000 },
  { articulo: "Cilindro FV", medidas: "39×34", material: "Fibra de Vidrio", pintada: false, precio: 157000 },
  { articulo: "Cilindro FV", medidas: "39×43", material: "Fibra de Vidrio", pintada: false, precio: 182000 },
  { articulo: "Cilindro FV", medidas: "39×64", material: "Fibra de Vidrio", pintada: false, precio: 292000 },
  { articulo: "Cilindro FV", medidas: "50×34", material: "Fibra de Vidrio", pintada: false, precio: 223000 },
  { articulo: "Cilindro FV", medidas: "50×43", material: "Fibra de Vidrio", pintada: false, precio: 244000 },
  { articulo: "Cilindro FV", medidas: "60×43", material: "Fibra de Vidrio", pintada: false, precio: 300000 },
  { articulo: "Cilindro FV", medidas: "75×43", material: "Fibra de Vidrio", pintada: false, precio: 473000 },
  { articulo: "Cubo FV", medidas: "30×30", material: "Fibra de Vidrio", pintada: false, precio: 124000 },
  { articulo: "Cubo FV", medidas: "40×25", material: "Fibra de Vidrio", pintada: false, precio: 145000 },
  { articulo: "Cubo FV", medidas: "40×40", material: "Fibra de Vidrio", pintada: false, precio: 192000 },
  { articulo: "Cubo FV", medidas: "50×40", material: "Fibra de Vidrio", pintada: false, precio: 245000 },
  { articulo: "Cubo FV", medidas: "60×40", material: "Fibra de Vidrio", pintada: false, precio: 428000 },
  { articulo: "Cubo FV", medidas: "70×40", material: "Fibra de Vidrio", pintada: false, precio: 514000 },
  { articulo: "Jardinera FV", medidas: "11×30×12", material: "Fibra de Vidrio", pintada: false, precio: 88000 },
  { articulo: "Jardinera FV", medidas: "11×40×12", material: "Fibra de Vidrio", pintada: false, precio: 96000 },
  { articulo: "Jardinera FV", medidas: "11×50×12", material: "Fibra de Vidrio", pintada: false, precio: 102000 },
  { articulo: "Jardinera FV", medidas: "11×60×12", material: "Fibra de Vidrio", pintada: false, precio: 114000 },
  { articulo: "Jardinera FV", medidas: "17×55×17", material: "Fibra de Vidrio", pintada: false, precio: 121000 },
  { articulo: "Jardinera FV", medidas: "17×80×17", material: "Fibra de Vidrio", pintada: false, precio: 137000 },
  { articulo: "Jardinera FV", medidas: "17×100×17", material: "Fibra de Vidrio", pintada: false, precio: 156000 },
  { articulo: "Jardinera FV", medidas: "17×120×17", material: "Fibra de Vidrio", pintada: false, precio: 184000 },
  { articulo: "Jardinera FV", medidas: "22×60×22", material: "Fibra de Vidrio", pintada: false, precio: 145000 },
  { articulo: "Jardinera FV", medidas: "22×80×22", material: "Fibra de Vidrio", pintada: false, precio: 181000 },
  { articulo: "Jardinera FV", medidas: "22×100×22", material: "Fibra de Vidrio", pintada: false, precio: 215000 },
  { articulo: "Jardinera FV", medidas: "25×60×28", material: "Fibra de Vidrio", pintada: false, precio: 191000 },
  { articulo: "Jardinera FV", medidas: "25×80×28", material: "Fibra de Vidrio", pintada: false, precio: 227000 },
  { articulo: "Jardinera FV", medidas: "25×100×28", material: "Fibra de Vidrio", pintada: false, precio: 277000 },
  { articulo: "Jardinera FV", medidas: "30×80×34", material: "Fibra de Vidrio", pintada: false, precio: 247000 },
  { articulo: "Jardinera FV", medidas: "30×100×34", material: "Fibra de Vidrio", pintada: false, precio: 329000 },
  { articulo: "Jardinera FV", medidas: "30×120×34", material: "Fibra de Vidrio", pintada: false, precio: 360000 },
  { articulo: "Cuenco FV", medidas: "40×30", material: "Fibra de Vidrio", pintada: false, precio: 195000 },
  { articulo: "Cuenco FV", medidas: "45×45", material: "Fibra de Vidrio", pintada: false, precio: 257000 },
  { articulo: "Cuenco FV", medidas: "50×40", material: "Fibra de Vidrio", pintada: false, precio: 257000 },
  { articulo: "Cuenco FV", medidas: "60×50", material: "Fibra de Vidrio", pintada: false, precio: 379000 },
  { articulo: "Misionera FV", medidas: "27×29", material: "Fibra de Vidrio", pintada: false, precio: 203000 },
  { articulo: "Misionera FV", medidas: "37×39", material: "Fibra de Vidrio", pintada: false, precio: 282000 },
  { articulo: "Misionera FV", medidas: "47×50", material: "Fibra de Vidrio", pintada: false, precio: 354000 },
  { articulo: "Plato FV", medidas: "Ø30", material: "Fibra de Vidrio", pintada: false, precio: 32000 },
  { articulo: "Plato FV", medidas: "Ø34", material: "Fibra de Vidrio", pintada: false, precio: 41000 },
  { articulo: "Plato FV", medidas: "Ø39", material: "Fibra de Vidrio", pintada: false, precio: 50000 },
  { articulo: "Salteña FV", medidas: "68×76", material: "Fibra de Vidrio", pintada: false, precio: 584000 },
  { articulo: "Salteña FV", medidas: "68×57", material: "Fibra de Vidrio", pintada: false, precio: 466000 },
  { articulo: "Gota FV", medidas: "Nº1 24×26", material: "Fibra de Vidrio", pintada: false, precio: 105000 },
  { articulo: "Gota FV", medidas: "Nº2 35×45", material: "Fibra de Vidrio", pintada: false, precio: 215000 },
  { articulo: "Cuenco FV", medidas: "Nº1 40×30", material: "Fibra de Vidrio", pintada: false, precio: 123000 },
  { articulo: "Cuenco FV", medidas: "Nº2 50×37", material: "Fibra de Vidrio", pintada: false, precio: 160000 },


  // ── CHIP DE CORTEZA (Jorma) ──
  { articulo: "Chip de Corteza", medidas: "*03 DM", material: "Insumos", pintada: false, precio: 3000 },
  { articulo: "Chip de Corteza", medidas: "*10 DM", material: "Insumos", pintada: false, precio: 3700 },
  { articulo: "Chip de Corteza", medidas: "*25 DM", material: "Insumos", pintada: false, precio: 7700 },

  // ── MUSGO ──
  { articulo: "Musgo", medidas: "25 DM", material: "Insumos", pintada: false, precio: 10000 },

  // ── PERLITA PERLINO ──
  { articulo: "Perlita Perlino", medidas: "*3 DM", material: "Insumos", pintada: false, precio: 2400 },
  { articulo: "Perlita Perlino", medidas: "*25 DM", material: "Insumos", pintada: false, precio: 16700 },

  // ── POMEX TARQUINI ──
  { articulo: "Pomex Tarquini", medidas: "*3 DM", material: "Insumos", pintada: false, precio: 3000 },
  { articulo: "Pomex Tarquini", medidas: "*10 DM", material: "Insumos", pintada: false, precio: 7600 },
  { articulo: "Pomex Tarquini", medidas: "*25 DM", material: "Insumos", pintada: false, precio: 16200 },

  // ── TERRA FERTIL ──
  { articulo: "Terra Fértil Grow Mix", medidas: "20 LTS", material: "Insumos", pintada: false, precio: 13500 },
  { articulo: "Terra Fértil Grow Mix", medidas: "80 LTS", material: "Insumos", pintada: false, precio: 41600 },
  { articulo: "Terra Fértil Huerta", medidas: "50 LTS", material: "Insumos", pintada: false, precio: 25200 },

  // ── TIERRA EL JARDINERO ──
  { articulo: "Tierra El Jardinero", medidas: "*05 DM3", material: "Insumos", pintada: false, precio: 2500 },
  { articulo: "Tierra El Jardinero", medidas: "*10 DM3", material: "Insumos", pintada: false, precio: 3400 },
  { articulo: "Tierra El Jardinero", medidas: "*25 DM3", material: "Insumos", pintada: false, precio: 6000 },

  // ── TURBA ──
  { articulo: "Turba", medidas: "*4 DM", material: "Insumos", pintada: false, precio: 2300 },
  { articulo: "Turba", medidas: "*5 DM", material: "Insumos", pintada: false, precio: 5400 },
  { articulo: "Turba", medidas: "*10 DM", material: "Insumos", pintada: false, precio: 9850 },
  { articulo: "Turba", medidas: "*25 DM", material: "Insumos", pintada: false, precio: 13700 },

  // ── VERMICULITA ──
  { articulo: "Vermiculita", medidas: "*3 DM", material: "Insumos", pintada: false, precio: 7400 },
  { articulo: "Vermiculita", medidas: "*25 DM", material: "Insumos", pintada: false, precio: 38000 },

  // ── FERTILIZ (FERTIFOX) ──
  { articulo: "Fertiliz Antishock", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 14200 },
  { articulo: "Fertiliz Antishock", medidas: "*500 CC", material: "Insumos", pintada: false, precio: 52900 },
  { articulo: "Fertiliz", medidas: "*200 CC Flora/Folla/Potenx.", material: "Insumos", pintada: false, precio: 7900 },
  { articulo: "Fertiliz", medidas: "*1000 CC Flora/Folla/Potenx.", material: "Insumos", pintada: false, precio: 24700 },
  { articulo: "Fertiliz Especial Orquídeas", medidas: "*200 CC", material: "Insumos", pintada: false, precio: 12500 },
  { articulo: "Fertiliz Hormona", medidas: "*075 CC", material: "Insumos", pintada: false, precio: 13000 },
  { articulo: "Fertiliz Hierro Líq.", medidas: "*140 CC", material: "Insumos", pintada: false, precio: 14100 },
  { articulo: "Fertiliz Brillo Foliar", medidas: "Aerosol", material: "Insumos", pintada: false, precio: 19600 },

  // ── ECO FERTILIZANTES ──
  { articulo: "Acrecio Fertilizante", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 12400 },
  { articulo: "Megagreen Fertilizante Polvo", medidas: "*50 GMS", material: "Insumos", pintada: false, precio: 16600 },
  { articulo: "Polyamino Fertilizante", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 10600 },
  { articulo: "Fixa MZN Fertilizante", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 8950 },
  { articulo: "Fertilizante Cactus y Suculentas", medidas: "*30 CC", material: "Insumos", pintada: false, precio: 5050 },

  // ── JAPAN FERTIL ──
  { articulo: "Japón Fértil Abono Especial", medidas: "*120 CC", material: "Insumos", pintada: false, precio: 4800 },
  { articulo: "Japón Fértil Abono Especial", medidas: "*260 CC", material: "Insumos", pintada: false, precio: 6400 },
  { articulo: "Japón Fértil Bonsai-Cactus-Orquídea", medidas: "*260 CC", material: "Insumos", pintada: false, precio: 7500 },
  { articulo: "Japón Fértil Azulador Hortensias", medidas: "*300 GRS", material: "Insumos", pintada: false, precio: 6950 },
  { articulo: "Japón Fértil Lustre Vegetal", medidas: "Aerosol", material: "Insumos", pintada: false, precio: 15000 },
  { articulo: "Japón Fértil Lustre Vegetal", medidas: "*120 CC", material: "Insumos", pintada: false, precio: 4800 },
  { articulo: "Japón Fértil Cítricos", medidas: "*260 CC", material: "Insumos", pintada: false, precio: 6400 },
  { articulo: "Japón Fértil Hormona Polvo", medidas: "*025 GRS", material: "Insumos", pintada: false, precio: 8550 },

  // ── DIATOMEA (GREEN LEAF) ──
  { articulo: "Diatomea Green Leaf", medidas: "*200 CC", material: "Insumos", pintada: false, precio: 5600 },
  { articulo: "Diatomea Green Leaf", medidas: "*1 KG Pote", material: "Insumos", pintada: false, precio: 9200 },

  // ── DROP ──
  { articulo: "Drop Residual", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 4050 },
  { articulo: "Drop Derribante", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 5250 },
  { articulo: "Drop Pasta Raticida", medidas: "", material: "Insumos", pintada: false, precio: 6150 },

  // ── GELTEX ──
  { articulo: "Geltex Aerosol Insecticida", medidas: "*440 ML", material: "Insumos", pintada: false, precio: 12400 },
  { articulo: "Geltex Mata Cucaracha", medidas: "*6 GRS", material: "Insumos", pintada: false, precio: 4700 },
  { articulo: "Geltex Mata Cucaracha", medidas: "*12 GRS", material: "Insumos", pintada: false, precio: 7050 },
  { articulo: "Geltex Mata Cucaracha", medidas: "*60 GRS", material: "Insumos", pintada: false, precio: 19500 },
  { articulo: "Geltex Mata Hormigas", medidas: "*6 GRS", material: "Insumos", pintada: false, precio: 4800 },
  { articulo: "Geltex Mata Hormigas", medidas: "*12 GRS", material: "Insumos", pintada: false, precio: 7650 },
  { articulo: "Geltex Mata Hormigas", medidas: "*40 GRS", material: "Insumos", pintada: false, precio: 15700 },
  { articulo: "Geltex Raticida Bloques", medidas: "*100 GRS", material: "Insumos", pintada: false, precio: 5200 },
  { articulo: "Geltex Raticida Bloques", medidas: "*1 KG", material: "Insumos", pintada: false, precio: 39400 },

  // ── GLACOXAN ──
  { articulo: "Glacoxan Veloxan", medidas: "*060 CC Bio", material: "Insumos", pintada: false, precio: 7650 },
  { articulo: "Glacoxan Veloxan", medidas: "*250 CC", material: "Insumos", pintada: false, precio: 16300 },
  { articulo: "Glacoxan Termixan Cebo", medidas: "*50 GRS", material: "Insumos", pintada: false, precio: 2600 },
  { articulo: "Glacoxan Termixan Bloques", medidas: "*90 GRS", material: "Insumos", pintada: false, precio: 11000 },
  { articulo: "Glacoxan Termixan", medidas: "*1 KG Pote", material: "Insumos", pintada: false, precio: 17400 },

  // ── GRHESA ──
  { articulo: "Grhesa Babosil MP", medidas: "*100 GRS", material: "Insumos", pintada: false, precio: 2900 },
  { articulo: "Grhesa Babosil", medidas: "*250 GRS Pellet", material: "Insumos", pintada: false, precio: 4700 },
  { articulo: "Grhesa Babosil MP", medidas: "*250 GRS", material: "Insumos", pintada: false, precio: 5300 },
  { articulo: "Grhesa Babosil Super", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 7400 },
  { articulo: "Grhesa Aceite", medidas: "*200 CC", material: "Insumos", pintada: false, precio: 5650 },
  { articulo: "Grhesa Aceite", medidas: "*500 CC", material: "Insumos", pintada: false, precio: 9850 },
  { articulo: "Grhesa Bordeles", medidas: "*100 GRS", material: "Insumos", pintada: false, precio: 4100 },
  { articulo: "Grhesa Bordeles", medidas: "*250 GRS", material: "Insumos", pintada: false, precio: 7800 },

  // ── HORTAL ──
  { articulo: "Hortal Cebadera Raticida", medidas: "Caja", material: "Insumos", pintada: false, precio: 7600 },
  { articulo: "Hortal Funguicida", medidas: "Aerosol", material: "Insumos", pintada: false, precio: 8250 },
  { articulo: "Hortal Brillo Top", medidas: "Aerosol", material: "Insumos", pintada: false, precio: 9700 },

  // ── HUAGRO ──
  { articulo: "Huagro Fipromirex", medidas: "*250 GMS", material: "Insumos", pintada: false, precio: 3900 },
  { articulo: "Huagro Bolita Plus", medidas: "*100 GMS", material: "Insumos", pintada: false, precio: 3100 },
  { articulo: "Huagro Troya", medidas: "*100 GMS", material: "Insumos", pintada: false, precio: 2650 },
  { articulo: "Huagro Troya", medidas: "*250 GMS", material: "Insumos", pintada: false, precio: 5550 },
  { articulo: "Huagro Micro Pellets", medidas: "*100 GRS", material: "Insumos", pintada: false, precio: 3300 },
  { articulo: "Huagro Micro Pellets", medidas: "*1 KG", material: "Insumos", pintada: false, precio: 24700 },
  { articulo: "Huagro Hormixg", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 5350 },

  // ── MAMBORETA ──
  { articulo: "Mamboreta Kaotrina", medidas: "*15 ML", material: "Insumos", pintada: false, precio: 1800 },
  { articulo: "Mamboreta Kaotrina", medidas: "*60 CC", material: "Insumos", pintada: false, precio: 7650 },
  { articulo: "Mamboreta B+R", medidas: "*100 GRS", material: "Insumos", pintada: false, precio: 6950 },
  { articulo: "Mamboreta Bolita", medidas: "*100 GRS", material: "Insumos", pintada: false, precio: 9450 },
  { articulo: "Mamboreta Sistemico", medidas: "*030 CC", material: "Insumos", pintada: false, precio: 8100 },
  { articulo: "Mamboreta Aceite Oil85", medidas: "*100 CC", material: "Insumos", pintada: false, precio: 7400 },
  { articulo: "Mamboreta Aceite Oil85", medidas: "*200 CC", material: "Insumos", pintada: false, precio: 12300 },

  // ── MYRMEC ──
  { articulo: "Myrmec", medidas: "*100 GMS", material: "Insumos", pintada: false, precio: 2750 },
  { articulo: "Myrmec", medidas: "*200 GMS", material: "Insumos", pintada: false, precio: 4400 },
  { articulo: "Myrmec", medidas: "*500 GMS", material: "Insumos", pintada: false, precio: 8200 },
  { articulo: "Myrmec", medidas: "*750 GMS", material: "Insumos", pintada: false, precio: 10200 },
  { articulo: "Myrmec Babosa y Caracol", medidas: "*100 GMS", material: "Insumos", pintada: false, precio: 3500 },
  { articulo: "Myrmec Bicho Bolita", medidas: "*100 GMS", material: "Insumos", pintada: false, precio: 2950 },

  // ── PULVERIZADORES ──
  { articulo: "Pulverizador", medidas: "*250 CC", material: "Insumos", pintada: false, precio: 1300 },
  { articulo: "Pulverizador", medidas: "*1¼ Lt Italiano", material: "Insumos", pintada: false, precio: 3050 },
  { articulo: "Pulverizador Berta Impulso", medidas: "Plástico", material: "Insumos", pintada: false, precio: 6000 },
  { articulo: "Pulverizador Berta", medidas: "Bronce para Botella", material: "Insumos", pintada: false, precio: 22300 },
  { articulo: "Pulverizador Berta Bomba", medidas: "1 Lt", material: "Insumos", pintada: false, precio: 13300 },
  { articulo: "Pulverizador Berta Bomba", medidas: "2 Lt", material: "Insumos", pintada: false, precio: 15200 },
  { articulo: "Pulverizador Mochila", medidas: "5 Lt", material: "Insumos", pintada: false, precio: 48200 },
  { articulo: "Pulverizador Mochila", medidas: "8 Lt", material: "Insumos", pintada: false, precio: 60900 },
  { articulo: "Pulverizador Mochila", medidas: "16 Lt", material: "Insumos", pintada: false, precio: 108400 },

  // ── TUTORES DE MUSGO ──
  { articulo: "Tutor de Musgo", medidas: "*040 CM", material: "Insumos", pintada: false, precio: 3300 },
  { articulo: "Tutor de Musgo", medidas: "*060 CM", material: "Insumos", pintada: false, precio: 4300 },
  { articulo: "Tutor de Musgo", medidas: "*080 CM", material: "Insumos", pintada: false, precio: 5700 },
  { articulo: "Tutor de Musgo", medidas: "*100 CM", material: "Insumos", pintada: false, precio: 6550 },
  { articulo: "Tutor de Musgo", medidas: "*120 CM", material: "Insumos", pintada: false, precio: 8250 },
  { articulo: "Tutor de Musgo", medidas: "*140 CM", material: "Insumos", pintada: false, precio: 10000 },
  { articulo: "Tutor de Musgo", medidas: "*160 CM", material: "Insumos", pintada: false, precio: 11400 },


  // ── T.A. PLASTIC ──
  { articulo: "Maceta Diamante", medidas: "Nº15", material: "Plástico", pintada: false, precio: 2250 },
  { articulo: "Maceta Diamante", medidas: "Nº19", material: "Plástico", pintada: false, precio: 3350 },
  { articulo: "Maceta Diamante", medidas: "Nº25", material: "Plástico", pintada: false, precio: 7300 },
  { articulo: "Maceta Facetada", medidas: "Nº16", material: "Plástico", pintada: false, precio: 3500 },
  { articulo: "Maceta Facetada", medidas: "Nº20", material: "Plástico", pintada: false, precio: 5700 },
  { articulo: "Maceta Facetada", medidas: "Nº24", material: "Plástico", pintada: false, precio: 9900 },
  { articulo: "Maceta Facetada", medidas: "Nº29", material: "Plástico", pintada: false, precio: 14800 },
  { articulo: "Maceta Facetada c/Rueda", medidas: "Nº41", material: "Plástico", pintada: false, precio: 26800 },
  { articulo: "Maceta Milan", medidas: "Nº16", material: "Plástico", pintada: false, precio: 3550 },
  { articulo: "Maceta Milan", medidas: "Nº20", material: "Plástico", pintada: false, precio: 6100 },
  { articulo: "Maceta Milan", medidas: "Nº25", material: "Plástico", pintada: false, precio: 11800 },
  { articulo: "Maceta Venecia", medidas: "Nº17", material: "Plástico", pintada: false, precio: 4450 },
  { articulo: "Maceta Paris c/Raya", medidas: "Nº18", material: "Plástico", pintada: false, precio: 3500 },
  { articulo: "Maceta Paris c/Raya", medidas: "Nº22", material: "Plástico", pintada: false, precio: 6350 },
  { articulo: "Maceta Paris c/Raya", medidas: "Nº27", material: "Plástico", pintada: false, precio: 10400 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº16", material: "Plástico", pintada: false, precio: 610 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº18", material: "Plástico", pintada: false, precio: 790 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº20", material: "Plástico", pintada: false, precio: 1150 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº22", material: "Plástico", pintada: false, precio: 1350 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº24", material: "Plástico", pintada: false, precio: 1700 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº26", material: "Plástico", pintada: false, precio: 1900 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº28", material: "Plástico", pintada: false, precio: 2400 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº32", material: "Plástico", pintada: false, precio: 2850 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº36", material: "Plástico", pintada: false, precio: 3800 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº40", material: "Plástico", pintada: false, precio: 5400 },
  { articulo: "Plato Redondo T.A.", medidas: "Nº45", material: "Plástico", pintada: false, precio: 7500 },
  { articulo: "Redonda Premium", medidas: "Nº8", material: "Plástico", pintada: false, precio: 1050 },
  { articulo: "Redonda Premium", medidas: "Nº12", material: "Plástico", pintada: false, precio: 1950 },
  { articulo: "Redonda Premium", medidas: "Nº16", material: "Plástico", pintada: false, precio: 3250 },
  { articulo: "Redonda Premium", medidas: "Nº18", material: "Plástico", pintada: false, precio: 4150 },
  { articulo: "Redonda Premium", medidas: "Nº22", material: "Plástico", pintada: false, precio: 7600 },
  { articulo: "Redonda Premium", medidas: "Nº27", material: "Plástico", pintada: false, precio: 14100 },
  { articulo: "Redonda Premium", medidas: "Nº35", material: "Plástico", pintada: false, precio: 25800 },
  { articulo: "Premium Cónica", medidas: "Nº8", material: "Plástico", pintada: false, precio: 860 },
  { articulo: "Premium Cónica", medidas: "Nº12", material: "Plástico", pintada: false, precio: 1700 },
  { articulo: "Premium Cónica", medidas: "Nº16", material: "Plástico", pintada: false, precio: 3450 },
  { articulo: "Premium Cónica", medidas: "Nº20", material: "Plástico", pintada: false, precio: 5500 },


  // ── ROTOMOLDEADO MD (Matías H. Diner) ──
  { articulo: "Cubo MD", medidas: "20×20", material: "Rotomoldeado", pintada: false, precio: 9350 },
  { articulo: "Cubo MD", medidas: "30×30", material: "Rotomoldeado", pintada: false, precio: 26300 },
  { articulo: "Cilindro MD", medidas: "30×30", material: "Rotomoldeado", pintada: false, precio: 19600 },
  { articulo: "Cilindro MD", medidas: "40×40", material: "Rotomoldeado", pintada: false, precio: 41000 },
  { articulo: "Cilindro MD", medidas: "30×40", material: "Rotomoldeado", pintada: false, precio: 28000 },
  { articulo: "Cilindro MD", medidas: "30×50", material: "Rotomoldeado", pintada: false, precio: 31000 },
  { articulo: "Jardinera MD", medidas: "60×20×30", material: "Rotomoldeado", pintada: false, precio: 36000 },
  { articulo: "Jardinera MD", medidas: "80×20×20", material: "Rotomoldeado", pintada: false, precio: 34600 },
  { articulo: "Jardinera MD", medidas: "80×20×30", material: "Rotomoldeado", pintada: false, precio: 48300 },
  { articulo: "Jardinera Curva MD", medidas: "", material: "Rotomoldeado", pintada: false, precio: 30600 },
  { articulo: "1/2 Cilindro MD", medidas: "", material: "Rotomoldeado", pintada: false, precio: 33000 },
  { articulo: "Jardinera en S MD", medidas: "58×28", material: "Rotomoldeado", pintada: false, precio: 39900 },
  { articulo: "Jardinera Cajón MD", medidas: "50×30×28", material: "Rotomoldeado", pintada: false, precio: 39800 },
  { articulo: "Piramidal MD", medidas: "58×28", material: "Rotomoldeado", pintada: false, precio: 31000 },
  { articulo: "Cono MD", medidas: "58×28", material: "Rotomoldeado", pintada: false, precio: 31000 },
  { articulo: "Cono MD", medidas: "43×24", material: "Rotomoldeado", pintada: false, precio: 20500 },
  { articulo: "Triángulo MD", medidas: "40l×21h", material: "Rotomoldeado", pintada: false, precio: 25000 },
  { articulo: "Prisma MD", medidas: "15×15×30", material: "Rotomoldeado", pintada: false, precio: 10200 },
  { articulo: "Gota MD", medidas: "20 alto", material: "Rotomoldeado", pintada: false, precio: 6800 },


  // ── SOBRETIERRA (Cerámica) ──
  { articulo: "Media Caña", medidas: "N°1 (20h×20d×12b)", material: "Cerámica", pintada: false, precio: 35500 },
  { articulo: "Media Caña", medidas: "N°2 (30h×29d×18b)", material: "Cerámica", pintada: false, precio: 64700 },
  { articulo: "Media Caña", medidas: "N°3 (38h×38d×25b)", material: "Cerámica", pintada: false, precio: 127100 },
  { articulo: "Oriental Blanca", medidas: "N°1 (20h×18d×9b)", material: "Cerámica", pintada: false, precio: 35500 },
  { articulo: "Oriental Blanca", medidas: "N°2 (30h×27d×14b)", material: "Cerámica", pintada: false, precio: 64700 },
  { articulo: "Oriental Blanca", medidas: "N°3 (42h×31d×19b)", material: "Cerámica", pintada: false, precio: 127100 },
  { articulo: "Oriental Color", medidas: "N°1 (20h×18d×9b)", material: "Cerámica", pintada: false, precio: 44600 },
  { articulo: "Oriental Color", medidas: "N°2 (30h×27d×14b)", material: "Cerámica", pintada: false, precio: 85200 },
  { articulo: "Oriental Color", medidas: "N°3 (42h×31d×19b)", material: "Cerámica", pintada: false, precio: 164400 },
  { articulo: "Riñon", medidas: "(32h×35d×17b)", material: "Cerámica", pintada: false, precio: 152900 },
  { articulo: "Panzón", medidas: "(35h×24d×18b)", material: "Cerámica", pintada: false, precio: 127100 },
  { articulo: "Gotas Góticas", medidas: "N°1 (27h×22d×16b)", material: "Cerámica", pintada: false, precio: 91900 },
  { articulo: "Gotas Góticas", medidas: "N°2 (38h×30d×18b)", material: "Cerámica", pintada: false, precio: 136300 },
  { articulo: "Vaso Rayado", medidas: "(44h×39d×23b)", material: "Cerámica", pintada: false, precio: 194500 },
  { articulo: "Tronquito", medidas: "N°1 (14h×15d×13b)", material: "Cerámica", pintada: false, precio: 37400 },
  { articulo: "Tronquito", medidas: "N°2 (19h×19d×16b)", material: "Cerámica", pintada: false, precio: 53400 },
  { articulo: "Coco", medidas: "N°1 (10h×11d×8b)", material: "Cerámica", pintada: false, precio: 33600 },
  { articulo: "Coco", medidas: "N°2 (14h×14d×11b)", material: "Cerámica", pintada: false, precio: 51600 },
  { articulo: "Coco", medidas: "N°3 (18h×17d×14b)", material: "Cerámica", pintada: false, precio: 92100 },
  { articulo: "Coco", medidas: "N°4 (24h×22d×18b)", material: "Cerámica", pintada: false, precio: 170200 },
  { articulo: "Coco", medidas: "N°5 (32h×28d×28b)", material: "Cerámica", pintada: false, precio: 268700 },
  { articulo: "Facetadas", medidas: "(10h×8d×6b)", material: "Cerámica", pintada: false, precio: 17400 },
  { articulo: "Maceta Curva", medidas: "N°6 (60h×40d)", material: "Cerámica", pintada: false, precio: 568300 },
  { articulo: "Maceta Curva", medidas: "N°7 (70h×45d)", material: "Cerámica", pintada: false, precio: 782100 },
  { articulo: "Maceta Curva", medidas: "N°8 (80h×50d)", material: "Cerámica", pintada: false, precio: 1305600 },
  { articulo: "Paila c/Franja Color", medidas: "N°1 (14h×34d×14b)", material: "Cerámica", pintada: false, precio: 77900 },
  { articulo: "Paila c/Franja Color", medidas: "N°2 (16h×40d×15b)", material: "Cerámica", pintada: false, precio: 91900 },
  { articulo: "Maceta Sin Esmalte", medidas: "N°1", material: "Cerámica", pintada: false, precio: 15900 },
  { articulo: "Maceta Sin Esmalte", medidas: "N°2", material: "Cerámica", pintada: false, precio: 21300 },
  { articulo: "Maceta Sin Esmalte", medidas: "N°3", material: "Cerámica", pintada: false, precio: 31900 },
  { articulo: "Maceta Sin Esmalte", medidas: "N°4", material: "Cerámica", pintada: false, precio: 83900 },
  { articulo: "Maceta Sin Esmalte", medidas: "N°5", material: "Cerámica", pintada: false, precio: 163400 },
  { articulo: "Maceta Esmaltada", medidas: "N°1", material: "Cerámica", pintada: false, precio: 19000 },
  { articulo: "Maceta Esmaltada", medidas: "N°2", material: "Cerámica", pintada: false, precio: 33500 },
  { articulo: "Maceta Esmaltada", medidas: "N°3", material: "Cerámica", pintada: false, precio: 47800 },
  { articulo: "Maceta Esmaltada", medidas: "N°4", material: "Cerámica", pintada: false, precio: 108100 },
  { articulo: "Maceta Esmaltada", medidas: "N°5", material: "Cerámica", pintada: false, precio: 212600 },
  { articulo: "Plato Sin Esmalte", medidas: "N°1", material: "Cerámica", pintada: false, precio: 6300 },
  { articulo: "Plato Sin Esmalte", medidas: "N°2", material: "Cerámica", pintada: false, precio: 12100 },
  { articulo: "Plato Sin Esmalte", medidas: "N°3", material: "Cerámica", pintada: false, precio: 18200 },
  { articulo: "Plato Sin Esmalte", medidas: "N°4", material: "Cerámica", pintada: false, precio: 28500 },
  { articulo: "Plato Sin Esmalte", medidas: "N°5", material: "Cerámica", pintada: false, precio: 48900 },
  { articulo: "Plato Sin Esmalte", medidas: "N°6", material: "Cerámica", pintada: false, precio: 72800 },
  { articulo: "Plato Esmaltado", medidas: "N°1", material: "Cerámica", pintada: false, precio: 9000 },
  { articulo: "Plato Esmaltado", medidas: "N°2", material: "Cerámica", pintada: false, precio: 16800 },
  { articulo: "Plato Esmaltado", medidas: "N°3", material: "Cerámica", pintada: false, precio: 25100 },
  { articulo: "Plato Esmaltado", medidas: "N°4", material: "Cerámica", pintada: false, precio: 39800 },
  { articulo: "Plato Esmaltado", medidas: "N°5", material: "Cerámica", pintada: false, precio: 68600 },
  { articulo: "Plato Esmaltado", medidas: "N°6", material: "Cerámica", pintada: false, precio: 102600 },
  { articulo: "Embudo Grande Rayado", medidas: "(31h×36d×6b)", material: "Cerámica", pintada: false, precio: 106000 },
  { articulo: "Embudo Chico", medidas: "(31h×28d×7b)", material: "Cerámica", pintada: false, precio: 71600 },
  { articulo: "Griega", medidas: "(27h×21d×4b)", material: "Cerámica", pintada: false, precio: 71600 },
  { articulo: "Embudo Grande Color", medidas: "(31h×36d×6b)", material: "Cerámica", pintada: false, precio: 133700 },
  { articulo: "Embudo Chico Color", medidas: "(31h×28d×7b)", material: "Cerámica", pintada: false, precio: 93000 },
  { articulo: "Griega Color", medidas: "(27h×21d×4b)", material: "Cerámica", pintada: false, precio: 93000 },
  { articulo: "Farol", medidas: "N°1 (12 cm)", material: "Cerámica", pintada: false, precio: 24100 },
  { articulo: "Farol", medidas: "N°2 (16 cm)", material: "Cerámica", pintada: false, precio: 38300 },
  { articulo: "Farol", medidas: "N°3 (22 cm)", material: "Cerámica", pintada: false, precio: 59800 },
  { articulo: "Palenque", medidas: "Baja (5h×29l×19a)", material: "Cerámica", pintada: false, precio: 44200 },
  { articulo: "Palenque", medidas: "Alta (9h×32l×21a)", material: "Cerámica", pintada: false, precio: 58300 },
  { articulo: "Yucatán", medidas: "Baja (6h×40l×24a)", material: "Cerámica", pintada: false, precio: 48700 },
  { articulo: "Yucatán", medidas: "Alta (12h×43l×26a)", material: "Cerámica", pintada: false, precio: 70200 },
  { articulo: "Cuadrada", medidas: "N°1 (6h×22d×12b)", material: "Cerámica", pintada: false, precio: 34600 },
  { articulo: "Cuadrada", medidas: "N°2 (8h×28d×18b)", material: "Cerámica", pintada: false, precio: 45000 },
  { articulo: "Kokedama", medidas: "Chica (10h×15d×5b)", material: "Cerámica", pintada: false, precio: 26800 },
  { articulo: "Kokedama", medidas: "Grande (15h×23d×11b)", material: "Cerámica", pintada: false, precio: 45000 },
];
