window.LYL_MIN = [
  // BARRO — BLUM
  { articulo: "FRUTILLERA 60", medidas: "", material: "Barro", pintada: false, precio: 174920 },
  { articulo: "MAC. COMUN Nº 16 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 6400 },
  { articulo: "MAC. COMUN Nº 18 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 8750 },
  { articulo: "PORTEÑA Nº20", medidas: "", material: "Barro", pintada: false, precio: 4750 },
  { articulo: "PORTEÑA Nº45", medidas: "", material: "Barro", pintada: false, precio: 49510 },
  { articulo: "CILINDRO N26 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 19030 },
  { articulo: "CILINDRO N22 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 12970 },
  { articulo: "CILINDRO N18 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 8380 },
  { articulo: "CILINDRO N14 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 4640 },
  { articulo: "CILINDRO N12 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 1960 },
  { articulo: "BOMBA N23 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 14390 },
  { articulo: "MAC PREMIUM N22 GRAFITO", medidas: "", material: "Barro", pintada: true, precio: 6900 },
  { articulo: "CILINDRO N18 ESMALTADO", medidas: "", material: "Barro", pintada: true, precio: 12980 },
  { articulo: "MAC. COMUN N14 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 5400 },
  { articulo: "CILINDRO ESMALTADO N12", medidas: "", material: "Barro", pintada: true, precio: 4540 },
  { articulo: "CILINDRO ESMALTADO N14", medidas: "", material: "Barro", pintada: true, precio: 8770 },
  { articulo: "MAC PREMIUM ESMALTADA N22", medidas: "", material: "Barro", pintada: true, precio: 13920 },
  { articulo: "ICONO N12", medidas: "", material: "Barro", pintada: false, precio: 1770 },
  { articulo: "ICONO N14", medidas: "", material: "Barro", pintada: false, precio: 1860 },
  { articulo: "ICONO N16", medidas: "", material: "Barro", pintada: false, precio: 2780 },
  { articulo: "ICONO N18", medidas: "", material: "Barro", pintada: false, precio: 3370 },
  { articulo: "ICONO N20", medidas: "", material: "Barro", pintada: false, precio: 4130 },
  { articulo: "CILINDRO ESMALTADO N22", medidas: "", material: "Barro", pintada: true, precio: 25850 },
  { articulo: "AMERICANA Nº23", medidas: "", material: "Barro", pintada: false, precio: 8380 },
  { articulo: "AMERICANA Nº29", medidas: "", material: "Barro", pintada: false, precio: 15550 },
  { articulo: "AMERICANA Nº36", medidas: "", material: "Barro", pintada: false, precio: 25140 },
  { articulo: "BALCONERA Nº45", medidas: "", material: "Barro", pintada: false, precio: 17000 },
  { articulo: "BOLS COLGANTE N24", medidas: "", material: "Barro", pintada: false, precio: 7010 },
  { articulo: "BOLS Nº13", medidas: "", material: "Barro", pintada: false, precio: 2940 },
  { articulo: "BOLS Nº17", medidas: "", material: "Barro", pintada: false, precio: 4560 },
  { articulo: "BOLS Nº21", medidas: "", material: "Barro", pintada: false, precio: 7210 },
  { articulo: "BOLS Nº25", medidas: "", material: "Barro", pintada: false, precio: 9850 },
  { articulo: "BOMBA Nº08", medidas: "", material: "Barro", pintada: false, precio: 3420 },
  { articulo: "BOMBA Nº14", medidas: "", material: "Barro", pintada: false, precio: 6790 },
  { articulo: "BOMBA Nº16", medidas: "", material: "Barro", pintada: false, precio: 8450 },
  { articulo: "BOMBA Nº19", medidas: "", material: "Barro", pintada: false, precio: 10790 },
  { articulo: "BOMBA Nº23", medidas: "", material: "Barro", pintada: false, precio: 16620 },
  { articulo: "BOMBA Nº35", medidas: "", material: "Barro", pintada: false, precio: 40580 },
  { articulo: "BOMBA Nº40", medidas: "", material: "Barro", pintada: false, precio: 60250 },
  { articulo: "BOMBA Nº50", medidas: "", material: "Barro", pintada: false, precio: 91290 },
  { articulo: "CILINDRO C/BORDE Nº15", medidas: "", material: "Barro", pintada: false, precio: 3860 },
  { articulo: "CILINDRO C/BORDE Nº19", medidas: "", material: "Barro", pintada: false, precio: 5740 },
  { articulo: "CILINDRO C/BORDE Nº24", medidas: "", material: "Barro", pintada: false, precio: 9240 },
  { articulo: "CILINDRO C/BORDE Nº30", medidas: "", material: "Barro", pintada: false, precio: 19490 },
  { articulo: "CILINDRO C/BORDE Nº38", medidas: "", material: "Barro", pintada: false, precio: 34820 },
  { articulo: "CILINDRO C/BORDE Nº48", medidas: "", material: "Barro", pintada: false, precio: 79250 },
  { articulo: "CILINDRO Nº12", medidas: "", material: "Barro", pintada: false, precio: 2260 },
  { articulo: "CILINDRO Nº14", medidas: "", material: "Barro", pintada: false, precio: 5360 },
  { articulo: "CILINDRO Nº18", medidas: "", material: "Barro", pintada: false, precio: 9680 },
  { articulo: "CILINDRO Nº22", medidas: "", material: "Barro", pintada: false, precio: 14970 },
  { articulo: "CILINDRO Nº26", medidas: "", material: "Barro", pintada: false, precio: 21960 },
  { articulo: "CILINDRO Nº30", medidas: "", material: "Barro", pintada: false, precio: 32320 },
  { articulo: "COLGADERA Nº25", medidas: "", material: "Barro", pintada: false, precio: 10390 },
  { articulo: "COLGADERA Nº30", medidas: "", material: "Barro", pintada: false, precio: 18120 },
  { articulo: "CONO 31", medidas: "", material: "Barro", pintada: false, precio: 10280 },
  { articulo: "CONO 40", medidas: "", material: "Barro", pintada: false, precio: 20390 },
  { articulo: "CONO 48", medidas: "", material: "Barro", pintada: false, precio: 31210 },
  { articulo: "CONO 55 CM", medidas: "", material: "Barro", pintada: false, precio: 52730 },
  { articulo: "FESTONEADA Nº08", medidas: "", material: "Barro", pintada: false, precio: 3360 },
  { articulo: "FESTONEADA Nº10", medidas: "", material: "Barro", pintada: false, precio: 4420 },
  { articulo: "FESTONEADA Nº16", medidas: "", material: "Barro", pintada: false, precio: 8210 },
  { articulo: "FESTONEADA Nº19", medidas: "", material: "Barro", pintada: false, precio: 11330 },
  { articulo: "FESTONEADA Nº24", medidas: "", material: "Barro", pintada: false, precio: 13020 },
  { articulo: "FESTONEADA Nº30", medidas: "", material: "Barro", pintada: false, precio: 31420 },
  { articulo: "FESTONEADA Nº45", medidas: "", material: "Barro", pintada: false, precio: 92230 },
  { articulo: "FESTONEADA Nº58", medidas: "", material: "Barro", pintada: false, precio: 138360 },
  { articulo: "FRUTILLERA 40", medidas: "", material: "Barro", pintada: false, precio: 87460 },
  { articulo: "ITALIANA Nº14", medidas: "", material: "Barro", pintada: false, precio: 2630 },
  { articulo: "ITALIANA Nº16", medidas: "", material: "Barro", pintada: false, precio: 3110 },
  { articulo: "ITALIANA Nº18", medidas: "", material: "Barro", pintada: false, precio: 4240 },
  { articulo: "ITALIANA Nº20", medidas: "", material: "Barro", pintada: false, precio: 5610 },
  { articulo: "ITALIANA Nº22", medidas: "", material: "Barro", pintada: false, precio: 7870 },
  { articulo: "ITALIANA Nº24", medidas: "", material: "Barro", pintada: false, precio: 10210 },
  { articulo: "ITALIANA Nº26", medidas: "", material: "Barro", pintada: false, precio: 13510 },
  { articulo: "ITALIANA Nº30", medidas: "", material: "Barro", pintada: false, precio: 17030 },
  { articulo: "ITALIANA Nº35", medidas: "", material: "Barro", pintada: false, precio: 24760 },
  { articulo: "ITALIANA Nº40", medidas: "", material: "Barro", pintada: false, precio: 32140 },
  { articulo: "ITALIANA Nº48", medidas: "", material: "Barro", pintada: false, precio: 53540 },
  { articulo: "ITALIANA Nº52", medidas: "", material: "Barro", pintada: false, precio: 77780 },
  { articulo: "JARD. C.ROMA Nº31", medidas: "", material: "Barro", pintada: false, precio: 14630 },
  { articulo: "JARD. C.ROMA Nº52", medidas: "", material: "Barro", pintada: false, precio: 37680 },
  { articulo: "JARDINERA Nº30", medidas: "", material: "Barro", pintada: false, precio: 13330 },
  { articulo: "JARDINERA Nº40", medidas: "", material: "Barro", pintada: false, precio: 24380 },
  { articulo: "JARDINERA Nº50", medidas: "", material: "Barro", pintada: false, precio: 35170 },
  { articulo: "LEBRILLO Nº22", medidas: "", material: "Barro", pintada: false, precio: 6920 },
  { articulo: "LEBRILLO Nº26", medidas: "", material: "Barro", pintada: false, precio: 9740 },
  { articulo: "LEBRILLO Nº30", medidas: "", material: "Barro", pintada: false, precio: 13380 },
  { articulo: "LEBRILLO Nº34", medidas: "", material: "Barro", pintada: false, precio: 16710 },
  { articulo: "LEBRILLO Nº38", medidas: "", material: "Barro", pintada: false, precio: 20550 },
  { articulo: "LEBRILLO Nº45", medidas: "", material: "Barro", pintada: false, precio: 33530 },
  { articulo: "LEBRILLO Nº52", medidas: "", material: "Barro", pintada: false, precio: 49910 },
  { articulo: "MAC. COMUN Nº 04", medidas: "", material: "Barro", pintada: false, precio: 1080 },
  { articulo: "MAC. COMUN Nº 05", medidas: "", material: "Barro", pintada: false, precio: 1100 },
  { articulo: "MAC. COMUN Nº 07", medidas: "", material: "Barro", pintada: false, precio: 1390 },
  { articulo: "MAC. COMUN Nº 08", medidas: "", material: "Barro", pintada: false, precio: 1600 },
  { articulo: "MAC. COMUN Nº 10", medidas: "", material: "Barro", pintada: false, precio: 1650 },
  { articulo: "MAC. COMUN Nº 12", medidas: "", material: "Barro", pintada: false, precio: 1850 },
  { articulo: "MAC. COMUN Nº 14", medidas: "", material: "Barro", pintada: false, precio: 2200 },
  { articulo: "MAC. COMUN Nº 16", medidas: "", material: "Barro", pintada: false, precio: 2890 },
  { articulo: "MAC. COMUN Nº 18", medidas: "", material: "Barro", pintada: false, precio: 4020 },
  { articulo: "MAC. COMUN Nº 20", medidas: "", material: "Barro", pintada: false, precio: 4960 },
  { articulo: "MAC. COMUN Nº 22", medidas: "", material: "Barro", pintada: false, precio: 7970 },
  { articulo: "MAC. COMUN Nº 24", medidas: "", material: "Barro", pintada: false, precio: 9260 },
  { articulo: "MAC. COMUN Nº 26", medidas: "", material: "Barro", pintada: false, precio: 11460 },
  { articulo: "MAC. COMUN Nº 28", medidas: "", material: "Barro", pintada: false, precio: 13120 },
  { articulo: "MAC. COMUN Nº 30", medidas: "", material: "Barro", pintada: false, precio: 15530 },
  { articulo: "MAC. COMUN Nº 35", medidas: "", material: "Barro", pintada: false, precio: 20390 },
  { articulo: "MAC. COMUN Nº 40", medidas: "", material: "Barro", pintada: false, precio: 32010 },
  { articulo: "MAC. COMUN Nº 48", medidas: "", material: "Barro", pintada: false, precio: 48850 },
  { articulo: "MAC. COMUN Nº 52", medidas: "", material: "Barro", pintada: false, precio: 76350 },
  { articulo: "AGUSTINIANA Nº20", medidas: "", material: "Barro", pintada: false, precio: 10260 },
  { articulo: "AGUSTINIANA Nº27", medidas: "", material: "Barro", pintada: false, precio: 23050 },
  { articulo: "AGUSTINIANA Nº34", medidas: "", material: "Barro", pintada: false, precio: 44870 },
  { articulo: "AGUSTINIANA Nº40", medidas: "", material: "Barro", pintada: false, precio: 71350 },
  { articulo: "AGUSTINIANA Nº60", medidas: "", material: "Barro", pintada: false, precio: 136680 },
  { articulo: "NIDO DE PALOMA Nº24", medidas: "", material: "Barro", pintada: false, precio: 9150 },
  { articulo: "PAILA Nº35", medidas: "", material: "Barro", pintada: false, precio: 15670 },
  { articulo: "PAILA Nº48", medidas: "", material: "Barro", pintada: false, precio: 33680 },
  { articulo: "PAILA Nº62", medidas: "", material: "Barro", pintada: false, precio: 60130 },
  { articulo: "PIE DE MACETA Nº45", medidas: "", material: "Barro", pintada: false, precio: 1780 },
  { articulo: "PIE DE MACETA Nº90", medidas: "", material: "Barro", pintada: false, precio: 2340 },
  { articulo: "PLATO Nº 08", medidas: "", material: "Barro", pintada: false, precio: 1480 },
  { articulo: "PLATO Nº 10", medidas: "", material: "Barro", pintada: false, precio: 1600 },
  { articulo: "PLATO Nº 12", medidas: "", material: "Barro", pintada: false, precio: 1680 },
  { articulo: "PLATO Nº 14", medidas: "", material: "Barro", pintada: false, precio: 2070 },
  { articulo: "PLATO Nº 16", medidas: "", material: "Barro", pintada: false, precio: 2690 },
  { articulo: "PLATO Nº 18", medidas: "", material: "Barro", pintada: false, precio: 3300 },
  { articulo: "PLATO Nº 20", medidas: "", material: "Barro", pintada: false, precio: 4070 },
  { articulo: "PLATO Nº 22", medidas: "", material: "Barro", pintada: false, precio: 6300 },
  { articulo: "PLATO Nº 24", medidas: "", material: "Barro", pintada: false, precio: 8290 },
  { articulo: "PLATO Nº 26", medidas: "", material: "Barro", pintada: false, precio: 10270 },
  { articulo: "PLATO Nº 28", medidas: "", material: "Barro", pintada: false, precio: 12410 },
  { articulo: "PLATO Nº 30", medidas: "", material: "Barro", pintada: false, precio: 15010 },
  { articulo: "PLATO Nº 35", medidas: "", material: "Barro", pintada: false, precio: 17570 },
  { articulo: "PLATO Nº 40", medidas: "", material: "Barro", pintada: false, precio: 21270 },
  { articulo: "PLATO Nº 45", medidas: "", material: "Barro", pintada: false, precio: 29640 },
  { articulo: "PLATO Nº 52", medidas: "", material: "Barro", pintada: false, precio: 36760 },
  { articulo: "TERRINA Nº10", medidas: "", material: "Barro", pintada: false, precio: 2560 },
  { articulo: "TERRINA Nº12", medidas: "", material: "Barro", pintada: false, precio: 2870 },
  { articulo: "TERRINA Nº14", medidas: "", material: "Barro", pintada: false, precio: 3090 },
  { articulo: "TERRINA Nº22", medidas: "", material: "Barro", pintada: false, precio: 7650 },
  { articulo: "TERRINA Nº24", medidas: "", material: "Barro", pintada: false, precio: 10040 },
  { articulo: "TERRINA Nº27", medidas: "", material: "Barro", pintada: false, precio: 14800 },
  { articulo: "MAC. COMUN N*6", medidas: "", material: "Barro", pintada: false, precio: 1240 },
  { articulo: "MAC. PREMIUM N22", medidas: "", material: "Barro", pintada: false, precio: 7970 },
  { articulo: "BOMBA Nº30", medidas: "", material: "Barro", pintada: false, precio: 29990 },
  { articulo: "MAC. COMUN Nº 10 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 3560 },
  { articulo: "MAC. COMUN Nº 12 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 4150 },
  { articulo: "MAC. COMUN Nº 22 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 14050 },
  { articulo: "MAC. COMUN Nº 08 PINTADA", medidas: "", material: "Barro", pintada: true, precio: 2990 },
  { articulo: "ICONO Nº 8", medidas: "", material: "Barro", pintada: false, precio: 1600 },
  { articulo: "ICONO Nº 10", medidas: "", material: "Barro", pintada: false, precio: 1650 },
  { articulo: "ICONO Nº 8  PINTADA", medidas: "", material: "Barro", pintada: true, precio: 2850 },
  { articulo: "ICONO Nº 10  PINTADA", medidas: "", material: "Barro", pintada: true, precio: 3390 },
  // BARRO ARTESANAL — CACHARROS
  { articulo: "Nº3 (*) 20CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 14950 },
  { articulo: "MATERON GIGANTE 10CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 4370 },
  { articulo: "Nº1  (*) 16CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 7240 },
  { articulo: "TIRAS *1 DOC. DEDAL 2CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 13800 },
  { articulo: "PREMIUM N22", medidas: "", material: "Barro Artesanal", pintada: false, precio: 12190 },
  { articulo: "PREMIUM N18", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9090 },
  { articulo: "1/2 PARED", medidas: "", material: "Barro Artesanal", pintada: false, precio: 13800 },
  { articulo: "BANDEJA OVAL GRANDE 30CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 22730 },
  { articulo: "TIRAS *1 DOC. SARTA 5CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 18400 },
  { articulo: "OLLA CHICA CUADRADA Y REDONDA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 22730 },
  { articulo: "OLLA MEDIANA REDONDA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 30300 },
  { articulo: "OLLA EXTRA GRANDE OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 41400 },
  { articulo: "SARTEN C/TAPA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 30300 },
  { articulo: "PAVA OFERTA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 20700 },
  { articulo: "CASUELA REDONDA 16CM X 7CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9660 },
  { articulo: "CASUELA REDONDO 14CM X 5CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 9660 },
  { articulo: "VOLCADO 2  26CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 29320 },
  { articulo: "VOLCADO GIGANTE SUPER 40CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 75900 },
  { articulo: "MATERA EXTRA GRANDE NUEVA 13CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 6040 },
  { articulo: "CHANCHITOS CH.", medidas: "", material: "Barro Artesanal", pintada: false, precio: 10100 },
  { articulo: "CHANCHITOS GRANDE", medidas: "", material: "Barro Artesanal", pintada: false, precio: 14140 },
  { articulo: "TIRAS *1 DOC. OJAL 3CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 20700 },
  { articulo: "MATERA SARTA 8CM BOCA 6CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 2420 },
  { articulo: "N4 30CM BOCA C/MANIJA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 37260 },
  { articulo: "JARRAS GRANDE 24CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 11110 },
  { articulo: "BANDEJA OVAL CHICA 18CM X 6CM ALTO", medidas: "", material: "Barro Artesanal", pintada: false, precio: 12070 },
  { articulo: "MATERA MEDIANA 6CM", medidas: "", material: "Barro Artesanal", pintada: false, precio: 1440 },
  { articulo: "JARRA CHICA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 7580 },
  { articulo: "GIGANTE SUPER", medidas: "", material: "Barro Artesanal", pintada: false, precio: 29320 },
  { articulo: "VOLCADO 1 30CM BOCA", medidas: "", material: "Barro Artesanal", pintada: false, precio: 29320 },
  // FIBROCEMENTO PINTADO
  { articulo: "Misionera", medidas: "20altx18bocx16bas", material: "Fibrocemento", pintada: true, precio: 10340 },
  { articulo: "Misionera", medidas: "28altx18bocx15bas", material: "Fibrocemento", pintada: true, precio: 22750 },
  { articulo: "Misionera", medidas: "38altx28bocx20bas", material: "Fibrocemento", pintada: true, precio: 36200 },
  { articulo: "Misionera", medidas: "50altx37bocx32bas", material: "Fibrocemento", pintada: true, precio: 44460 },
  { articulo: "Misionera", medidas: "63altx40bocx32bas", material: "Fibrocemento", pintada: true, precio: 67220 },
  { articulo: "Misionera", medidas: "67altx37bocx32bas", material: "Fibrocemento", pintada: true, precio: 65080 },
  { articulo: "Misionera", medidas: "90altx40bocx35bas", material: "Fibrocemento", pintada: true, precio: 109880 },
  { articulo: "Misionera", medidas: "80altx50bocx40bas", material: "Fibrocemento", pintada: true, precio: 116350 },
  { articulo: "Misionera con Borde", medidas: "35CM", material: "Fibrocemento", pintada: true, precio: 35520 },
  { articulo: "Misionera con Borde", medidas: "45CM", material: "Fibrocemento", pintada: true, precio: 46550 },
  { articulo: "Misionera con Borde", medidas: "55CM", material: "Fibrocemento", pintada: true, precio: 84490 },
  { articulo: "Salteña", medidas: "77altx65bocx32bas", material: "Fibrocemento", pintada: true, precio: 126290 },
  { articulo: "Salteña", medidas: "50altx65bocx32bas", material: "Fibrocemento", pintada: true, precio: 105380 },
  { articulo: "Salteña", medidas: "65altx50 bocx25 bas", material: "Fibrocemento", pintada: true, precio: 68830 },
  { articulo: "Salteña", medidas: "45altx40bocx20bas", material: "Fibrocemento", pintada: true, precio: 33730 },
  { articulo: "Copa", medidas: "70altx50bocx28bas", material: "Fibrocemento", pintada: true, precio: 106710 },
  { articulo: "Copa", medidas: "55altx45bocx28bas", material: "Fibrocemento", pintada: true, precio: 49060 },
  { articulo: "Copa", medidas: "40altx33bocx16bas", material: "Fibrocemento", pintada: true, precio: 24530 },
  { articulo: "Bols", medidas: "28altx55bocx27bas", material: "Fibrocemento", pintada: true, precio: 31400 },
  { articulo: "Bols", medidas: "30altx80bocx33bas", material: "Fibrocemento", pintada: true, precio: 50290 },
  { articulo: "Cónica / Tradicional", medidas: "30altx30bocx18bas", material: "Fibrocemento", pintada: true, precio: 18400 },
  { articulo: "Cónica / Tradicional", medidas: "40altx40bocx25bas", material: "Fibrocemento", pintada: true, precio: 33730 },
  { articulo: "Cónica / Tradicional", medidas: "50altx50bocx29bas", material: "Fibrocemento", pintada: true, precio: 39860 },
  { articulo: "Cónica / Tradicional", medidas: "60altx60bocx36bas", material: "Fibrocemento", pintada: true, precio: 55190 },
  { articulo: "Cónica / Tradicional", medidas: "70altx70bocx44bas", material: "Fibrocemento", pintada: true, precio: 83250 },
  { articulo: "Andina", medidas: "35altx40bocx26bas", material: "Fibrocemento", pintada: true, precio: 35260 },
  { articulo: "Andina", medidas: "43altx50bocx33bas", material: "Fibrocemento", pintada: true, precio: 47010 },
  { articulo: "Andina", medidas: "55altx65bocx43bas", material: "Fibrocemento", pintada: true, precio: 83940 },
  { articulo: "Andina", medidas: "69altx80bocx53bas", material: "Fibrocemento", pintada: true, precio: 172600 },
  { articulo: "Cilindro", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 16970 },
  { articulo: "Cilindro", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 25500 },
  { articulo: "Cilindro", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: true, precio: 35000 },
  { articulo: "Cilindro", medidas: "45altx40bocx45bas", material: "Fibrocemento", pintada: true, precio: 79550 },
  { articulo: "Cilindro", medidas: "52altx52bocx52bas", material: "Fibrocemento", pintada: true, precio: 42430 },
  { articulo: "Cilindro", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: true, precio: 79550 },
  { articulo: "Cono", medidas: "100altx45bocx30bas", material: "Fibrocemento", pintada: true, precio: 68690 },
  { articulo: "Cono", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: true, precio: 44150 },
  { articulo: "Cono", medidas: "60altx38bocx30bas", material: "Fibrocemento", pintada: true, precio: 34340 },
  { articulo: "Cono Moderno", medidas: "40altx31bocx22bas", material: "Fibrocemento", pintada: true, precio: 24530 },
  { articulo: "Cono Moderno", medidas: "55altx36bocx24bas", material: "Fibrocemento", pintada: true, precio: 31890 },
  { articulo: "Cono Moderno", medidas: "70altx46bocx24bas", material: "Fibrocemento", pintada: true, precio: 42930 },
  { articulo: "Cono Moderno", medidas: "80altx46bocx28bas", material: "Fibrocemento", pintada: true, precio: 56310 },
  { articulo: "Cubo", medidas: "15altx15bocx15bas", material: "Fibrocemento", pintada: true, precio: 7760 },
  { articulo: "Cubo", medidas: "20altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 9700 },
  { articulo: "Cubo", medidas: "25altx25bocx25bas", material: "Fibrocemento", pintada: true, precio: 14220 },
  { articulo: "Cubo", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 19390 },
  { articulo: "Cubo", medidas: "35altx35bocx35bas", material: "Fibrocemento", pintada: true, precio: 24560 },
  { articulo: "Cubo", medidas: "40altx40bocx40bas", material: "Fibrocemento", pintada: true, precio: 29090 },
  { articulo: "Cubo", medidas: "45altx45bocx45bas", material: "Fibrocemento", pintada: true, precio: 38780 },
  { articulo: "Cubo", medidas: "50altx50bocx50bas", material: "Fibrocemento", pintada: true, precio: 51710 },
  { articulo: "Cubo", medidas: "60altx60bocx60bas", material: "Fibrocemento", pintada: true, precio: 90490 },
  { articulo: "Esfera", medidas: "20cm", material: "Fibrocemento", pintada: true, precio: 12260 },
  { articulo: "Esfera", medidas: "28cm", material: "Fibrocemento", pintada: true, precio: 17170 },
  { articulo: "Esfera", medidas: "40cm", material: "Fibrocemento", pintada: true, precio: 24530 },
  { articulo: "Esfera", medidas: "50cm", material: "Fibrocemento", pintada: true, precio: 49060 },
  { articulo: "Jardinera", medidas: "135lrgx50anchx45alt", material: "Fibrocemento", pintada: true, precio: 153310 },
  { articulo: "Jardinera", medidas: "100lrgx40anchx40alt", material: "Fibrocemento", pintada: true, precio: 73590 },
  { articulo: "Jardinera", medidas: "80lrgx35anchx40alt", material: "Fibrocemento", pintada: true, precio: 49060 },
  { articulo: "Jardinera", medidas: "60lrgx30anchx30alt", material: "Fibrocemento", pintada: true, precio: 30050 },
  { articulo: "Paila", medidas: "33cm", material: "Fibrocemento", pintada: true, precio: 11770 },
  { articulo: "Paila", medidas: "48cm", material: "Fibrocemento", pintada: true, precio: 17650 },
  { articulo: "Paila", medidas: "60cm", material: "Fibrocemento", pintada: true, precio: 22560 },
  { articulo: "Piramidal", medidas: "120altx45bocx30bas", material: "Fibrocemento", pintada: true, precio: 122650 },
  { articulo: "Piramidal", medidas: "80altx50bocx30bas", material: "Fibrocemento", pintada: true, precio: 73590 },
  { articulo: "Piramidal", medidas: "60altx35bocx25bas", material: "Fibrocemento", pintada: true, precio: 27300 },
  { articulo: "Piramidal", medidas: "40altx25bocx18bas", material: "Fibrocemento", pintada: true, precio: 18400 },
  { articulo: "Piramidal", medidas: "30altx30bocx15bas", material: "Fibrocemento", pintada: true, precio: 11650 },
  { articulo: "Piramidal", medidas: "20altx20bocx15bas", material: "Fibrocemento", pintada: true, precio: 8590 },
  { articulo: "Plato", medidas: "20cm", material: "Fibrocemento", pintada: true, precio: 4290 },
  { articulo: "Plato", medidas: "30cm", material: "Fibrocemento", pintada: true, precio: 7360 },
  { articulo: "Plato", medidas: "40cm", material: "Fibrocemento", pintada: true, precio: 11650 },
  { articulo: "Plato", medidas: "45cm", material: "Fibrocemento", pintada: true, precio: 15940 },
  { articulo: "Plato", medidas: "50cm", material: "Fibrocemento", pintada: true, precio: 19620 },
  { articulo: "Prisma", medidas: "80altx40bocx40bas", material: "Fibrocemento", pintada: true, precio: 68440 },
  { articulo: "Prisma", medidas: "60altx30bocx30bas", material: "Fibrocemento", pintada: true, precio: 31400 },
  { articulo: "Prisma", medidas: "40altx20bocx20bas", material: "Fibrocemento", pintada: true, precio: 11490 },
  { articulo: "Sanjuanina", medidas: "63altx39bocx33bas", material: "Fibrocemento", pintada: true, precio: 58870 },
  { articulo: "Tinaja", medidas: "50cm", material: "Fibrocemento", pintada: true, precio: 39250 },
  { articulo: "Tinaja", medidas: "60cm", material: "Fibrocemento", pintada: true, precio: 44150 },
  { articulo: "Tinaja", medidas: "80cm", material: "Fibrocemento", pintada: true, precio: 138110 },
  { articulo: "Vaso Antiguo", medidas: "45altx40bocx35bas", material: "Fibrocemento", pintada: true, precio: 24530 },
  { articulo: "Vaso Antiguo", medidas: "55altx50bocx35bas", material: "Fibrocemento", pintada: true, precio: 42930 },
  { articulo: "Ánfora", medidas: "75cm de alto", material: "Fibrocemento", pintada: true, precio: 86020 },
  { articulo: "Ánfora", medidas: "90cm de alto", material: "Fibrocemento", pintada: true, precio: 122100 },
  // FIBROCEMENTO SIN PINTAR
  { articulo: "Misionera", medidas: "20altx18bocx16bas", material: "Fibrocemento", pintada: false, precio: 9280 },
  { articulo: "Misionera", medidas: "28altx18bocx15bas", material: "Fibrocemento", pintada: false, precio: 20420 },
  { articulo: "Misionera", medidas: "38altx28bocx20bas", material: "Fibrocemento", pintada: false, precio: 32480 },
  { articulo: "Misionera", medidas: "50altx37bocx32bas", material: "Fibrocemento", pintada: false, precio: 39900 },
  { articulo: "Misionera", medidas: "63altx40bocx32bas", material: "Fibrocemento", pintada: false, precio: 60330 },
  { articulo: "Misionera", medidas: "90altx40bocx35bas", material: "Fibrocemento", pintada: false, precio: 98610 },
  { articulo: "Cubo", medidas: "15altx15bocx15bas", material: "Fibrocemento", pintada: false, precio: 6960 },
  { articulo: "Cubo", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 17400 },
  { articulo: "Cubo", medidas: "50altx50bocx50bas", material: "Fibrocemento", pintada: false, precio: 46410 },
  { articulo: "Cilindro", medidas: "30altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 15700 },
  { articulo: "Cilindro", medidas: "50altx30bocx30bas", material: "Fibrocemento", pintada: false, precio: 23590 },
  { articulo: "Piramidal", medidas: "80altx40bocx30bas", material: "Fibrocemento", pintada: false, precio: 43750 },
  { articulo: "Piramidal", medidas: "60altx35bocx25bas", material: "Fibrocemento", pintada: false, precio: 24350 },
  { articulo: "Piramidal", medidas: "30altx30bocx15bas", material: "Fibrocemento", pintada: false, precio: 10390 },
  { articulo: "Plato", medidas: "20cm", material: "Fibrocemento", pintada: false, precio: 3830 },
  { articulo: "Plato", medidas: "30cm", material: "Fibrocemento", pintada: false, precio: 6560 },
  { articulo: "Plato", medidas: "40cm", material: "Fibrocemento", pintada: false, precio: 10390 },
  // ROTOMOLDEADO
  { articulo: "Misionera", medidas: "20cm c/plato", material: "Rotomoldeado", pintada: false, precio: 8700 },
  { articulo: "Misionera", medidas: "30cm c/plato", material: "Rotomoldeado", pintada: false, precio: 20900 },
  { articulo: "Misionera", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 47900 },
  { articulo: "Misionera", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 80400 },
  { articulo: "Misionera", medidas: "60cm", material: "Rotomoldeado", pintada: false, precio: 119600 },
  { articulo: "Misionera Texturada", medidas: "20h x 15Ø x 18b", material: "Rotomoldeado", pintada: false, precio: 8100 },
  { articulo: "Misionera Texturada", medidas: "30h x 22Ø x 18b", material: "Rotomoldeado", pintada: false, precio: 25110 },
  { articulo: "Misionera Texturada", medidas: "40cm (29h x 22Ø x 18b)", material: "Rotomoldeado", pintada: false, precio: 42590 },
  { articulo: "Salteña con Pie", medidas: "25h x 20Ø x 20b (patas 10cm)", material: "Rotomoldeado", pintada: false, precio: 26500 },
  { articulo: "Cuenco", medidas: "32cm c/plato", material: "Rotomoldeado", pintada: false, precio: 52500 },
  { articulo: "Cuenco", medidas: "48cm c/plato", material: "Rotomoldeado", pintada: false, precio: 123500 },
  { articulo: "Gota", medidas: "40cm c/plato", material: "Rotomoldeado", pintada: false, precio: 49600 },
  { articulo: "Gota", medidas: "55cm c/plato", material: "Rotomoldeado", pintada: false, precio: 69600 },
  { articulo: "Gota", medidas: "70cm c/plato", material: "Rotomoldeado", pintada: false, precio: 83500 },
  { articulo: "Copa", medidas: "40cm c/plato", material: "Rotomoldeado", pintada: false, precio: 37900 },
  { articulo: "Copa", medidas: "55cm c/plato", material: "Rotomoldeado", pintada: false, precio: 73900 },
  { articulo: "Copa", medidas: "70cm c/plato", material: "Rotomoldeado", pintada: false, precio: 122500 },
  { articulo: "Cubo", medidas: "20x20x20", material: "Rotomoldeado", pintada: false, precio: 15200 },
  { articulo: "Cubo", medidas: "30x30x30", material: "Rotomoldeado", pintada: false, precio: 27100 },
  { articulo: "Cubo", medidas: "40x40x40", material: "Rotomoldeado", pintada: false, precio: 58700 },
  { articulo: "Cubo", medidas: "50x50x50", material: "Rotomoldeado", pintada: false, precio: 100600 },
  { articulo: "Piramidal", medidas: "40h x 25bo x 22b", material: "Rotomoldeado", pintada: false, precio: 26200 },
  { articulo: "Piramidal", medidas: "60h x 30bo x 25b", material: "Rotomoldeado", pintada: false, precio: 46300 },
  { articulo: "Piramidal", medidas: "70h x 35bo x 30b", material: "Rotomoldeado", pintada: false, precio: 61700 },
  { articulo: "Cilindro", medidas: "30x30", material: "Rotomoldeado", pintada: false, precio: 48960 },
  { articulo: "Cilindro", medidas: "50x50", material: "Rotomoldeado", pintada: false, precio: 72900 },
  { articulo: "Jardinera", medidas: "60x20x20", material: "Rotomoldeado", pintada: false, precio: 35200 },
  { articulo: "Jardinera", medidas: "80x27x30", material: "Rotomoldeado", pintada: false, precio: 73600 },
  { articulo: "Jardinera", medidas: "100x27x30", material: "Rotomoldeado", pintada: false, precio: 91500 },
  { articulo: "Van Gogh", medidas: "", material: "Rotomoldeado", pintada: false, precio: 24300 },
  { articulo: "Paris", medidas: "30cm", material: "Rotomoldeado", pintada: false, precio: 47700 },
  { articulo: "Paris", medidas: "44cm", material: "Rotomoldeado", pintada: false, precio: 55700 },
  { articulo: "🎁 Combo Copa Trío", medidas: "Copa 40 + 50 + 60cm", material: "Combo", pintada: false, precio: 234000 },
  { articulo: "🎁 Combo Misionera Trío", medidas: "Misionera 40 + 55 + 70cm c/plato", material: "Combo", pintada: false, precio: 191500 },
  { articulo: "🎁 Combo Salteña Trío", medidas: "Salteña 40 + 55 + 70cm c/plato", material: "Combo", pintada: false, precio: 200000 },
  { articulo: "🎁 Combo Entrada", medidas: "2× Misionera 55cm + Copa 40cm", material: "Combo", pintada: false, precio: 179000 },
  { articulo: "🎁 Combo Terraza", medidas: "2× Copa 50cm + Cuenco 32cm", material: "Combo", pintada: false, precio: 205500 },
  { articulo: "🎁 Combo Living", medidas: "2× Misionera 70cm + Misionera 40cm", material: "Combo", pintada: false, precio: 204000 },
  { articulo: "🎁 Combo Misionera Texturada", medidas: "30cm + 40cm", material: "Combo", pintada: false, precio: 59000 },
  // CERÁMICA
  { articulo: "Coco N°1", medidas: "10h x 11d x 8b", material: "Cerámica", pintada: false, precio: 26020 },
  { articulo: "Coco N°2", medidas: "14h x 14d x 11b", material: "Cerámica", pintada: false, precio: 39960 },
  { articulo: "Coco N°3", medidas: "18h x 17d x 14b", material: "Cerámica", pintada: false, precio: 71410 },
  { articulo: "Coco N°4", medidas: "24h x 22d x 18b", material: "Cerámica", pintada: false, precio: 131910 },
  { articulo: "Coco N°5", medidas: "32h x 28d x 28b", material: "Cerámica", pintada: false, precio: 208310 },
  { articulo: "Maceta N°1", medidas: "9h x 11d x 6b", material: "Cerámica", pintada: false, precio: 14730 },
  { articulo: "Maceta N°2", medidas: "14h x 16d x 10b", material: "Cerámica", pintada: false, precio: 25990 },
  { articulo: "Maceta N°3", medidas: "18h x 20d x 12b", material: "Cerámica", pintada: false, precio: 37100 },
  { articulo: "Maceta N°4", medidas: "31h x 29d x 18b", material: "Cerámica", pintada: false, precio: 83760 },
  // PLÁSTICO (muestra)
  { articulo: "Plato Nº12", medidas: "Nº12", material: "Plástico", pintada: false, precio: 890 },
  { articulo: "Plato Nº16", medidas: "Nº16", material: "Plástico", pintada: false, precio: 960 },
  { articulo: "Plato Nº20", medidas: "Nº20", material: "Plástico", pintada: false, precio: 1240 },
  { articulo: "Plato Nº24", medidas: "Nº24", material: "Plástico", pintada: false, precio: 1640 },
  { articulo: "Plato Nº30", medidas: "Nº30 (T.A)", material: "Plástico", pintada: false, precio: 2040 },
  { articulo: "Plato Nº36", medidas: "Nº36", material: "Plástico", pintada: false, precio: 2860 },
  { articulo: "Plato Nº40", medidas: "Nº40", material: "Plástico", pintada: false, precio: 3770 },
  { articulo: "Regadera", medidas: "2 lts", material: "Plástico", pintada: false, precio: 7830 },
  { articulo: "Regadera", medidas: "5 lts", material: "Plástico", pintada: false, precio: 13730 },
  { articulo: "Regadera", medidas: "10 lts", material: "Plástico", pintada: false, precio: 24770 },
  { articulo: "MAC JARDINERA", medidas: "35 CM", material: "Plástico", pintada: false, precio: 3540 },
  { articulo: "MAC JARDINERA", medidas: "45 CM", material: "Plástico", pintada: false, precio: 5220 },
  { articulo: "MAC JARDINERA", medidas: "60 CM", material: "Plástico", pintada: false, precio: 10600 },
  { articulo: "MAC JARDINERA IMPERIO", medidas: "50 CM", material: "Plástico", pintada: false, precio: 15880 },
  { articulo: "MAC JARDINERA IMPERIO", medidas: "80 CM", material: "Plástico", pintada: false, precio: 35530 },
  // INSUMOS — Fertilizantes (se clasifican automáticamente)
  { articulo: "GUANO MURCIELAGO X 250 GRS", medidas: "", material: "Insumos", pintada: false, precio: 13450 },
  { articulo: "HUMUS DE LOMBRIS X 500CC", medidas: "", material: "Insumos", pintada: false, precio: 11450 },
  { articulo: "MICORRIZAS X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 10480 },
  { articulo: "TRICHODERMA ENRAIZANTE X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 13470 },
  { articulo: "FERTILIZ ANTISHOCK *100 CC", medidas: "", material: "Insumos", pintada: false, precio: 12710 },
  { articulo: "FERTILIZ ANTISHOCK *500 CC", medidas: "", material: "Insumos", pintada: false, precio: 47200 },
  { articulo: "FERTILIZ *200 CC FLORA/folla/poten.", medidas: "", material: "Insumos", pintada: false, precio: 7040 },
  { articulo: "FERTILIZ *1000CC FLORA/folla/peton.", medidas: "", material: "Insumos", pintada: false, precio: 22120 },
  { articulo: "FERTILIZ ESPECIAL ORQUIDEAS *200 CM.", medidas: "", material: "Insumos", pintada: false, precio: 11110 },
  { articulo: "LJF-TRIPLE 15 *1000GRS", medidas: "", material: "Insumos", pintada: false, precio: 6620 },
  { articulo: "LJF-UREA *1000GRS", medidas: "", material: "Insumos", pintada: false, precio: 6560 },
  { articulo: "JF ABONO ESPECIAL * 120CC", medidas: "", material: "Insumos", pintada: false, precio: 4810 },
  { articulo: "JF ABONO X 200CC FLORACION -FOLLAJE-HORMONA", medidas: "", material: "Insumos", pintada: false, precio: 5880 },
  { articulo: "ACRECIO FERTILIZANTE X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 12380 },
  { articulo: "MEGAGREEN FERTILIZANTE POLVO 50GMS", medidas: "", material: "Insumos", pintada: false, precio: 16600 },
  // INSUMOS — Insecticidas
  { articulo: "PARAISO ORUGUICIDA X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 10650 },
  { articulo: "BTI LARVICIDA INSECTICIDA BIOLOGICO * 30 cc", medidas: "", material: "Insumos", pintada: false, precio: 3720 },
  { articulo: "JABON POTASICO CANELA Y NEEM X 250CC", medidas: "", material: "Insumos", pintada: false, precio: 14510 },
  { articulo: "JABON POTASICO NEUTRO X 500CC", medidas: "", material: "Insumos", pintada: false, precio: 24780 },
  { articulo: "NEEM PURO X 30CC", medidas: "", material: "Insumos", pintada: false, precio: 6380 },
  { articulo: "BEAUVERIA X 100CC", medidas: "", material: "Insumos", pintada: false, precio: 4720 },
  { articulo: "ARAÑUELA X 30CC (ACARICIDA)", medidas: "", material: "Insumos", pintada: false, precio: 2820 },
  { articulo: "REPELENTE DE INSECTOS * 30 cc", medidas: "", material: "Insumos", pintada: false, precio: 4990 },
  { articulo: "HORMIGUICIDA *120 CC.", medidas: "", material: "Insumos", pintada: false, precio: 6270 },
  { articulo: "HORMIGUICIDA *500 CC.", medidas: "", material: "Insumos", pintada: false, precio: 18120 },
  { articulo: "X-TERMIXAN *1000 GRS. POTE", medidas: "", material: "Insumos", pintada: false, precio: 17380 },
  { articulo: "X-VELOXAN *250 CC", medidas: "", material: "Insumos", pintada: false, precio: 16260 },
  { articulo: "X-FUMIXAN FOG * 120 cc", medidas: "", material: "Insumos", pintada: false, precio: 11430 },
  { articulo: "X-MATA-HORMIGAS *250 CC.", medidas: "", material: "Insumos", pintada: false, precio: 8910 },
  { articulo: "X-SISTEMICO *60 CC. 'D'", medidas: "", material: "Insumos", pintada: false, precio: 9980 },
  { articulo: "MYRMEC. X 200GMS 20+5 DE REGALO", medidas: "", material: "Insumos", pintada: false, precio: 4070 },
  { articulo: "MIREX X 100GMS", medidas: "", material: "Insumos", pintada: false, precio: 2590 },
  { articulo: "GEL MATA CUCARACHA * 60 GRS", medidas: "", material: "Insumos", pintada: false, precio: 19470 },
  { articulo: "GEL MATA HORMIGAS X 40 GRS", medidas: "", material: "Insumos", pintada: false, precio: 15680 },
  { articulo: "KAOTRINA X 60 CC", medidas: "", material: "Insumos", pintada: false, precio: 7410 },
  { articulo: "TUTORES *040 CM.", medidas: "", material: "Insumos", pintada: false, precio: 3280 },
  { articulo: "TUTORES *060 CM", medidas: "", material: "Insumos", pintada: false, precio: 4280 },
  { articulo: "TUTORES *100 CM", medidas: "", material: "Insumos", pintada: false, precio: 6560 },
  { articulo: "TUTORES *120CM", medidas: "", material: "Insumos", pintada: false, precio: 8260 },
  { articulo: "TUTORES *160 CM", medidas: "", material: "Insumos", pintada: false, precio: 11400 },
  // INSUMOS — Sustratos
  { articulo: "J-TIERRA *05 DM3", medidas: "", material: "Insumos", pintada: false, precio: 2220 },
  { articulo: "J-TIERRA *25 DM3", medidas: "", material: "Insumos", pintada: false, precio: 5420 },
  { articulo: "J-TURBA JOR *5DM", medidas: "", material: "Insumos", pintada: false, precio: 5390 },
  { articulo: "J-TURBA JOR *25DM", medidas: "", material: "Insumos", pintada: false, precio: 13680 },
  { articulo: "J-PERLITA *3DM NUTRI VIDA", medidas: "", material: "Insumos", pintada: false, precio: 2140 },
  { articulo: "J-PERLITA PERLINO *25DM", medidas: "", material: "Insumos", pintada: false, precio: 14820 },
  { articulo: "J-POMEX *10DM", medidas: "", material: "Insumos", pintada: false, precio: 7600 },
  { articulo: "J-POMEX *25DM", medidas: "", material: "Insumos", pintada: false, precio: 16150 },
  { articulo: "J-HUMUS *05 DM3", medidas: "", material: "Insumos", pintada: false, precio: 3140 },
  { articulo: "J-HUMUS *25 DM3", medidas: "", material: "Insumos", pintada: false, precio: 11680 },
  { articulo: "J-COMPUESTO ORGANICO *10 DM3", medidas: "", material: "Insumos", pintada: false, precio: 3420 },
  { articulo: "J-COMPUESTO ORGANICO *25 DM3", medidas: "", material: "Insumos", pintada: false, precio: 6410 },
  { articulo: "J-SUSTRATO ORQUIDEAS X *3 DM ECO", medidas: "", material: "Insumos", pintada: false, precio: 2710 },
  { articulo: "J-CHIP *10DM", medidas: "", material: "Insumos", pintada: false, precio: 2990 },
  { articulo: "J-CHIP *25DM", medidas: "", material: "Insumos", pintada: false, precio: 6470 },
  { articulo: "J-VERMICULITA NUTRI VIDA *3DM", medidas: "", material: "Insumos", pintada: false, precio: 6610 },
  { articulo: "J-VERMICULITA *25DM", medidas: "", material: "Insumos", pintada: false, precio: 38000 },
  { articulo: "MUSGO BOLSA 25DM", medidas: "", material: "Insumos", pintada: false, precio: 9980 },
  { articulo: "Tierra Abonada", medidas: "5 DM", material: "Insumos", pintada: false, precio: 4180 },
  { articulo: "Tierra Abonada", medidas: "10 DM", material: "Insumos", pintada: false, precio: 4940 },
  { articulo: "Tierra Abonada", medidas: "25 DM", material: "Insumos", pintada: false, precio: 6650 },
  { articulo: "Resaca", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5320 },
  { articulo: "Resaca", medidas: "25 DM", material: "Insumos", pintada: false, precio: 8550 },
  { articulo: "Pinocha", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5600 },
  { articulo: "Pinocha", medidas: "10 DM", material: "Insumos", pintada: false, precio: 6200 },
  { articulo: "Compost", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5320 },
  { articulo: "Compost", medidas: "25 DM", material: "Insumos", pintada: false, precio: 8740 },
  { articulo: "Perlita", medidas: "5 DM", material: "Insumos", pintada: false, precio: 6200 },
  { articulo: "Perlita", medidas: "10 DM", material: "Insumos", pintada: false, precio: 9200 },
  { articulo: "Turba", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Turba", medidas: "10 DM", material: "Insumos", pintada: false, precio: 8740 },
  { articulo: "Sustrato Cactus y Suculentas", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Sustrato Cactus y Suculentas", medidas: "10 DM", material: "Insumos", pintada: false, precio: 7220 },
  { articulo: "Tierra Abonada Ferticam", medidas: "5 DM", material: "Insumos", pintada: false, precio: 4180 },
  { articulo: "Tierra Abonada Ferticam", medidas: "25 DM", material: "Insumos", pintada: false, precio: 6650 },
  { articulo: "Turba Ferticam", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Turba Ferticam", medidas: "10 DM", material: "Insumos", pintada: false, precio: 8740 },
  { articulo: "Cactus y Suculentas Ferticam", medidas: "5 DM", material: "Insumos", pintada: false, precio: 5890 },
  { articulo: "Cactus y Suculentas Ferticam", medidas: "10 DM", material: "Insumos", pintada: false, precio: 7220 },

  // ROTOMOLDEADO — nuevos modelos
  { articulo: "Cubo", medidas: "25x25x25", material: "Rotomoldeado", pintada: false, precio: 21000 },
  { articulo: "Cubo", medidas: "35x35x35", material: "Rotomoldeado", pintada: false, precio: 39800 },
  { articulo: "Piramidal", medidas: "50h x 25bo x 22b", material: "Rotomoldeado", pintada: false, precio: 32100 },
  { articulo: "Jardinera", medidas: "80x20x20", material: "Rotomoldeado", pintada: false, precio: 46200 },
  { articulo: "Jardinera", medidas: "100x20x20", material: "Rotomoldeado", pintada: false, precio: 55700 },
  { articulo: "Jardinera", medidas: "60x27x30", material: "Rotomoldeado", pintada: false, precio: 55700 },
  { articulo: "Cilindro", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 54100 },
  { articulo: "Cilindro", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 80600 },
  { articulo: "Misionera Texturada", medidas: "20cm", material: "Rotomoldeado", pintada: false, precio: 8000 },
  { articulo: "Misionera Texturada", medidas: "30cm", material: "Rotomoldeado", pintada: false, precio: 24900 },
  { articulo: "Misionera Texturada", medidas: "40cm", material: "Rotomoldeado", pintada: false, precio: 48700 },
  { articulo: "Misionera Texturada", medidas: "50cm", material: "Rotomoldeado", pintada: false, precio: 95500 },
  { articulo: "Plato Misionera", medidas: "Chico", material: "Rotomoldeado", pintada: false, precio: 7700 },
  { articulo: "Plato Misionera", medidas: "Mediano", material: "Rotomoldeado", pintada: false, precio: 13100 },
  { articulo: "Plato Misionera", medidas: "Grande", material: "Rotomoldeado", pintada: false, precio: 18600 },

  // ROTOMOLDEADO — RAYUM Andina (actualizado)
  { articulo: "JARDINERA 40x20x30", medidas: "40x20x30", material: "Rotomoldeado", pintada: false, precio: 43700 },
  { articulo: "JARDINERA 60x20x30", medidas: "60x20x30", material: "Rotomoldeado", pintada: false, precio: 81800 },
  { articulo: "JARDINERA 80x20x30", medidas: "80x20x30", material: "Rotomoldeado", pintada: false, precio: 114000 },

  // ROTOMOLDEADO — RAYUM Andina (actualizado)
  { articulo: "ANDINA N27 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 24500 },
  { articulo: "ANDINA N40 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 53500 },
  { articulo: "ANDINA N50 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 91300 },
  { articulo: "ANDINA N65 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 180900 },
  { articulo: "ANDINA N80 RUSTICA", medidas: "", material: "Rotomoldeado", pintada: false, precio: 288600 },
  { articulo: "ANDINA N40 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 46500 },
  { articulo: "ANDINA N50 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 79400 },
  { articulo: "ANDINA N65 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 157300 },
  { articulo: "ANDINA N80 LISO", medidas: "", material: "Rotomoldeado", pintada: false, precio: 251000 },
  { articulo: "JARDINERA RAYUM", medidas: "40x20x30", material: "Rotomoldeado", pintada: false, precio: 43700 },
  { articulo: "JARDINERA RAYUM", medidas: "60x20x30", material: "Rotomoldeado", pintada: false, precio: 81800 },
  { articulo: "JARDINERA RAYUM", medidas: "80x20x30", material: "Rotomoldeado", pintada: false, precio: 114000 },
];
